// Generated by TeaQL. Do not edit directly.
import Foundation
import TeaQLCore

public struct Platform: TeaQLEntity, TeaQLMutationRootedEntity {
    public var id: Int64 = 0
    public var name: String? = nil
    public var baseUrl: String? = nil
    public var createTime: Date = Date(timeIntervalSince1970: 0)
    public var updateTime: Date = Date(timeIntervalSince1970: 0)
    public var version: Int64 = 0
    public var schoolTypeList: [SchoolType] = []
    public var schoolList: [School] = []
    private var _loadedFields: Set<String> = []
    public var teaqlEntityRoot = EntityRoot()
    private static let teaqlIDLock = NSLock()
    nonisolated(unsafe) private static var teaqlNextTemporaryID: Int64 = 0
    private var teaqlLedgerID: Int64 = 0
    public var teaqlEntityKey: EntityKey { EntityKey(entity: "Platform", id: .int(id == 0 ? teaqlLedgerID : id)) }

    private enum CodingKeys: String, CodingKey {
        case id
        case name
        case baseUrl
        case createTime
        case updateTime
        case version
    }

    public init() {
        Self.teaqlIDLock.lock(); Self.teaqlNextTemporaryID -= 1; teaqlLedgerID = Self.teaqlNextTemporaryID; Self.teaqlIDLock.unlock()
        _loadedFields = Set(["id", "name", "baseUrl", "createTime", "updateTime", "version"])
        teaqlEntityRoot.markAsNew(teaqlEntityKey)
    }

    public static let descriptor = EntityDescriptor(
        name: "Platform",
        table: "platform_data",
        properties: [
            PropertyDescriptor(name: "id", modelName: "id", column: "id", type: .int, nullable: true, isID: true, isVersion: false),
            PropertyDescriptor(name: "name", modelName: "name", column: "name", type: .string, nullable: true, isID: false, isVersion: false),
            PropertyDescriptor(name: "baseUrl", modelName: "base_url", column: "base_url", type: .string, nullable: true, isID: false, isVersion: false),
            PropertyDescriptor(name: "createTime", modelName: "create_time", column: "create_time", type: .date, nullable: true, isID: false, isVersion: false),
            PropertyDescriptor(name: "updateTime", modelName: "update_time", column: "update_time", type: .date, nullable: true, isID: false, isVersion: false),
            PropertyDescriptor(name: "version", modelName: "version", column: "version", type: .int, nullable: true, isID: false, isVersion: true)
        ]
    )

    public static func from(record: TeaQLRecord) throws -> Self {
        var entity = Self()
        entity._loadedFields.removeAll()
        entity.id = record["id"]?.int64Value ?? 0
        if record.keys.contains("id") { entity._loadedFields.insert("id") }
        entity.name = record["name"]?.stringValue ?? nil
        if record.keys.contains("name") { entity._loadedFields.insert("name") }
        entity.baseUrl = record["baseUrl"]?.stringValue ?? nil
        if record.keys.contains("baseUrl") { entity._loadedFields.insert("baseUrl") }
        entity.createTime = record["createTime"]?.dateValue ?? Date(timeIntervalSince1970: 0)
        if record.keys.contains("createTime") { entity._loadedFields.insert("createTime") }
        entity.updateTime = record["updateTime"]?.dateValue ?? Date(timeIntervalSince1970: 0)
        if record.keys.contains("updateTime") { entity._loadedFields.insert("updateTime") }
        entity.version = record["version"]?.int64Value ?? 0
        if record.keys.contains("version") { entity._loadedFields.insert("version") }
        if let relationValue = record["schoolTypeList"] {
            switch relationValue {
            case .array(let values):
                entity.schoolTypeList = try values.compactMap {
                    guard case .object(let childRecord) = $0 else { return nil }
                    return try SchoolType.from(record: childRecord)
                }
            case .object(let childRecord):
                entity.schoolTypeList = [try SchoolType.from(record: childRecord)]
            case .null:
                entity.schoolTypeList = []
            default:
                throw TeaQLError.execution("Invalid relation payload: schoolTypeList")
            }
            entity._loadedFields.insert("schoolTypeList")
        }
        if let relationValue = record["schoolList"] {
            switch relationValue {
            case .array(let values):
                entity.schoolList = try values.compactMap {
                    guard case .object(let childRecord) = $0 else { return nil }
                    return try School.from(record: childRecord)
                }
            case .object(let childRecord):
                entity.schoolList = [try School.from(record: childRecord)]
            case .null:
                entity.schoolList = []
            default:
                throw TeaQLError.execution("Invalid relation payload: schoolList")
            }
            entity._loadedFields.insert("schoolList")
        }
        let temporaryKey = entity.teaqlEntityKey
        entity.teaqlLedgerID = entity.id
        entity.teaqlEntityRoot.rekey(temporaryKey, to: entity.teaqlEntityKey)
        entity.teaqlEntityRoot.markAsPersisted(entity.teaqlEntityKey)
        entity.teaqlEntityRoot.setOriginalVersion(entity.teaqlEntityKey, version: entity.version)
        return entity
    }

    public static func from(record: TeaQLRecord, root: EntityRoot) throws -> Self {
        var entity = try from(record: record)
        entity.teaqlAttachRoot(root)
        return entity
    }

    public mutating func teaqlAttachRoot(_ root: EntityRoot) {
        if teaqlEntityRoot !== root { root.merge(from: teaqlEntityRoot); teaqlEntityRoot = root }
        for index in schoolTypeList.indices { schoolTypeList[index].teaqlAttachRoot(root) }
        for index in schoolList.indices { schoolList[index].teaqlAttachRoot(root) }
    }

    public func toRecord() -> TeaQLRecord {
        [
            "id": .int(id),
            "name": name.map(TeaQLValue.string) ?? .null,
            "baseUrl": baseUrl.map(TeaQLValue.string) ?? .null,
            "createTime": .date(createTime),
            "updateTime": .date(updateTime),
            "version": .int(version)
        ]
    }

    public func toMutationRecord() -> TeaQLRecord {
        var record: TeaQLRecord = [:]
        if _loadedFields.contains("id") {
            record["id"] = .int(id)
        }
        if _loadedFields.contains("name") {
            record["name"] = name.map(TeaQLValue.string) ?? .null
        }
        if _loadedFields.contains("baseUrl") {
            record["base_url"] = baseUrl.map(TeaQLValue.string) ?? .null
        }
        if _loadedFields.contains("createTime") {
            record["create_time"] = .date(createTime)
        }
        if _loadedFields.contains("updateTime") {
            record["update_time"] = .date(updateTime)
        }
        if _loadedFields.contains("version") {
            record["version"] = .int(version)
        }
        return record
    }

    public func isLoaded(_ field: String) -> Bool { _loadedFields.contains(field) }

    @discardableResult
    public mutating func markLoadedOnly(_ fields: String...) -> Self {
        _loadedFields = Set(fields)
        return self
    }

    @discardableResult
    public mutating func updateId(_ value: Int64) -> Self {
        self.id = value
        self._loadedFields.insert("id")
        self.teaqlEntityRoot.set(teaqlEntityKey, field: "id", value: .int(value))
        return self
    }


    @discardableResult
    public mutating func updateName(_ value: String?) -> Self {
        self.name = value
        self._loadedFields.insert("name")
        self.teaqlEntityRoot.set(teaqlEntityKey, field: "name", value: value.map(TeaQLValue.string) ?? .null)
        return self
    }


    @discardableResult
    public mutating func updateBaseUrl(_ value: String?) -> Self {
        self.baseUrl = value
        self._loadedFields.insert("baseUrl")
        self.teaqlEntityRoot.set(teaqlEntityKey, field: "base_url", value: value.map(TeaQLValue.string) ?? .null)
        return self
    }


    @discardableResult
    public mutating func updateCreateTime(_ value: Date) -> Self {
        self.createTime = value
        self._loadedFields.insert("createTime")
        self.teaqlEntityRoot.set(teaqlEntityKey, field: "create_time", value: .date(value))
        return self
    }


    @discardableResult
    public mutating func updateUpdateTime(_ value: Date) -> Self {
        self.updateTime = value
        self._loadedFields.insert("updateTime")
        self.teaqlEntityRoot.set(teaqlEntityKey, field: "update_time", value: .date(value))
        return self
    }


    @discardableResult
    public mutating func updateVersion(_ value: Int64) -> Self {
        self.version = value
        self._loadedFields.insert("version")
        self.teaqlEntityRoot.set(teaqlEntityKey, field: "version", value: .int(value))
        return self
    }


    public func auditAs(_ reason: String) -> PlatformAudited {
        PlatformAudited(entity: self, reason: reason)
    }
}

public struct PlatformAudited: Sendable {
    public let entity: Platform
    public let reason: String

    public func save(_ context: UserContext) async throws -> Platform {
        let saved = try await AuditedEntity(entity: entity, reason: reason).save(context)
        for var child in entity.schoolTypeList {
            child.teaqlAttachRoot(context.entityRoot)
            child.updatePlatform(saved.id)
            _ = try await child.auditAs(reason).save(context)
        }
        for var child in entity.schoolList {
            child.teaqlAttachRoot(context.entityRoot)
            child.updatePlatform(saved.id)
            _ = try await child.auditAs(reason).save(context)
        }
        return saved
    }

    public func delete(_ context: UserContext) async throws -> Platform {
        try await AuditedEntity(entity: entity, reason: reason).delete(context)
    }
}