// Generated by TeaQL. Do not edit directly.
import Foundation
import TeaQLCore

public struct Platform: TeaQLEntity, TeaQLMutationRootedEntity {
    public var id: Int64 = 0
    public var name: String? = nil
    public var baseUrl: String? = nil
    public var createTime: Date? = nil
    public var updateTime: Date? = nil
    public var version: Int64 = 0
    public var schoolTypeList: [SchoolType] = []
    public var schoolList: [School] = []
    private var _loadedFields: Set<String> = []
    public var teaqlEntityRoot = EntityRoot()
    private static let teaqlIDLock = NSLock()
    nonisolated(unsafe) private static var teaqlNextTemporaryID: Int64 = 0
    private var teaqlLedgerID: Int64 = 0
    public var teaqlEntityKey: EntityKey { EntityKey(entity: "Platform", id: .int(id == 0 ? teaqlLedgerID : id)) }
    var teaqlPreflightID: Int64 { id == 0 ? teaqlLedgerID : id }

    private enum CodingKeys: String, CodingKey {
        case id
        case name
        case baseUrl
        case createTime
        case updateTime
        case version
    }

    public init() {
        Self.teaqlIDLock.lock(); Self.teaqlNextTemporaryID -= 1; teaqlLedgerID = Self.teaqlNextTemporaryID; Self.teaqlIDLock.unlock()
        _loadedFields = Set(["id", "name", "baseUrl", "createTime", "updateTime", "version"])
        teaqlEntityRoot.markAsNew(teaqlEntityKey)
    }

    public static let descriptor = EntityDescriptor(
        name: "Platform",
        table: "platform_data",
        properties: [
            PropertyDescriptor(name: "id", modelName: "id", column: "id", type: .int, nullable: false, isID: true, isVersion: false),
            PropertyDescriptor(name: "name", modelName: "name", column: "name", type: .string, nullable: false, isID: false, isVersion: false),
            PropertyDescriptor(name: "baseUrl", modelName: "base_url", column: "base_url", type: .string, nullable: false, isID: false, isVersion: false),
            PropertyDescriptor(name: "createTime", modelName: "create_time", column: "create_time", type: .timestamp, nullable: false, isID: false, isVersion: false),
            PropertyDescriptor(name: "updateTime", modelName: "update_time", column: "update_time", type: .timestamp, nullable: false, isID: false, isVersion: false),
            PropertyDescriptor(name: "version", modelName: "version", column: "version", type: .int, nullable: false, isID: false, isVersion: true)
        ]
    )

    public static func from(record: TeaQLRecord) throws -> Self {
        var entity = Self()
        entity._loadedFields.removeAll()
        entity.id = record["id"]?.int64Value ?? 0
        if record.keys.contains("id") { entity._loadedFields.insert("id") }
        entity.name = record["name"]?.stringValue
        if record.keys.contains("name") { entity._loadedFields.insert("name") }
        entity.baseUrl = record["baseUrl"]?.stringValue
        if record.keys.contains("baseUrl") { entity._loadedFields.insert("baseUrl") }
        entity.createTime = record["createTime"]?.dateValue
        if record.keys.contains("createTime") { entity._loadedFields.insert("createTime") }
        entity.updateTime = record["updateTime"]?.dateValue
        if record.keys.contains("updateTime") { entity._loadedFields.insert("updateTime") }
        entity.version = record["version"]?.int64Value ?? 0
        if record.keys.contains("version") { entity._loadedFields.insert("version") }
        if let relationValue = record["schoolTypeList"] {
            switch relationValue {
            case .array(let values):
                entity.schoolTypeList = try values.compactMap {
                    guard case .object(let childRecord) = $0 else { return nil }
                    return try SchoolType.from(record: childRecord)
                }
            case .object(let childRecord):
                entity.schoolTypeList = [try SchoolType.from(record: childRecord)]
            case .null:
                entity.schoolTypeList = []
            default:
                throw TeaQLError.execution("Invalid relation payload: schoolTypeList")
            }
            entity._loadedFields.insert("schoolTypeList")
        }
        if let relationValue = record["schoolList"] {
            switch relationValue {
            case .array(let values):
                entity.schoolList = try values.compactMap {
                    guard case .object(let childRecord) = $0 else { return nil }
                    return try School.from(record: childRecord)
                }
            case .object(let childRecord):
                entity.schoolList = [try School.from(record: childRecord)]
            case .null:
                entity.schoolList = []
            default:
                throw TeaQLError.execution("Invalid relation payload: schoolList")
            }
            entity._loadedFields.insert("schoolList")
        }
        let temporaryKey = entity.teaqlEntityKey
        entity.teaqlLedgerID = entity.id
        entity.teaqlEntityRoot.rekey(temporaryKey, to: entity.teaqlEntityKey)
        entity.teaqlEntityRoot.markAsPersisted(entity.teaqlEntityKey)
        entity.teaqlEntityRoot.setOriginalVersion(entity.teaqlEntityKey, version: entity.version)
        return entity
    }

    public static func from(record: TeaQLRecord, root: EntityRoot) throws -> Self {
        var entity = try from(record: record)
        entity.teaqlAttachRoot(root)
        return entity
    }

    public mutating func teaqlAttachRoot(_ root: EntityRoot) {
        if teaqlEntityRoot !== root { root.merge(from: teaqlEntityRoot); teaqlEntityRoot = root }
        for index in schoolTypeList.indices { schoolTypeList[index].teaqlAttachRoot(root) }
        for index in schoolList.indices { schoolList[index].teaqlAttachRoot(root) }
    }

    public func toRecord() -> TeaQLRecord {
        [
            "id": .int(id),
            "name": name.map { .string($0) } ?? .null,
            "baseUrl": baseUrl.map { .string($0) } ?? .null,
            "createTime": createTime.map { .timestamp(Int64($0.timeIntervalSince1970 * 1_000)) } ?? .null,
            "updateTime": updateTime.map { .timestamp(Int64($0.timeIntervalSince1970 * 1_000)) } ?? .null,
            "version": .int(version)
        ]
    }

    public func toMutationRecord() -> TeaQLRecord {
        var record: TeaQLRecord = [:]
        if _loadedFields.contains("id") {
            record["id"] = .int(id)
        }
        if _loadedFields.contains("name") {
            record["name"] = name.map { .string($0) } ?? .null
        }
        if _loadedFields.contains("baseUrl") {
            record["base_url"] = baseUrl.map { .string($0) } ?? .null
        }
        if _loadedFields.contains("createTime") {
            record["create_time"] = createTime.map { .timestamp(Int64($0.timeIntervalSince1970 * 1_000)) } ?? .null
        }
        if _loadedFields.contains("updateTime") {
            record["update_time"] = updateTime.map { .timestamp(Int64($0.timeIntervalSince1970 * 1_000)) } ?? .null
        }
        if _loadedFields.contains("version") {
            record["version"] = .int(version)
        }
        return record
    }

    public func isLoaded(_ field: String) -> Bool { _loadedFields.contains(field) }

    @discardableResult
    public mutating func markLoadedOnly(_ fields: String...) -> Self {
        _loadedFields = Set(fields)
        return self
    }

    @discardableResult
    public mutating func updateId(_ value: Int64) -> Self {
        self.id = value
        self._loadedFields.insert("id")
        self.teaqlEntityRoot.set(teaqlEntityKey, field: "id", value: .int(value))
        return self
    }


    @discardableResult
    public mutating func updateName(_ value: String?) -> Self {
        self.name = value
        self._loadedFields.insert("name")
        self.teaqlEntityRoot.set(teaqlEntityKey, field: "name", value: value.map { .string($0) } ?? .null)
        return self
    }


    @discardableResult
    public mutating func updateBaseUrl(_ value: String?) -> Self {
        self.baseUrl = value
        self._loadedFields.insert("baseUrl")
        self.teaqlEntityRoot.set(teaqlEntityKey, field: "base_url", value: value.map { .string($0) } ?? .null)
        return self
    }


    @discardableResult
    public mutating func updateCreateTime(_ value: Date?) -> Self {
        self.createTime = value
        self._loadedFields.insert("createTime")
        self.teaqlEntityRoot.set(teaqlEntityKey, field: "create_time", value: value.map { .timestamp(Int64($0.timeIntervalSince1970 * 1_000)) } ?? .null)
        return self
    }


    @discardableResult
    public mutating func updateUpdateTime(_ value: Date?) -> Self {
        self.updateTime = value
        self._loadedFields.insert("updateTime")
        self.teaqlEntityRoot.set(teaqlEntityKey, field: "update_time", value: value.map { .timestamp(Int64($0.timeIntervalSince1970 * 1_000)) } ?? .null)
        return self
    }


    @discardableResult
    public mutating func updateVersion(_ value: Int64) -> Self {
        self.version = value
        self._loadedFields.insert("version")
        self.teaqlEntityRoot.set(teaqlEntityKey, field: "version", value: .int(value))
        return self
    }


    public func auditAs(_ reason: String) -> PlatformAudited {
        PlatformAudited(entity: self, reason: reason)
    }

    @discardableResult
    public mutating func markForDeletion() -> Self {
        teaqlEntityRoot.markAsDeleted(teaqlEntityKey)
        return self
    }
}

public struct PlatformAudited: Sendable {
    public let entity: Platform
    public let reason: String

    public func save(_ context: UserContext) async throws -> Platform {
        try await context.executeGraphSave {
        try teaqlPreflightGraph(context)
        let saved = try await AuditedEntity(entity: entity, reason: reason).save(context)
        for (index, var child) in entity.schoolTypeList.enumerated() {
            child.teaqlAttachRoot(entity.teaqlEntityRoot)
            child.updatePlatform(saved.id)
            do { _ = try await child.auditAs(reason).save(context) }
            catch let error as CheckException {
                let prefix = ObjectLocation.property("school_type_list").index(index)
                throw CheckException(error.violations.map { violation in
                    CheckResult(
                        ruleID: violation.ruleID,
                        location: violation.location.prefixed(by: prefix),
                        inputValue: violation.inputValue,
                        systemValue: violation.systemValue,
                        message: violation.message)
                })
            }
        }
        for (index, var child) in entity.schoolList.enumerated() {
            child.teaqlAttachRoot(entity.teaqlEntityRoot)
            child.updatePlatform(saved.id)
            do { _ = try await child.auditAs(reason).save(context) }
            catch let error as CheckException {
                let prefix = ObjectLocation.property("school_list").index(index)
                throw CheckException(error.violations.map { violation in
                    CheckResult(
                        ruleID: violation.ruleID,
                        location: violation.location.prefixed(by: prefix),
                        inputValue: violation.inputValue,
                        systemValue: violation.systemValue,
                        message: violation.message)
                })
            }
        }
        return saved
        }
    }

    func teaqlPreflightGraph(_ context: UserContext) throws {
        if entity.id != 0 {
            if !entity.isLoaded("id") {
                throw CheckException([CheckResult(ruleID: "invalid_type", location: .property("id"), message: "Mutation requires a fully loaded entity")])
            }
            if !entity.isLoaded("name") {
                throw CheckException([CheckResult(ruleID: "invalid_type", location: .property("name"), message: "Mutation requires a fully loaded entity")])
            }
            if !entity.isLoaded("baseUrl") {
                throw CheckException([CheckResult(ruleID: "invalid_type", location: .property("base_url"), message: "Mutation requires a fully loaded entity")])
            }
            if !entity.isLoaded("createTime") {
                throw CheckException([CheckResult(ruleID: "invalid_type", location: .property("create_time"), message: "Mutation requires a fully loaded entity")])
            }
            if !entity.isLoaded("updateTime") {
                throw CheckException([CheckResult(ruleID: "invalid_type", location: .property("update_time"), message: "Mutation requires a fully loaded entity")])
            }
            if !entity.isLoaded("version") {
                throw CheckException([CheckResult(ruleID: "invalid_type", location: .property("version"), message: "Mutation requires a fully loaded entity")])
            }
        }
        try AuditedEntity(entity: entity, reason: reason).preflight(context)
        for (index, var child) in entity.schoolTypeList.enumerated() {
            child.teaqlAttachRoot(entity.teaqlEntityRoot)
            child.updatePlatform(entity.teaqlPreflightID)
            do { try child.auditAs(reason).teaqlPreflightGraph(context) }
            catch let error as CheckException {
                let prefix = ObjectLocation.property("school_type_list").index(index)
                throw CheckException(error.violations.map { violation in
                    CheckResult(
                        ruleID: violation.ruleID,
                        location: violation.location.prefixed(by: prefix),
                        inputValue: violation.inputValue,
                        systemValue: violation.systemValue,
                        message: violation.message)
                })
            }
        }
        for (index, var child) in entity.schoolList.enumerated() {
            child.teaqlAttachRoot(entity.teaqlEntityRoot)
            child.updatePlatform(entity.teaqlPreflightID)
            do { try child.auditAs(reason).teaqlPreflightGraph(context) }
            catch let error as CheckException {
                let prefix = ObjectLocation.property("school_list").index(index)
                throw CheckException(error.violations.map { violation in
                    CheckResult(
                        ruleID: violation.ruleID,
                        location: violation.location.prefixed(by: prefix),
                        inputValue: violation.inputValue,
                        systemValue: violation.systemValue,
                        message: violation.message)
                })
            }
        }
    }
}