// Generated by TeaQL. Do not edit directly.
import Foundation
import TeaQLCore

public struct School: TeaQLEntity, TeaQLMutationRootedEntity {
    public var id: Int64 = 0
    public var platform: Int64? = nil
    public var schoolType: Int64? = nil
    public var name: String? = nil
    public var address: String? = nil
    public var establishedDate: Date? = nil
    public var studentCapacity: Int64? = nil
    public var active: Bool? = nil
    public var createTime: Date? = nil
    public var updateTime: Date? = nil
    public var version: Int64 = 0
    public var platformEntity: Platform?
    public var schoolTypeEntity: SchoolType?
    private var _loadedFields: Set<String> = []
    public var teaqlEntityRoot = EntityRoot()
    private static let teaqlIDLock = NSLock()
    nonisolated(unsafe) private static var teaqlNextTemporaryID: Int64 = 0
    private var teaqlLedgerID: Int64 = 0
    public var teaqlEntityKey: EntityKey { EntityKey(entity: "School", id: .int(id == 0 ? teaqlLedgerID : id)) }
    var teaqlPreflightID: Int64 { id == 0 ? teaqlLedgerID : id }

    private enum CodingKeys: String, CodingKey {
        case id
        case platform
        case schoolType
        case name
        case address
        case establishedDate
        case studentCapacity
        case active
        case createTime
        case updateTime
        case version
    }

    public init() {
        Self.teaqlIDLock.lock(); Self.teaqlNextTemporaryID -= 1; teaqlLedgerID = Self.teaqlNextTemporaryID; Self.teaqlIDLock.unlock()
        _loadedFields = Set(["id", "platform", "schoolType", "name", "address", "establishedDate", "studentCapacity", "active", "createTime", "updateTime", "version"])
        teaqlEntityRoot.markAsNew(teaqlEntityKey)
    }

    public static let descriptor = EntityDescriptor(
        name: "School",
        table: "school_data",
        properties: [
            PropertyDescriptor(name: "id", modelName: "id", column: "id", type: .int, nullable: false, isID: true, isVersion: false),
            PropertyDescriptor(name: "platform", modelName: "platform", column: "platform", type: .int, nullable: false, isID: false, isVersion: false),
            PropertyDescriptor(name: "schoolType", modelName: "school_type", column: "school_type", type: .int, nullable: false, isID: false, isVersion: false),
            PropertyDescriptor(name: "name", modelName: "name", column: "name", type: .string, nullable: false, isID: false, isVersion: false),
            PropertyDescriptor(name: "address", modelName: "address", column: "address", type: .string, nullable: false, isID: false, isVersion: false),
            PropertyDescriptor(name: "establishedDate", modelName: "established_date", column: "established_date", type: .date, nullable: false, isID: false, isVersion: false),
            PropertyDescriptor(name: "studentCapacity", modelName: "student_capacity", column: "student_capacity", type: .int, nullable: false, isID: false, isVersion: false),
            PropertyDescriptor(name: "active", modelName: "active", column: "active", type: .bool, nullable: false, isID: false, isVersion: false),
            PropertyDescriptor(name: "createTime", modelName: "create_time", column: "create_time", type: .timestamp, nullable: false, isID: false, isVersion: false),
            PropertyDescriptor(name: "updateTime", modelName: "update_time", column: "update_time", type: .timestamp, nullable: false, isID: false, isVersion: false),
            PropertyDescriptor(name: "version", modelName: "version", column: "version", type: .int, nullable: false, isID: false, isVersion: true)
        ]
    )

    public static func from(record: TeaQLRecord) throws -> Self {
        var entity = Self()
        entity._loadedFields.removeAll()
        entity.id = record["id"]?.int64Value ?? 0
        if record.keys.contains("id") { entity._loadedFields.insert("id") }
        entity.platform = record["platform"]?.int64Value
        if record.keys.contains("platform") { entity._loadedFields.insert("platform") }
        entity.schoolType = record["schoolType"]?.int64Value
        if record.keys.contains("schoolType") { entity._loadedFields.insert("schoolType") }
        entity.name = record["name"]?.stringValue
        if record.keys.contains("name") { entity._loadedFields.insert("name") }
        entity.address = record["address"]?.stringValue
        if record.keys.contains("address") { entity._loadedFields.insert("address") }
        entity.establishedDate = record["establishedDate"]?.dateValue
        if record.keys.contains("establishedDate") { entity._loadedFields.insert("establishedDate") }
        entity.studentCapacity = record["studentCapacity"]?.int64Value
        if record.keys.contains("studentCapacity") { entity._loadedFields.insert("studentCapacity") }
        entity.active = record["active"]?.boolValue
        if record.keys.contains("active") { entity._loadedFields.insert("active") }
        entity.createTime = record["createTime"]?.dateValue
        if record.keys.contains("createTime") { entity._loadedFields.insert("createTime") }
        entity.updateTime = record["updateTime"]?.dateValue
        if record.keys.contains("updateTime") { entity._loadedFields.insert("updateTime") }
        entity.version = record["version"]?.int64Value ?? 0
        if record.keys.contains("version") { entity._loadedFields.insert("version") }
        if let relationValue = record["platformEntity"] {
            switch relationValue {
            case .object(let relatedRecord):
                entity.platformEntity = try Platform.from(record: relatedRecord)
            case .null:
                entity.platformEntity = nil
            default:
                throw TeaQLError.execution("Invalid relation payload: platform")
            }
            entity._loadedFields.insert("platformEntity")
        }
        if let relationValue = record["schoolTypeEntity"] {
            switch relationValue {
            case .object(let relatedRecord):
                entity.schoolTypeEntity = try SchoolType.from(record: relatedRecord)
            case .null:
                entity.schoolTypeEntity = nil
            default:
                throw TeaQLError.execution("Invalid relation payload: schoolType")
            }
            entity._loadedFields.insert("schoolTypeEntity")
        }
        let temporaryKey = entity.teaqlEntityKey
        entity.teaqlLedgerID = entity.id
        entity.teaqlEntityRoot.rekey(temporaryKey, to: entity.teaqlEntityKey)
        entity.teaqlEntityRoot.markAsPersisted(entity.teaqlEntityKey)
        entity.teaqlEntityRoot.setOriginalVersion(entity.teaqlEntityKey, version: entity.version)
        return entity
    }

    public static func from(record: TeaQLRecord, root: EntityRoot) throws -> Self {
        var entity = try from(record: record)
        entity.teaqlAttachRoot(root)
        return entity
    }

    public mutating func teaqlAttachRoot(_ root: EntityRoot) {
        if teaqlEntityRoot !== root { root.merge(from: teaqlEntityRoot); teaqlEntityRoot = root }
    }

    public func toRecord() -> TeaQLRecord {
        [
            "id": .int(id),
            "platform": platform.map { .int($0) } ?? .null,
            "schoolType": schoolType.map { .int($0) } ?? .null,
            "name": name.map { .string($0) } ?? .null,
            "address": address.map { .string($0) } ?? .null,
            "establishedDate": establishedDate.map { .date($0) } ?? .null,
            "studentCapacity": studentCapacity.map { .int($0) } ?? .null,
            "active": active.map { .bool($0) } ?? .null,
            "createTime": createTime.map { .timestamp(Int64($0.timeIntervalSince1970 * 1_000)) } ?? .null,
            "updateTime": updateTime.map { .timestamp(Int64($0.timeIntervalSince1970 * 1_000)) } ?? .null,
            "version": .int(version)
        ]
    }

    public func toMutationRecord() -> TeaQLRecord {
        var record: TeaQLRecord = [:]
        if _loadedFields.contains("id") {
            record["id"] = .int(id)
        }
        if _loadedFields.contains("platform") {
            record["platform"] = platform.map { .int($0) } ?? .null
        }
        if _loadedFields.contains("schoolType") {
            record["school_type"] = schoolType.map { .int($0) } ?? .null
        }
        if _loadedFields.contains("name") {
            record["name"] = name.map { .string($0) } ?? .null
        }
        if _loadedFields.contains("address") {
            record["address"] = address.map { .string($0) } ?? .null
        }
        if _loadedFields.contains("establishedDate") {
            record["established_date"] = establishedDate.map { .date($0) } ?? .null
        }
        if _loadedFields.contains("studentCapacity") {
            record["student_capacity"] = studentCapacity.map { .int($0) } ?? .null
        }
        if _loadedFields.contains("active") {
            record["active"] = active.map { .bool($0) } ?? .null
        }
        if _loadedFields.contains("createTime") {
            record["create_time"] = createTime.map { .timestamp(Int64($0.timeIntervalSince1970 * 1_000)) } ?? .null
        }
        if _loadedFields.contains("updateTime") {
            record["update_time"] = updateTime.map { .timestamp(Int64($0.timeIntervalSince1970 * 1_000)) } ?? .null
        }
        if _loadedFields.contains("version") {
            record["version"] = .int(version)
        }
        return record
    }

    public func isLoaded(_ field: String) -> Bool { _loadedFields.contains(field) }

    @discardableResult
    public mutating func markLoadedOnly(_ fields: String...) -> Self {
        _loadedFields = Set(fields)
        return self
    }

    @discardableResult
    public mutating func updateId(_ value: Int64) -> Self {
        self.id = value
        self._loadedFields.insert("id")
        self.teaqlEntityRoot.set(teaqlEntityKey, field: "id", value: .int(value))
        return self
    }


    @discardableResult
    public mutating func updatePlatform(_ value: Int64?) -> Self {
        self.platform = value
        self._loadedFields.insert("platform")
        self.teaqlEntityRoot.set(teaqlEntityKey, field: "platform", value: value.map { .int($0) } ?? .null)
        return self
    }


    @discardableResult
    public mutating func updateSchoolType(_ value: Int64?) -> Self {
        self.schoolType = value
        self._loadedFields.insert("schoolType")
        self.teaqlEntityRoot.set(teaqlEntityKey, field: "school_type", value: value.map { .int($0) } ?? .null)
        return self
    }
    @discardableResult
    public mutating func updateSchoolTypeToPrimary() -> Self {
        self.schoolType = 1001
        self._loadedFields.insert("schoolType")
        self.teaqlEntityRoot.set(teaqlEntityKey, field: "school_type", value: .int(1001))
        return self
    }


    @discardableResult
    public mutating func updateName(_ value: String?) -> Self {
        self.name = value
        self._loadedFields.insert("name")
        self.teaqlEntityRoot.set(teaqlEntityKey, field: "name", value: value.map { .string($0) } ?? .null)
        return self
    }


    @discardableResult
    public mutating func updateAddress(_ value: String?) -> Self {
        self.address = value
        self._loadedFields.insert("address")
        self.teaqlEntityRoot.set(teaqlEntityKey, field: "address", value: value.map { .string($0) } ?? .null)
        return self
    }


    @discardableResult
    public mutating func updateEstablishedDate(_ value: Date?) -> Self {
        self.establishedDate = value
        self._loadedFields.insert("establishedDate")
        self.teaqlEntityRoot.set(teaqlEntityKey, field: "established_date", value: value.map { .date($0) } ?? .null)
        return self
    }


    @discardableResult
    public mutating func updateStudentCapacity(_ value: Int64?) -> Self {
        self.studentCapacity = value
        self._loadedFields.insert("studentCapacity")
        self.teaqlEntityRoot.set(teaqlEntityKey, field: "student_capacity", value: value.map { .int($0) } ?? .null)
        return self
    }


    @discardableResult
    public mutating func updateActive(_ value: Bool?) -> Self {
        self.active = value
        self._loadedFields.insert("active")
        self.teaqlEntityRoot.set(teaqlEntityKey, field: "active", value: value.map { .bool($0) } ?? .null)
        return self
    }


    @discardableResult
    public mutating func updateCreateTime(_ value: Date?) -> Self {
        self.createTime = value
        self._loadedFields.insert("createTime")
        self.teaqlEntityRoot.set(teaqlEntityKey, field: "create_time", value: value.map { .timestamp(Int64($0.timeIntervalSince1970 * 1_000)) } ?? .null)
        return self
    }


    @discardableResult
    public mutating func updateUpdateTime(_ value: Date?) -> Self {
        self.updateTime = value
        self._loadedFields.insert("updateTime")
        self.teaqlEntityRoot.set(teaqlEntityKey, field: "update_time", value: value.map { .timestamp(Int64($0.timeIntervalSince1970 * 1_000)) } ?? .null)
        return self
    }


    @discardableResult
    public mutating func updateVersion(_ value: Int64) -> Self {
        self.version = value
        self._loadedFields.insert("version")
        self.teaqlEntityRoot.set(teaqlEntityKey, field: "version", value: .int(value))
        return self
    }


    public func auditAs(_ reason: String) -> SchoolAudited {
        SchoolAudited(entity: self, reason: reason)
    }

    @discardableResult
    public mutating func markForDeletion() -> Self {
        teaqlEntityRoot.markAsDeleted(teaqlEntityKey)
        return self
    }
}

public struct SchoolAudited: Sendable {
    public let entity: School
    public let reason: String

    public func save(_ context: UserContext) async throws -> School {
        try await context.executeGraphSave {
        try teaqlPreflightGraph(context)
        let saved = try await AuditedEntity(entity: entity, reason: reason).save(context)
        return saved
        }
    }

    func teaqlPreflightGraph(_ context: UserContext) throws {
        if entity.id != 0 {
            if !entity.isLoaded("id") {
                throw CheckException([CheckResult(ruleID: "invalid_type", location: .property("id"), message: "Mutation requires a fully loaded entity")])
            }
            if !entity.isLoaded("platform") {
                throw CheckException([CheckResult(ruleID: "invalid_type", location: .property("platform"), message: "Mutation requires a fully loaded entity")])
            }
            if !entity.isLoaded("schoolType") {
                throw CheckException([CheckResult(ruleID: "invalid_type", location: .property("school_type"), message: "Mutation requires a fully loaded entity")])
            }
            if !entity.isLoaded("name") {
                throw CheckException([CheckResult(ruleID: "invalid_type", location: .property("name"), message: "Mutation requires a fully loaded entity")])
            }
            if !entity.isLoaded("address") {
                throw CheckException([CheckResult(ruleID: "invalid_type", location: .property("address"), message: "Mutation requires a fully loaded entity")])
            }
            if !entity.isLoaded("establishedDate") {
                throw CheckException([CheckResult(ruleID: "invalid_type", location: .property("established_date"), message: "Mutation requires a fully loaded entity")])
            }
            if !entity.isLoaded("studentCapacity") {
                throw CheckException([CheckResult(ruleID: "invalid_type", location: .property("student_capacity"), message: "Mutation requires a fully loaded entity")])
            }
            if !entity.isLoaded("active") {
                throw CheckException([CheckResult(ruleID: "invalid_type", location: .property("active"), message: "Mutation requires a fully loaded entity")])
            }
            if !entity.isLoaded("createTime") {
                throw CheckException([CheckResult(ruleID: "invalid_type", location: .property("create_time"), message: "Mutation requires a fully loaded entity")])
            }
            if !entity.isLoaded("updateTime") {
                throw CheckException([CheckResult(ruleID: "invalid_type", location: .property("update_time"), message: "Mutation requires a fully loaded entity")])
            }
            if !entity.isLoaded("version") {
                throw CheckException([CheckResult(ruleID: "invalid_type", location: .property("version"), message: "Mutation requires a fully loaded entity")])
            }
        }
        try AuditedEntity(entity: entity, reason: reason).preflight(context)
    }
}