// Generated by TeaQL. Do not edit directly.
import Foundation
import TeaQLCore

public struct SchoolType: TeaQLEntity, TeaQLMutationRootedEntity {
    public var platform: Int64 = 0
    public var id: Int64 = 0
    public var name: String? = nil
    public var code: String? = nil
    public var displayOrder: Decimal = 0
    public var version: Int64 = 0
    public var platformEntity: Platform?
    public var schoolList: [School] = []
    private var _loadedFields: Set<String> = []
    public var teaqlEntityRoot = EntityRoot()
    private static let teaqlIDLock = NSLock()
    nonisolated(unsafe) private static var teaqlNextTemporaryID: Int64 = 0
    private var teaqlLedgerID: Int64 = 0
    public var teaqlEntityKey: EntityKey { EntityKey(entity: "SchoolType", id: .int(id == 0 ? teaqlLedgerID : id)) }

    private enum CodingKeys: String, CodingKey {
        case platform
        case id
        case name
        case code
        case displayOrder
        case version
    }

    public init() {
        Self.teaqlIDLock.lock(); Self.teaqlNextTemporaryID -= 1; teaqlLedgerID = Self.teaqlNextTemporaryID; Self.teaqlIDLock.unlock()
        _loadedFields = Set(["platform", "id", "name", "code", "displayOrder", "version"])
        teaqlEntityRoot.markAsNew(teaqlEntityKey)
    }

    public static let descriptor = EntityDescriptor(
        name: "SchoolType",
        table: "school_type_data",
        properties: [
            PropertyDescriptor(name: "platform", modelName: "platform", column: "platform", type: .int, nullable: true, isID: false, isVersion: false),
            PropertyDescriptor(name: "id", modelName: "id", column: "id", type: .int, nullable: true, isID: true, isVersion: false),
            PropertyDescriptor(name: "name", modelName: "name", column: "name", type: .string, nullable: true, isID: false, isVersion: false),
            PropertyDescriptor(name: "code", modelName: "code", column: "code", type: .string, nullable: true, isID: false, isVersion: false),
            PropertyDescriptor(name: "displayOrder", modelName: "display_order", column: "display_order", type: .decimal, nullable: true, isID: false, isVersion: false),
            PropertyDescriptor(name: "version", modelName: "version", column: "version", type: .int, nullable: true, isID: false, isVersion: true)
        ]
    )

    public static func from(record: TeaQLRecord) throws -> Self {
        var entity = Self()
        entity._loadedFields.removeAll()
        entity.platform = record["platform"]?.int64Value ?? 0
        if record.keys.contains("platform") { entity._loadedFields.insert("platform") }
        entity.id = record["id"]?.int64Value ?? 0
        if record.keys.contains("id") { entity._loadedFields.insert("id") }
        entity.name = record["name"]?.stringValue ?? nil
        if record.keys.contains("name") { entity._loadedFields.insert("name") }
        entity.code = record["code"]?.stringValue ?? nil
        if record.keys.contains("code") { entity._loadedFields.insert("code") }
        entity.displayOrder = record["displayOrder"]?.decimalValue ?? 0
        if record.keys.contains("displayOrder") { entity._loadedFields.insert("displayOrder") }
        entity.version = record["version"]?.int64Value ?? 0
        if record.keys.contains("version") { entity._loadedFields.insert("version") }
        if let relationValue = record["platformEntity"] {
            switch relationValue {
            case .object(let relatedRecord):
                entity.platformEntity = try Platform.from(record: relatedRecord)
            case .null:
                entity.platformEntity = nil
            default:
                throw TeaQLError.execution("Invalid relation payload: platform")
            }
            entity._loadedFields.insert("platformEntity")
        }
        if let relationValue = record["schoolList"] {
            switch relationValue {
            case .array(let values):
                entity.schoolList = try values.compactMap {
                    guard case .object(let childRecord) = $0 else { return nil }
                    return try School.from(record: childRecord)
                }
            case .object(let childRecord):
                entity.schoolList = [try School.from(record: childRecord)]
            case .null:
                entity.schoolList = []
            default:
                throw TeaQLError.execution("Invalid relation payload: schoolList")
            }
            entity._loadedFields.insert("schoolList")
        }
        let temporaryKey = entity.teaqlEntityKey
        entity.teaqlLedgerID = entity.id
        entity.teaqlEntityRoot.rekey(temporaryKey, to: entity.teaqlEntityKey)
        entity.teaqlEntityRoot.markAsPersisted(entity.teaqlEntityKey)
        entity.teaqlEntityRoot.setOriginalVersion(entity.teaqlEntityKey, version: entity.version)
        return entity
    }

    public static func from(record: TeaQLRecord, root: EntityRoot) throws -> Self {
        var entity = try from(record: record)
        entity.teaqlAttachRoot(root)
        return entity
    }

    public mutating func teaqlAttachRoot(_ root: EntityRoot) {
        if teaqlEntityRoot !== root { root.merge(from: teaqlEntityRoot); teaqlEntityRoot = root }
        for index in schoolList.indices { schoolList[index].teaqlAttachRoot(root) }
    }

    public func toRecord() -> TeaQLRecord {
        [
            "platform": .int(platform),
            "id": .int(id),
            "name": name.map(TeaQLValue.string) ?? .null,
            "code": code.map(TeaQLValue.string) ?? .null,
            "displayOrder": .decimal(displayOrder),
            "version": .int(version)
        ]
    }

    public func toMutationRecord() -> TeaQLRecord {
        var record: TeaQLRecord = [:]
        if _loadedFields.contains("platform") {
            record["platform"] = .int(platform)
        }
        if _loadedFields.contains("id") {
            record["id"] = .int(id)
        }
        if _loadedFields.contains("name") {
            record["name"] = name.map(TeaQLValue.string) ?? .null
        }
        if _loadedFields.contains("code") {
            record["code"] = code.map(TeaQLValue.string) ?? .null
        }
        if _loadedFields.contains("displayOrder") {
            record["display_order"] = .decimal(displayOrder)
        }
        if _loadedFields.contains("version") {
            record["version"] = .int(version)
        }
        return record
    }

    public func isLoaded(_ field: String) -> Bool { _loadedFields.contains(field) }

    @discardableResult
    public mutating func markLoadedOnly(_ fields: String...) -> Self {
        _loadedFields = Set(fields)
        return self
    }

    @discardableResult
    public mutating func updatePlatform(_ value: Int64) -> Self {
        self.platform = value
        self._loadedFields.insert("platform")
        self.teaqlEntityRoot.set(teaqlEntityKey, field: "platform", value: .int(value))
        return self
    }


    @discardableResult
    public mutating func updateId(_ value: Int64) -> Self {
        self.id = value
        self._loadedFields.insert("id")
        self.teaqlEntityRoot.set(teaqlEntityKey, field: "id", value: .int(value))
        return self
    }


    @discardableResult
    public mutating func updateName(_ value: String?) -> Self {
        self.name = value
        self._loadedFields.insert("name")
        self.teaqlEntityRoot.set(teaqlEntityKey, field: "name", value: value.map(TeaQLValue.string) ?? .null)
        return self
    }


    @discardableResult
    public mutating func updateCode(_ value: String?) -> Self {
        self.code = value
        self._loadedFields.insert("code")
        self.teaqlEntityRoot.set(teaqlEntityKey, field: "code", value: value.map(TeaQLValue.string) ?? .null)
        return self
    }


    @discardableResult
    public mutating func updateDisplayOrder(_ value: Decimal) -> Self {
        self.displayOrder = value
        self._loadedFields.insert("displayOrder")
        self.teaqlEntityRoot.set(teaqlEntityKey, field: "display_order", value: .decimal(value))
        return self
    }


    @discardableResult
    public mutating func updateVersion(_ value: Int64) -> Self {
        self.version = value
        self._loadedFields.insert("version")
        self.teaqlEntityRoot.set(teaqlEntityKey, field: "version", value: .int(value))
        return self
    }


    public func auditAs(_ reason: String) -> SchoolTypeAudited {
        SchoolTypeAudited(entity: self, reason: reason)
    }
}

public struct SchoolTypeAudited: Sendable {
    public let entity: SchoolType
    public let reason: String

    public func save(_ context: UserContext) async throws -> SchoolType {
        let saved = try await AuditedEntity(entity: entity, reason: reason).save(context)
        for var child in entity.schoolList {
            child.teaqlAttachRoot(context.entityRoot)
            child.updateSchoolType(saved.id)
            _ = try await child.auditAs(reason).save(context)
        }
        return saved
    }

    public func delete(_ context: UserContext) async throws -> SchoolType {
        try await AuditedEntity(entity: entity, reason: reason).delete(context)
    }
}