// Generated by TeaQL. Do not edit directly.
import TeaQLCore

public enum Q {
    public static func platforms() -> PlatformRequest<RequestDraft> {
        var query = SelectQuery(entity: Platform.descriptor)
        query.filter = .greaterThanOrEqual("version", .int(1))
        return PlatformRequest(query: query)
    }

    public static func platformsWithMinimalFields() -> PlatformRequest<RequestDraft> {
        var query = SelectQuery(entity: Platform.descriptor)
        query.filter = .greaterThanOrEqual("version", .int(1))
        query.projection = ["id", "version"]
        return PlatformRequest(query: query)
    }
    public static func workItems() -> WorkItemRequest<RequestDraft> {
        var query = SelectQuery(entity: WorkItem.descriptor)
        query.filter = .greaterThanOrEqual("version", .int(1))
        return WorkItemRequest(query: query)
    }

    public static func workItemsWithMinimalFields() -> WorkItemRequest<RequestDraft> {
        var query = SelectQuery(entity: WorkItem.descriptor)
        query.filter = .greaterThanOrEqual("version", .int(1))
        query.projection = ["id", "version"]
        return WorkItemRequest(query: query)
    }
}