// Generated by TeaQL. Do not edit directly.
import Foundation
import TeaQLCore

private struct PlatformChecker: EntityChecker {
    func checkAndFix(
        context: UserContext, mutation: inout Mutation, now: Date
    ) throws -> [CheckResult] {
        var results: [CheckResult] = []
        if (mutation.kind == .create && mutation.values["name"] == nil) || mutation.values["name"] == .null { results.append(CheckResult(ruleID: "required", location: .property("name"))) }
        if let value = mutation.values["name"]?.stringValue, value.count > 100 { results.append(CheckResult(ruleID: "max_length", location: .property("name"), inputValue: value, systemValue: "100")) }


        return results
    }
}

private struct WorkItemChecker: EntityChecker {
    func checkAndFix(
        context: UserContext, mutation: inout Mutation, now: Date
    ) throws -> [CheckResult] {
        var results: [CheckResult] = []
        if (mutation.kind == .create && mutation.values["title"] == nil) || mutation.values["title"] == .null { results.append(CheckResult(ruleID: "required", location: .property("title"))) }
        if let value = mutation.values["title"]?.stringValue, !(value.count >= 1) { results.append(CheckResult(ruleID: "min_length", location: .property("title"), inputValue: value, systemValue: "1")) }
        if let value = mutation.values["title"]?.stringValue, value.count > 80 { results.append(CheckResult(ruleID: "max_length", location: .property("title"), inputValue: value, systemValue: "80")) }

        if let value = mutation.values["description"]?.stringValue, value.count > 100 { results.append(CheckResult(ruleID: "max_length", location: .property("description"), inputValue: value, systemValue: "100")) }

        if (mutation.kind == .create && mutation.values["platform"] == nil) || mutation.values["platform"] == .null { results.append(CheckResult(ruleID: "required", location: .property("platform"))) }


        return results
    }
}

/// Passive generated metadata. Installing it never creates or changes schema.
public enum GeneratedRuntimeModule {
    public static let module = RuntimeModule(
        name: "runtime-example-conformance-service",
        entities: [
           Platform.descriptor,
           WorkItem.descriptor
        ],
        checkers: [
           "Platform": PlatformChecker(),
           "WorkItem": WorkItemChecker()
        ],
        generatedBootstrap: ensureGeneratedBootstrap,

        wireMetadata: [
            "Platform": try! WireEntityMetadata(entityType: "Platform", canonicalFields: ["id", "name", "version"], aliases: ["id": ["id"], "name": ["name"], "version": ["version"]]),
            "WorkItem": try! WireEntityMetadata(entityType: "WorkItem", canonicalFields: ["id", "title", "description", "platform", "version"], aliases: ["id": ["id"], "title": ["title"], "description": ["description"], "platform": ["platform"], "version": ["version"]])
        ]
    )

    private static func ensureGeneratedBootstrap(_ callerContext: UserContext) async throws {
        var lastError: Error?
        for attempt in 0..<5 {
            do { try await ensureGeneratedBootstrapOnce(callerContext); return }
            catch { lastError = error; if attempt < 4 { try await Task.sleep(nanoseconds: UInt64(attempt + 1) * 10_000_000) } }
        }
        throw lastError!
    }

    private static func ensureGeneratedBootstrapOnce(_ callerContext: UserContext) async throws {
        let bootstrapContext = callerContext._generatedBootstrapContext()
        var domainRoot = try await Q.platforms().withIdIs(1).comment("what: locate generated Domain Root").purpose("why: idempotent runtime bootstrap").executeForList(bootstrapContext).first
        if domainRoot == nil {
            var created = try Q.platforms().comment("what: create generated Domain Root").purpose("why: initialize runtime bootstrap").newEntity(bootstrapContext)
            try created.teaqlInitializeGeneratedBootstrapId(1)
            created.updateName("Runtime Example")
            do { domainRoot = try await created.auditAs("create generated Domain Root Platform").save(bootstrapContext) }
            catch { domainRoot = try await Q.platforms().withIdIs(1).comment("what: recover concurrent Domain Root bootstrap").purpose("why: make bootstrap idempotent").executeForList(bootstrapContext).first; if domainRoot == nil { throw error } }
        }
        guard let domainRoot else { throw TeaQLError.execution("Generated Domain Root bootstrap failed") }
        let rootedContext = callerContext._generatedBootstrapContext(activeRoot: ContextEntityRef(entity: "Platform", id: .int(domainRoot.id)))
    }

    private static func generatedBootstrapDate(_ value: String) throws -> Date {
        if let date = ISO8601DateFormatter().date(from: value) { return date }
        let formatter = DateFormatter(); formatter.locale = Locale(identifier: "en_US_POSIX"); formatter.timeZone = TimeZone(secondsFromGMT: 0); formatter.dateFormat = "yyyy-MM-dd"
        guard let date = formatter.date(from: value) else { throw TeaQLError.execution("Invalid generated bootstrap date: \(value)") }; return date
    }

}