// Generated by TeaQL. Do not edit directly.
import Foundation
import TeaQLCore

private struct PlatformChecker: EntityChecker {
    func checkAndFix(
        context: UserContext, mutation: inout Mutation, now: Date
    ) throws -> [CheckResult] {
        var results: [CheckResult] = []
        if (mutation.kind == .create && mutation.values["name"] == nil) || mutation.values["name"] == .null { results.append(CheckResult(ruleID: "required", location: .property("name"))) }
        if let value = mutation.values["name"]?.stringValue, value.count > 100 { results.append(CheckResult(ruleID: "max_length", location: .property("name"), inputValue: value, systemValue: "100")) }


        return results
    }
}

private struct WorkItemChecker: EntityChecker {
    func checkAndFix(
        context: UserContext, mutation: inout Mutation, now: Date
    ) throws -> [CheckResult] {
        var results: [CheckResult] = []
        if (mutation.kind == .create && mutation.values["title"] == nil) || mutation.values["title"] == .null { results.append(CheckResult(ruleID: "required", location: .property("title"))) }
        if let value = mutation.values["title"]?.stringValue, !(value.count >= 1) { results.append(CheckResult(ruleID: "min_length", location: .property("title"), inputValue: value, systemValue: "1")) }
        if let value = mutation.values["title"]?.stringValue, value.count > 80 { results.append(CheckResult(ruleID: "max_length", location: .property("title"), inputValue: value, systemValue: "80")) }

        if let value = mutation.values["description"]?.stringValue, value.count > 100 { results.append(CheckResult(ruleID: "max_length", location: .property("description"), inputValue: value, systemValue: "100")) }

        if (mutation.kind == .create && mutation.values["platform"] == nil) || mutation.values["platform"] == .null { results.append(CheckResult(ruleID: "required", location: .property("platform"))) }


        return results
    }
}

/// Passive generated metadata. Installing it never creates or changes schema.
public enum GeneratedRuntimeModule {
    public static let module = RuntimeModule(
        name: "runtime-example-conformance-service",
        entities: [
           Platform.descriptor,
           WorkItem.descriptor
        ],
        checkers: [
           "Platform": PlatformChecker(),
           "WorkItem": WorkItemChecker()
        ],
        rootEntities: [.init(entity: "Platform", id: 1, values: ["name": .string("Runtime Example")])],
        constantEntities: [
            
        ]
    )
}