// Generated by TeaQL. Do not edit directly.
import Foundation
import TeaQLCore

public struct PlatformRequest<State: Sendable>: Sendable {
    private var query: SelectQuery

    init(query: SelectQuery) { self.query = query }

    @discardableResult
    public func comment(_ value: String) -> Self {
        var copy = self; copy.query.comment = value; return copy
    }

    public func purpose(_ value: String) -> PlatformRequest<RequestExecutable> {
        var copy = query; copy.purpose = value
        return PlatformRequest<RequestExecutable>(query: copy)
    }

    @discardableResult
    public func limit(_ value: Int) -> Self {
        var copy = self; copy.query.limit = value; return copy
    }

    @discardableResult
    public func topNProbeParentThreshold(_ value: Int) -> Self {
        var copy = self; copy.query.topNProbeParentThreshold(value); return copy
    }

    @discardableResult
    public func hardLimit(_ value: Int) -> Self {
        var copy = self; copy.query.hardLimit = value; return copy
    }

    @discardableResult
    public func offset(_ value: Int) -> Self {
        var copy = self; copy.query.offset = value; return copy
    }

    @discardableResult
    public func optimizeForContinuousPageFetch() -> Self {
        optimizeForContinuousPageFetch(namespace: "default", ttlSeconds: 600)
    }

    @discardableResult
    public func optimizeForContinuousPageFetch(namespace: String, ttlSeconds: Int) -> Self {
        var copy = self
        copy.query.continuousPage = ContinuousPageFetchOptions(
            namespace: namespace, ttlSeconds: ttlSeconds)
        return copy
    }

    @discardableResult
    public func optimizePaginationWithIdSet() -> Self {
        optimizePaginationWithIdSet(namespace: "default", ttlSeconds: 600, maxIds: 3_000_000)
    }

    @discardableResult
    public func optimizePaginationWithIdSet(
        namespace: String, ttlSeconds: Int, maxIds: Int
    ) -> Self {
        var copy = self
        copy.query.idSetPagination = IdSetPaginationOptions(
            namespace: namespace, ttlSeconds: ttlSeconds, maxIds: maxIds)
        return copy
    }

    public func toQuery() -> SelectQuery { query }

    /// Includes both active and soft-deleted rows. Callers must still provide
    /// Comment and Purpose before execution.
    @discardableResult
    public func withDeletedRows() -> Self {
        var copy = self
        copy.query.filter = removingActiveVersionFilter(copy.query.filter)
        return copy
    }

    /// Returns only soft-deleted rows, represented by a negative version.
    @discardableResult
    public func deletedRowsOnly() -> Self {
        withDeletedRows().adding(.lessThanOrEqual("version", .int(-1)))
    }

    @discardableResult
    public func selectSelfFields() -> Self {
        var copy = self
        copy.query.projection = ["id", "name", "version"]
        return copy
    }

    @discardableResult
    public func selectId() -> Self {
        var copy = self
        if !copy.query.projection.contains("id") {
            copy.query.projection.append("id")
        }
        return copy
    }


    @discardableResult
    public func selectName() -> Self {
        var copy = self
        if !copy.query.projection.contains("name") {
            copy.query.projection.append("name")
        }
        return copy
    }


    @discardableResult
    public func selectVersion() -> Self {
        var copy = self
        if !copy.query.projection.contains("version") {
            copy.query.projection.append("version")
        }
        return copy
    }



    @discardableResult
    public func orderByIdAscending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("id", .ascending)); return copy
    }

    @discardableResult
    public func orderByIdDescending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("id", .descending)); return copy
    }

    @discardableResult
    public func orderByNameAscending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("name", .ascending)); return copy
    }

    @discardableResult
    public func orderByNameDescending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("name", .descending)); return copy
    }

    @discardableResult
    public func orderByVersionAscending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("version", .ascending)); return copy
    }

    @discardableResult
    public func orderByVersionDescending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("version", .descending)); return copy
    }

    @discardableResult
    public func selectWorkItemList() -> Self {
        selectWorkItemListWith(WorkItemRequest<RequestDraft>(
            query: SelectQuery(entity: WorkItem.descriptor)))
    }

    @discardableResult
    public func selectWorkItemListWith<ChildState: Sendable>(
        _ child: WorkItemRequest<ChildState>
    ) -> Self {
        var copy = self
        copy.query.relationQuery(
            "workItemList",
            localKey: "id",
            foreignKey: "platform",
            many: true,
            query: child.toQuery())
        return copy
    }

    @discardableResult
    public func countWorkItems() -> Self {
        countWorkItemsAs("countWorkItems")
    }

    @discardableResult
    public func countWorkItemsAs(_ alias: String) -> Self {
        countWorkItemsWith(alias, Q.workItems())
    }

    @discardableResult
    public func countWorkItemsWith<ChildState: Sendable>(
        _ alias: String, _ child: WorkItemRequest<ChildState>
    ) -> Self {
        var copy = self
        var childQuery = child.toQuery()
        childQuery.aggregates.append(QueryAggregate(.count, field: "id", alias: alias))
        copy.query.relationAggregate(
            "workItemList", foreignKey: "platform", alias: alias,
            query: childQuery, singleResult: true)
        return copy
    }



    @discardableResult
    public func withIdIs(_ value: Int64) -> Self {
        adding(.equal("id", .int(value)))
    }

    @discardableResult
    public func withIdIn(_ values: [Int64]) -> Self {
        adding(.inList("id", values.map { .int($0) }))
    }

    @discardableResult
    public func withIdIsNot(_ value: Int64) -> Self {
        adding(.notEqual("id", .int(value)))
    }

    @discardableResult
    public func withIdNotIn(_ values: [Int64]) -> Self {
        adding(.notInList("id", values.map { .int($0) }))
    }

    @discardableResult
    public func withIdGreaterThan(_ value: Int64) -> Self {
        adding(.greaterThan("id", .int(value)))
    }

    @discardableResult
    public func withIdGreaterThanOrEqualTo(_ value: Int64) -> Self {
        adding(.greaterThanOrEqual("id", .int(value)))
    }

    @discardableResult
    public func withIdLessThan(_ value: Int64) -> Self {
        adding(.lessThan("id", .int(value)))
    }

    @discardableResult
    public func withIdLessThanOrEqualTo(_ value: Int64) -> Self {
        adding(.lessThanOrEqual("id", .int(value)))
    }

    @discardableResult
    public func withIdBetween(_ lower: Int64, _ upper: Int64) -> Self {
        adding(.between("id", .int(lower), .int(upper)))
    }

    @discardableResult
    public func withIdIsKnown() -> Self {
        adding(.isNotNull("id"))
    }

    @discardableResult
    public func withIdIsUnknown() -> Self {
        adding(.isNull("id"))
    }


    @discardableResult
    public func withNameIs(_ value: String) -> Self {
        adding(.equal("name", .string(value)))
    }

    @discardableResult
    public func withNameIn(_ values: [String]) -> Self {
        adding(.inList("name", values.map { .string($0) }))
    }

    @discardableResult
    public func withNameIsNot(_ value: String) -> Self {
        adding(.notEqual("name", .string(value)))
    }

    @discardableResult
    public func withNameNotIn(_ values: [String]) -> Self {
        adding(.notInList("name", values.map { .string($0) }))
    }

    @discardableResult
    public func withNameGreaterThan(_ value: String) -> Self {
        adding(.greaterThan("name", .string(value)))
    }

    @discardableResult
    public func withNameGreaterThanOrEqualTo(_ value: String) -> Self {
        adding(.greaterThanOrEqual("name", .string(value)))
    }

    @discardableResult
    public func withNameLessThan(_ value: String) -> Self {
        adding(.lessThan("name", .string(value)))
    }

    @discardableResult
    public func withNameLessThanOrEqualTo(_ value: String) -> Self {
        adding(.lessThanOrEqual("name", .string(value)))
    }

    @discardableResult
    public func withNameBetween(_ lower: String, _ upper: String) -> Self {
        adding(.between("name", .string(lower), .string(upper)))
    }

    @discardableResult
    public func withNameIsKnown() -> Self {
        adding(.isNotNull("name"))
    }

    @discardableResult
    public func withNameIsUnknown() -> Self {
        adding(.isNull("name"))
    }
    @discardableResult
    public func withNameContaining(_ value: String) -> Self {
        adding(.contains("name", value))
    }

    @discardableResult
    public func withNameNotContaining(_ value: String) -> Self {
        adding(.notContains("name", value))
    }

    @discardableResult
    public func withNameStartingWith(_ value: String) -> Self {
        adding(.startsWith("name", value))
    }

    @discardableResult
    public func withNameNotStartingWith(_ value: String) -> Self {
        adding(.notStartsWith("name", value))
    }

    @discardableResult
    public func withNameEndingWith(_ value: String) -> Self {
        adding(.endsWith("name", value))
    }

    @discardableResult
    public func withNameNotEndingWith(_ value: String) -> Self {
        adding(.notEndsWith("name", value))
    }

    @discardableResult
    public func withNameSoundingLike(_ value: String) -> Self {
        adding(.soundingLike("name", value))
    }


    @discardableResult
    public func withVersionIs(_ value: Int64) -> Self {
        adding(.equal("version", .int(value)))
    }

    @discardableResult
    public func withVersionIn(_ values: [Int64]) -> Self {
        adding(.inList("version", values.map { .int($0) }))
    }

    @discardableResult
    public func withVersionIsNot(_ value: Int64) -> Self {
        adding(.notEqual("version", .int(value)))
    }

    @discardableResult
    public func withVersionNotIn(_ values: [Int64]) -> Self {
        adding(.notInList("version", values.map { .int($0) }))
    }

    @discardableResult
    public func withVersionGreaterThan(_ value: Int64) -> Self {
        adding(.greaterThan("version", .int(value)))
    }

    @discardableResult
    public func withVersionGreaterThanOrEqualTo(_ value: Int64) -> Self {
        adding(.greaterThanOrEqual("version", .int(value)))
    }

    @discardableResult
    public func withVersionLessThan(_ value: Int64) -> Self {
        adding(.lessThan("version", .int(value)))
    }

    @discardableResult
    public func withVersionLessThanOrEqualTo(_ value: Int64) -> Self {
        adding(.lessThanOrEqual("version", .int(value)))
    }

    @discardableResult
    public func withVersionBetween(_ lower: Int64, _ upper: Int64) -> Self {
        adding(.between("version", .int(lower), .int(upper)))
    }

    @discardableResult
    public func withVersionIsKnown() -> Self {
        adding(.isNotNull("version"))
    }

    @discardableResult
    public func withVersionIsUnknown() -> Self {
        adding(.isNull("version"))
    }



    @discardableResult
    public func haveWorkItems() -> Self {
        withWorkItemListMatching(WorkItemRequest<RequestDraft>(
            query: SelectQuery(entity: WorkItem.descriptor)))
    }

    @discardableResult
    public func haveNoWorkItems() -> Self {
        withoutWorkItemListMatching(WorkItemRequest<RequestDraft>(
            query: SelectQuery(entity: WorkItem.descriptor)))
    }

    @discardableResult
    public func withWorkItemListMatching<ChildState: Sendable>(
        _ child: WorkItemRequest<ChildState>
    ) -> Self {
        adding(.inSubquery("id", RelationQueryPlan(child.toQuery()), "platform"))
    }

    @discardableResult
    public func withoutWorkItemListMatching<ChildState: Sendable>(
        _ child: WorkItemRequest<ChildState>
    ) -> Self {
        adding(.notInSubquery("id", RelationQueryPlan(child.toQuery()), "platform"))
    }


    @discardableResult
    public func count() -> Self { countAs("count") }

    @discardableResult
    public func countAs(_ alias: String) -> Self {
        var copy = self
        copy.query.aggregates.append(QueryAggregate(.count, field: "*", alias: alias))
        return copy
    }


    @discardableResult
    public func groupById() -> Self {
        var copy = self
        copy.query.groupBy.append("id")
        return copy
    }

    @discardableResult
    public func groupByName() -> Self {
        var copy = self
        copy.query.groupBy.append("name")
        return copy
    }

    @discardableResult
    public func groupByVersion() -> Self {
        var copy = self
        copy.query.groupBy.append("version")
        return copy
    }

    private func adding(_ expression: TeaQLExpression) -> Self {
        var copy = self
        copy.query.filter = copy.query.filter.map { .and([$0, expression]) } ?? expression
        return copy
    }

    private func removingActiveVersionFilter(
        _ expression: TeaQLExpression?
    ) -> TeaQLExpression? {
        guard let expression else { return nil }
        let active = TeaQLExpression.greaterThanOrEqual("version", .int(1))
        if expression == active { return nil }
        guard case .and(let items) = expression else { return expression }
        let retained = items.compactMap { removingActiveVersionFilter($0) }
        if retained.isEmpty { return nil }
        if retained.count == 1 { return retained[0] }
        return .and(retained)
    }
}

public extension PlatformRequest where State == RequestExecutable {
    private func ensureIntent() throws {
        guard let comment = query.comment,
              !comment.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            throw TeaQLError.execution("Comment is required before execution")
        }
        guard let purpose = query.purpose,
              !purpose.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            throw TeaQLError.execution("Purpose is required before execution")
        }
    }

    func newEntity(_ context: UserContext) throws -> Platform {
        try ensureIntent()
        return context.initializeEntity("Platform", Platform())
    }

    func executeForList(_ context: UserContext) async throws -> SmartList<Platform> {
        try ensureIntent()
        let result = try await context.execute(query)
        let queryRoot = EntityRoot()
        return SmartList(
            try result.records.map { try Platform.from(record: $0, root: queryRoot) },
            facets: result.facets)
    }

    func executeForRows(_ context: UserContext) async throws -> SmartList<TeaQLRecord> {
        try ensureIntent()
        let result = try await context.execute(query)
        return SmartList(result.records, facets: result.facets)
    }

    func executeForPage(
        _ context: UserContext, offset: Int, limit: Int
    ) async throws -> TeaQLPage<Platform> {
        try ensureIntent()
        var pageQuery = query
        pageQuery.offset = offset
        pageQuery.limit = limit
        let result = try await context.execute(pageQuery)
        let observation = await context.idSetPaginationObservation()
        let total: Int
        if pageQuery.idSetPagination != nil && observation.countAccuracy == "EXACT" {
            total = observation.count
        } else {
            total = try await context.count(pageQuery)
        }
        let queryRoot = EntityRoot()
        let items = SmartList(
            try result.records.map { try Platform.from(record: $0, root: queryRoot) },
            totalCount: total)
        return TeaQLPage(items: items, total: total, offset: offset, limit: limit)
    }
}