// Generated by TeaQL. Do not edit directly.
import Foundation
import TeaQLCore

public struct WorkItemRequest<State: Sendable>: Sendable {
    private var query: SelectQuery

    init(query: SelectQuery) { self.query = query }

    @discardableResult
    public func comment(_ value: String) -> Self {
        var copy = self; copy.query.comment = value; return copy
    }

    public func purpose(_ value: String) -> WorkItemRequest<RequestExecutable> {
        var copy = query; copy.purpose = value
        return WorkItemRequest<RequestExecutable>(query: copy)
    }

    @discardableResult
    public func limit(_ value: Int) -> Self {
        var copy = self; copy.query.limit = value; return copy
    }

    @discardableResult
    public func topNProbeParentThreshold(_ value: Int) -> Self {
        var copy = self; copy.query.topNProbeParentThreshold(value); return copy
    }

    @discardableResult
    public func hardLimit(_ value: Int) -> Self {
        var copy = self; copy.query.hardLimit = value; return copy
    }

    @discardableResult
    public func offset(_ value: Int) -> Self {
        var copy = self; copy.query.offset = value; return copy
    }

    @discardableResult
    public func optimizeForContinuousPageFetch() -> Self {
        optimizeForContinuousPageFetch(namespace: "default", ttlSeconds: 600)
    }

    @discardableResult
    public func optimizeForContinuousPageFetch(namespace: String, ttlSeconds: Int) -> Self {
        var copy = self
        copy.query.continuousPage = ContinuousPageFetchOptions(
            namespace: namespace, ttlSeconds: ttlSeconds)
        return copy
    }

    @discardableResult
    public func optimizePaginationWithIdSet() -> Self {
        optimizePaginationWithIdSet(namespace: "default", ttlSeconds: 600, maxIds: 3_000_000)
    }

    @discardableResult
    public func optimizePaginationWithIdSet(
        namespace: String, ttlSeconds: Int, maxIds: Int
    ) -> Self {
        var copy = self
        copy.query.idSetPagination = IdSetPaginationOptions(
            namespace: namespace, ttlSeconds: ttlSeconds, maxIds: maxIds)
        return copy
    }

    public func toQuery() -> SelectQuery { query }

    /// Includes both active and soft-deleted rows. Callers must still provide
    /// Comment and Purpose before execution.
    @discardableResult
    public func withDeletedRows() -> Self {
        var copy = self
        copy.query.filter = removingActiveVersionFilter(copy.query.filter)
        return copy
    }

    /// Returns only soft-deleted rows, represented by a negative version.
    @discardableResult
    public func deletedRowsOnly() -> Self {
        withDeletedRows().adding(.lessThanOrEqual("version", .int(-1)))
    }

    @discardableResult
    public func selectSelfFields() -> Self {
        var copy = self
        copy.query.projection = ["id", "title", "description", "platform", "version"]
        return copy
    }

    @discardableResult
    public func selectId() -> Self {
        var copy = self
        if !copy.query.projection.contains("id") {
            copy.query.projection.append("id")
        }
        return copy
    }


    @discardableResult
    public func selectTitle() -> Self {
        var copy = self
        if !copy.query.projection.contains("title") {
            copy.query.projection.append("title")
        }
        return copy
    }


    @discardableResult
    public func selectDescription() -> Self {
        var copy = self
        if !copy.query.projection.contains("description") {
            copy.query.projection.append("description")
        }
        return copy
    }




    @discardableResult
    public func selectVersion() -> Self {
        var copy = self
        if !copy.query.projection.contains("version") {
            copy.query.projection.append("version")
        }
        return copy
    }


    @discardableResult
    public func selectPlatform() -> Self {
        selectPlatformWith(Q.platformsWithMinimalFields())
    }

    @discardableResult
    public func selectPlatformWith<ChildState: Sendable>(
        _ child: PlatformRequest<ChildState>
    ) -> Self {
        var copy = self
        if !copy.query.projection.contains("platform") {
            copy.query.projection.append("platform")
        }
        copy.query.relationQuery(
            "platformEntity",
            localKey: "platform",
            foreignKey: "id",
            many: false,
            query: child.toQuery())
        return copy
    }

    @discardableResult
    public func orderByIdAscending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("id", .ascending)); return copy
    }

    @discardableResult
    public func orderByIdDescending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("id", .descending)); return copy
    }

    @discardableResult
    public func orderByTitleAscending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("title", .ascending)); return copy
    }

    @discardableResult
    public func orderByTitleDescending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("title", .descending)); return copy
    }

    @discardableResult
    public func orderByDescriptionAscending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("description", .ascending)); return copy
    }

    @discardableResult
    public func orderByDescriptionDescending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("description", .descending)); return copy
    }

    @discardableResult
    public func orderByPlatformAscending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("platform", .ascending)); return copy
    }

    @discardableResult
    public func orderByPlatformDescending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("platform", .descending)); return copy
    }

    @discardableResult
    public func orderByVersionAscending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("version", .ascending)); return copy
    }

    @discardableResult
    public func orderByVersionDescending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("version", .descending)); return copy
    }



    @discardableResult
    public func withIdIs(_ value: Int64) -> Self {
        adding(.equal("id", .int(value)))
    }

    @discardableResult
    public func withIdIn(_ values: [Int64]) -> Self {
        adding(.inList("id", values.map { .int($0) }))
    }

    @discardableResult
    public func withIdIsNot(_ value: Int64) -> Self {
        adding(.notEqual("id", .int(value)))
    }

    @discardableResult
    public func withIdNotIn(_ values: [Int64]) -> Self {
        adding(.notInList("id", values.map { .int($0) }))
    }

    @discardableResult
    public func withIdGreaterThan(_ value: Int64) -> Self {
        adding(.greaterThan("id", .int(value)))
    }

    @discardableResult
    public func withIdGreaterThanOrEqualTo(_ value: Int64) -> Self {
        adding(.greaterThanOrEqual("id", .int(value)))
    }

    @discardableResult
    public func withIdLessThan(_ value: Int64) -> Self {
        adding(.lessThan("id", .int(value)))
    }

    @discardableResult
    public func withIdLessThanOrEqualTo(_ value: Int64) -> Self {
        adding(.lessThanOrEqual("id", .int(value)))
    }

    @discardableResult
    public func withIdBetween(_ lower: Int64, _ upper: Int64) -> Self {
        adding(.between("id", .int(lower), .int(upper)))
    }

    @discardableResult
    public func withIdIsKnown() -> Self {
        adding(.isNotNull("id"))
    }

    @discardableResult
    public func withIdIsUnknown() -> Self {
        adding(.isNull("id"))
    }


    @discardableResult
    public func withTitleIs(_ value: String) -> Self {
        adding(.equal("title", .string(value)))
    }

    @discardableResult
    public func withTitleIn(_ values: [String]) -> Self {
        adding(.inList("title", values.map { .string($0) }))
    }

    @discardableResult
    public func withTitleIsNot(_ value: String) -> Self {
        adding(.notEqual("title", .string(value)))
    }

    @discardableResult
    public func withTitleNotIn(_ values: [String]) -> Self {
        adding(.notInList("title", values.map { .string($0) }))
    }

    @discardableResult
    public func withTitleGreaterThan(_ value: String) -> Self {
        adding(.greaterThan("title", .string(value)))
    }

    @discardableResult
    public func withTitleGreaterThanOrEqualTo(_ value: String) -> Self {
        adding(.greaterThanOrEqual("title", .string(value)))
    }

    @discardableResult
    public func withTitleLessThan(_ value: String) -> Self {
        adding(.lessThan("title", .string(value)))
    }

    @discardableResult
    public func withTitleLessThanOrEqualTo(_ value: String) -> Self {
        adding(.lessThanOrEqual("title", .string(value)))
    }

    @discardableResult
    public func withTitleBetween(_ lower: String, _ upper: String) -> Self {
        adding(.between("title", .string(lower), .string(upper)))
    }

    @discardableResult
    public func withTitleIsKnown() -> Self {
        adding(.isNotNull("title"))
    }

    @discardableResult
    public func withTitleIsUnknown() -> Self {
        adding(.isNull("title"))
    }
    @discardableResult
    public func withTitleContaining(_ value: String) -> Self {
        adding(.contains("title", value))
    }

    @discardableResult
    public func withTitleNotContaining(_ value: String) -> Self {
        adding(.notContains("title", value))
    }

    @discardableResult
    public func withTitleStartingWith(_ value: String) -> Self {
        adding(.startsWith("title", value))
    }

    @discardableResult
    public func withTitleNotStartingWith(_ value: String) -> Self {
        adding(.notStartsWith("title", value))
    }

    @discardableResult
    public func withTitleEndingWith(_ value: String) -> Self {
        adding(.endsWith("title", value))
    }

    @discardableResult
    public func withTitleNotEndingWith(_ value: String) -> Self {
        adding(.notEndsWith("title", value))
    }

    @discardableResult
    public func withTitleSoundingLike(_ value: String) -> Self {
        adding(.soundingLike("title", value))
    }


    @discardableResult
    public func withDescriptionIs(_ value: String) -> Self {
        adding(.equal("description", .string(value)))
    }

    @discardableResult
    public func withDescriptionIn(_ values: [String]) -> Self {
        adding(.inList("description", values.map { .string($0) }))
    }

    @discardableResult
    public func withDescriptionIsNot(_ value: String) -> Self {
        adding(.notEqual("description", .string(value)))
    }

    @discardableResult
    public func withDescriptionNotIn(_ values: [String]) -> Self {
        adding(.notInList("description", values.map { .string($0) }))
    }

    @discardableResult
    public func withDescriptionGreaterThan(_ value: String) -> Self {
        adding(.greaterThan("description", .string(value)))
    }

    @discardableResult
    public func withDescriptionGreaterThanOrEqualTo(_ value: String) -> Self {
        adding(.greaterThanOrEqual("description", .string(value)))
    }

    @discardableResult
    public func withDescriptionLessThan(_ value: String) -> Self {
        adding(.lessThan("description", .string(value)))
    }

    @discardableResult
    public func withDescriptionLessThanOrEqualTo(_ value: String) -> Self {
        adding(.lessThanOrEqual("description", .string(value)))
    }

    @discardableResult
    public func withDescriptionBetween(_ lower: String, _ upper: String) -> Self {
        adding(.between("description", .string(lower), .string(upper)))
    }

    @discardableResult
    public func withDescriptionIsKnown() -> Self {
        adding(.isNotNull("description"))
    }

    @discardableResult
    public func withDescriptionIsUnknown() -> Self {
        adding(.isNull("description"))
    }
    @discardableResult
    public func withDescriptionContaining(_ value: String) -> Self {
        adding(.contains("description", value))
    }

    @discardableResult
    public func withDescriptionNotContaining(_ value: String) -> Self {
        adding(.notContains("description", value))
    }

    @discardableResult
    public func withDescriptionStartingWith(_ value: String) -> Self {
        adding(.startsWith("description", value))
    }

    @discardableResult
    public func withDescriptionNotStartingWith(_ value: String) -> Self {
        adding(.notStartsWith("description", value))
    }

    @discardableResult
    public func withDescriptionEndingWith(_ value: String) -> Self {
        adding(.endsWith("description", value))
    }

    @discardableResult
    public func withDescriptionNotEndingWith(_ value: String) -> Self {
        adding(.notEndsWith("description", value))
    }

    @discardableResult
    public func withDescriptionSoundingLike(_ value: String) -> Self {
        adding(.soundingLike("description", value))
    }


    @discardableResult
    public func filterByPlatform(_ value: Int64) -> Self {
        adding(.equal("platform", .int(value)))
    }

    @discardableResult
    public func filterByPlatformIn(_ values: [Int64]) -> Self {
        adding(.inList("platform", values.map(TeaQLValue.int)))
    }

    @discardableResult
    public func withPlatformIsKnown() -> Self {
        adding(.isNotNull("platform"))
    }

    @discardableResult
    public func withPlatformIsUnknown() -> Self {
        adding(.isNull("platform"))
    }


    @discardableResult
    public func withVersionIs(_ value: Int64) -> Self {
        adding(.equal("version", .int(value)))
    }

    @discardableResult
    public func withVersionIn(_ values: [Int64]) -> Self {
        adding(.inList("version", values.map { .int($0) }))
    }

    @discardableResult
    public func withVersionIsNot(_ value: Int64) -> Self {
        adding(.notEqual("version", .int(value)))
    }

    @discardableResult
    public func withVersionNotIn(_ values: [Int64]) -> Self {
        adding(.notInList("version", values.map { .int($0) }))
    }

    @discardableResult
    public func withVersionGreaterThan(_ value: Int64) -> Self {
        adding(.greaterThan("version", .int(value)))
    }

    @discardableResult
    public func withVersionGreaterThanOrEqualTo(_ value: Int64) -> Self {
        adding(.greaterThanOrEqual("version", .int(value)))
    }

    @discardableResult
    public func withVersionLessThan(_ value: Int64) -> Self {
        adding(.lessThan("version", .int(value)))
    }

    @discardableResult
    public func withVersionLessThanOrEqualTo(_ value: Int64) -> Self {
        adding(.lessThanOrEqual("version", .int(value)))
    }

    @discardableResult
    public func withVersionBetween(_ lower: Int64, _ upper: Int64) -> Self {
        adding(.between("version", .int(lower), .int(upper)))
    }

    @discardableResult
    public func withVersionIsKnown() -> Self {
        adding(.isNotNull("version"))
    }

    @discardableResult
    public func withVersionIsUnknown() -> Self {
        adding(.isNull("version"))
    }


    @discardableResult
    public func withPlatformMatching<ChildState: Sendable>(
        _ child: PlatformRequest<ChildState>
    ) -> Self {
        adding(.inSubquery("platform", RelationQueryPlan(child.toQuery()), "id"))
    }

    @discardableResult
    public func withoutPlatformMatching<ChildState: Sendable>(
        _ child: PlatformRequest<ChildState>
    ) -> Self {
        adding(.notInSubquery("platform", RelationQueryPlan(child.toQuery()), "id"))
    }


    @discardableResult
    public func facetByPlatformAs<NestedState: Sendable>(
        _ name: String,
        _ request: PlatformRequest<NestedState>,
        includeAllFacets: Bool = true
    ) -> Self {
        var copy = self
        copy.query.facets.append(FacetRequest(
            name: name,
            relationName: "platform",
            query: request.toQuery(),
            includeAllFacets: includeAllFacets))
        return copy
    }


    @discardableResult
    public func count() -> Self { countAs("count") }

    @discardableResult
    public func countAs(_ alias: String) -> Self {
        var copy = self
        copy.query.aggregates.append(QueryAggregate(.count, field: "*", alias: alias))
        return copy
    }


    @discardableResult
    public func groupById() -> Self {
        var copy = self
        copy.query.groupBy.append("id")
        return copy
    }

    @discardableResult
    public func groupByTitle() -> Self {
        var copy = self
        copy.query.groupBy.append("title")
        return copy
    }

    @discardableResult
    public func groupByDescription() -> Self {
        var copy = self
        copy.query.groupBy.append("description")
        return copy
    }

    @discardableResult
    public func groupByPlatform() -> Self {
        var copy = self
        copy.query.groupBy.append("platform")
        return copy
    }

    @discardableResult
    public func groupByVersion() -> Self {
        var copy = self
        copy.query.groupBy.append("version")
        return copy
    }

    private func adding(_ expression: TeaQLExpression) -> Self {
        var copy = self
        copy.query.filter = copy.query.filter.map { .and([$0, expression]) } ?? expression
        return copy
    }

    private func removingActiveVersionFilter(
        _ expression: TeaQLExpression?
    ) -> TeaQLExpression? {
        guard let expression else { return nil }
        let active = TeaQLExpression.greaterThanOrEqual("version", .int(1))
        if expression == active { return nil }
        guard case .and(let items) = expression else { return expression }
        let retained = items.compactMap { removingActiveVersionFilter($0) }
        if retained.isEmpty { return nil }
        if retained.count == 1 { return retained[0] }
        return .and(retained)
    }
}

public extension WorkItemRequest where State == RequestExecutable {
    private func ensureIntent() throws {
        guard let comment = query.comment,
              !comment.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            throw TeaQLError.execution("Comment is required before execution")
        }
        guard let purpose = query.purpose,
              !purpose.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            throw TeaQLError.execution("Purpose is required before execution")
        }
    }

    func newEntity(_ context: UserContext) throws -> WorkItem {
        try ensureIntent()
        return context.initializeEntity("WorkItem", WorkItem())
    }

    func executeForList(_ context: UserContext) async throws -> SmartList<WorkItem> {
        try ensureIntent()
        let result = try await context.execute(query)
        let queryRoot = EntityRoot()
        return SmartList(
            try result.records.map { try WorkItem.from(record: $0, root: queryRoot) },
            facets: result.facets)
    }

    func executeForRows(_ context: UserContext) async throws -> SmartList<TeaQLRecord> {
        try ensureIntent()
        let result = try await context.execute(query)
        return SmartList(result.records, facets: result.facets)
    }

    func executeForPage(
        _ context: UserContext, offset: Int, limit: Int
    ) async throws -> TeaQLPage<WorkItem> {
        try ensureIntent()
        var pageQuery = query
        pageQuery.offset = offset
        pageQuery.limit = limit
        let result = try await context.execute(pageQuery)
        let observation = await context.idSetPaginationObservation()
        let total: Int
        if pageQuery.idSetPagination != nil && observation.countAccuracy == "EXACT" {
            total = observation.count
        } else {
            total = try await context.count(pageQuery)
        }
        let queryRoot = EntityRoot()
        let items = SmartList(
            try result.records.map { try WorkItem.from(record: $0, root: queryRoot) },
            totalCount: total)
        return TeaQLPage(items: items, total: total, offset: offset, limit: limit)
    }
}