// Generated by TeaQL. Do not edit directly.
import Foundation
import TeaQLCore

private struct PlatformChecker: EntityChecker {
    func checkAndFix(
        context: UserContext, mutation: inout Mutation, now: Date
    ) throws -> [CheckResult] {
        var results: [CheckResult] = []
        if mutation.kind == .create && (mutation.values["create_time"] == nil || mutation.values["create_time"] == .null) {
            mutation.values["create_time"] = .timestamp(Int64(now.timeIntervalSince1970 * 1_000))
            context.recordFixEvidence(FixEvidence(entityType: "Platform", modelPath: "create_time", source: .clock, sourceLabel: "graphClock"))
        }

        if mutation.kind == .create && (mutation.values["update_time"] == nil || mutation.values["update_time"] == .null) {
            mutation.values["update_time"] = .timestamp(Int64(now.timeIntervalSince1970 * 1_000))
            context.recordFixEvidence(FixEvidence(entityType: "Platform", modelPath: "update_time", source: .clock, sourceLabel: "graphClock"))
        }
        if mutation.kind == .update {
            mutation.values["update_time"] = .timestamp(Int64(now.timeIntervalSince1970 * 1_000))
            context.recordFixEvidence(FixEvidence(entityType: "Platform", modelPath: "update_time", source: .clock, sourceLabel: "graphClock"))
        }


        if (mutation.kind == .create && mutation.values["name"] == nil) || mutation.values["name"] == .null { results.append(CheckResult(ruleID: "required", location: .property("name"))) }
        if let value = mutation.values["name"]?.stringValue, value.count > 100 { results.append(CheckResult(ruleID: "max_length", location: .property("name"), inputValue: value, systemValue: "100")) }

        if (mutation.kind == .create && mutation.values["base_url"] == nil) || mutation.values["base_url"] == .null { results.append(CheckResult(ruleID: "required", location: .property("base_url"))) }
        if let value = mutation.values["base_url"]?.stringValue, value.count > 100 { results.append(CheckResult(ruleID: "max_length", location: .property("base_url"), inputValue: value, systemValue: "100")) }

        if (mutation.kind == .create && mutation.values["create_time"] == nil) || mutation.values["create_time"] == .null { results.append(CheckResult(ruleID: "required", location: .property("create_time"))) }

        if (mutation.kind == .create && mutation.values["update_time"] == nil) || mutation.values["update_time"] == .null { results.append(CheckResult(ruleID: "required", location: .property("update_time"))) }


        return results
    }
}

private struct SchoolTypeChecker: EntityChecker {
    func checkAndFix(
        context: UserContext, mutation: inout Mutation, now: Date
    ) throws -> [CheckResult] {
        var results: [CheckResult] = []
        if (mutation.kind == .create && mutation.values["platform"] == nil) || mutation.values["platform"] == .null { results.append(CheckResult(ruleID: "required", location: .property("platform"))) }


        if (mutation.kind == .create && mutation.values["name"] == nil) || mutation.values["name"] == .null { results.append(CheckResult(ruleID: "required", location: .property("name"))) }
        if let value = mutation.values["name"]?.stringValue, value.count > 100 { results.append(CheckResult(ruleID: "max_length", location: .property("name"), inputValue: value, systemValue: "100")) }

        if (mutation.kind == .create && mutation.values["code"] == nil) || mutation.values["code"] == .null { results.append(CheckResult(ruleID: "required", location: .property("code"))) }
        if let value = mutation.values["code"]?.stringValue, value.count > 100 { results.append(CheckResult(ruleID: "max_length", location: .property("code"), inputValue: value, systemValue: "100")) }

        if (mutation.kind == .create && mutation.values["display_order"] == nil) || mutation.values["display_order"] == .null { results.append(CheckResult(ruleID: "required", location: .property("display_order"))) }


        return results
    }
}

private struct SchoolChecker: EntityChecker {
    func checkAndFix(
        context: UserContext, mutation: inout Mutation, now: Date
    ) throws -> [CheckResult] {
        var results: [CheckResult] = []
        if mutation.kind == .create && (mutation.values["create_time"] == nil || mutation.values["create_time"] == .null) {
            mutation.values["create_time"] = .timestamp(Int64(now.timeIntervalSince1970 * 1_000))
            context.recordFixEvidence(FixEvidence(entityType: "School", modelPath: "create_time", source: .clock, sourceLabel: "graphClock"))
        }

        if mutation.kind == .create && (mutation.values["update_time"] == nil || mutation.values["update_time"] == .null) {
            mutation.values["update_time"] = .timestamp(Int64(now.timeIntervalSince1970 * 1_000))
            context.recordFixEvidence(FixEvidence(entityType: "School", modelPath: "update_time", source: .clock, sourceLabel: "graphClock"))
        }
        if mutation.kind == .update {
            mutation.values["update_time"] = .timestamp(Int64(now.timeIntervalSince1970 * 1_000))
            context.recordFixEvidence(FixEvidence(entityType: "School", modelPath: "update_time", source: .clock, sourceLabel: "graphClock"))
        }


        if (mutation.kind == .create && mutation.values["platform"] == nil) || mutation.values["platform"] == .null { results.append(CheckResult(ruleID: "required", location: .property("platform"))) }

        if (mutation.kind == .create && mutation.values["school_type"] == nil) || mutation.values["school_type"] == .null { results.append(CheckResult(ruleID: "required", location: .property("school_type"))) }

        if (mutation.kind == .create && mutation.values["name"] == nil) || mutation.values["name"] == .null { results.append(CheckResult(ruleID: "required", location: .property("name"))) }
        if let value = mutation.values["name"]?.stringValue, value.count > 100 { results.append(CheckResult(ruleID: "max_length", location: .property("name"), inputValue: value, systemValue: "100")) }

        if (mutation.kind == .create && mutation.values["address"] == nil) || mutation.values["address"] == .null { results.append(CheckResult(ruleID: "required", location: .property("address"))) }
        if let value = mutation.values["address"]?.stringValue, value.count > 100 { results.append(CheckResult(ruleID: "max_length", location: .property("address"), inputValue: value, systemValue: "100")) }

        if (mutation.kind == .create && mutation.values["established_date"] == nil) || mutation.values["established_date"] == .null { results.append(CheckResult(ruleID: "required", location: .property("established_date"))) }

        if (mutation.kind == .create && mutation.values["student_capacity"] == nil) || mutation.values["student_capacity"] == .null { results.append(CheckResult(ruleID: "required", location: .property("student_capacity"))) }

        if (mutation.kind == .create && mutation.values["active"] == nil) || mutation.values["active"] == .null { results.append(CheckResult(ruleID: "required", location: .property("active"))) }

        if (mutation.kind == .create && mutation.values["create_time"] == nil) || mutation.values["create_time"] == .null { results.append(CheckResult(ruleID: "required", location: .property("create_time"))) }

        if (mutation.kind == .create && mutation.values["update_time"] == nil) || mutation.values["update_time"] == .null { results.append(CheckResult(ruleID: "required", location: .property("update_time"))) }


        return results
    }
}

/// Passive generated metadata. Installing it never creates or changes schema.
public enum GeneratedRuntimeModule {
    public static let module = RuntimeModule(
        name: "school-management-service",
        entities: [
           Platform.descriptor,
           SchoolType.descriptor,
           School.descriptor
        ],
        checkers: [
           "Platform": PlatformChecker(),
           "SchoolType": SchoolTypeChecker(),
           "School": SchoolChecker()
        ],
        rootEntities: [.init(entity: "Platform", id: 1, values: ["name": .string("Campus Learning Platform"), "base_url": .string("https://campus.example.com"), "create_time": .date(Date()), "update_time": .date(Date())])],
        constantEntities: [
            .init(entity: "SchoolType", id: 1001, values: ["platform": .int(1), "name": .string("Primary"), "code": .string("PRIMARY"), "display_order": .decimal(Decimal(string: "1")!)]),
            .init(entity: "SchoolType", id: 1002, values: ["platform": .int(1), "name": .string("Secondary"), "code": .string("SECONDARY"), "display_order": .decimal(Decimal(string: "2")!)])
        ]
    )
}