// Generated by TeaQL. Do not edit directly.
import Foundation
import TeaQLCore

private struct PlatformChecker: EntityChecker {
    func checkAndFix(
        context: UserContext, mutation: inout Mutation, now: Date
    ) throws -> [CheckResult] {
        var results: [CheckResult] = []
        if mutation.kind == .create && (mutation.values["create_time"] == nil || mutation.values["create_time"] == .null) {
            mutation.values["create_time"] = .timestamp(Int64(now.timeIntervalSince1970 * 1_000))
            context.recordFixEvidence(FixEvidence(entityType: "Platform", modelPath: "create_time", source: .clock, sourceLabel: "graphClock"))
        }

        if mutation.kind == .create && (mutation.values["update_time"] == nil || mutation.values["update_time"] == .null) {
            mutation.values["update_time"] = .timestamp(Int64(now.timeIntervalSince1970 * 1_000))
            context.recordFixEvidence(FixEvidence(entityType: "Platform", modelPath: "update_time", source: .clock, sourceLabel: "graphClock"))
        }
        if mutation.kind == .update {
            mutation.values["update_time"] = .timestamp(Int64(now.timeIntervalSince1970 * 1_000))
            context.recordFixEvidence(FixEvidence(entityType: "Platform", modelPath: "update_time", source: .clock, sourceLabel: "graphClock"))
        }


        if (mutation.kind == .create && mutation.values["name"] == nil) || mutation.values["name"] == .null { results.append(CheckResult(ruleID: "required", location: .property("name"))) }
        if let value = mutation.values["name"]?.stringValue, value.count > 100 { results.append(CheckResult(ruleID: "max_length", location: .property("name"), inputValue: value, systemValue: "100")) }

        if (mutation.kind == .create && mutation.values["base_url"] == nil) || mutation.values["base_url"] == .null { results.append(CheckResult(ruleID: "required", location: .property("base_url"))) }
        if let value = mutation.values["base_url"]?.stringValue, value.count > 100 { results.append(CheckResult(ruleID: "max_length", location: .property("base_url"), inputValue: value, systemValue: "100")) }

        if (mutation.kind == .create && mutation.values["create_time"] == nil) || mutation.values["create_time"] == .null { results.append(CheckResult(ruleID: "required", location: .property("create_time"))) }

        if (mutation.kind == .create && mutation.values["update_time"] == nil) || mutation.values["update_time"] == .null { results.append(CheckResult(ruleID: "required", location: .property("update_time"))) }


        return results
    }
}

private struct SchoolTypeChecker: EntityChecker {
    func checkAndFix(
        context: UserContext, mutation: inout Mutation, now: Date
    ) throws -> [CheckResult] {
        var results: [CheckResult] = []
        if (mutation.kind == .create && mutation.values["platform"] == nil) || mutation.values["platform"] == .null { results.append(CheckResult(ruleID: "required", location: .property("platform"))) }


        if (mutation.kind == .create && mutation.values["name"] == nil) || mutation.values["name"] == .null { results.append(CheckResult(ruleID: "required", location: .property("name"))) }
        if let value = mutation.values["name"]?.stringValue, value.count > 100 { results.append(CheckResult(ruleID: "max_length", location: .property("name"), inputValue: value, systemValue: "100")) }

        if (mutation.kind == .create && mutation.values["code"] == nil) || mutation.values["code"] == .null { results.append(CheckResult(ruleID: "required", location: .property("code"))) }
        if let value = mutation.values["code"]?.stringValue, value.count > 100 { results.append(CheckResult(ruleID: "max_length", location: .property("code"), inputValue: value, systemValue: "100")) }

        if (mutation.kind == .create && mutation.values["display_order"] == nil) || mutation.values["display_order"] == .null { results.append(CheckResult(ruleID: "required", location: .property("display_order"))) }


        return results
    }
}

private struct SchoolChecker: EntityChecker {
    func checkAndFix(
        context: UserContext, mutation: inout Mutation, now: Date
    ) throws -> [CheckResult] {
        var results: [CheckResult] = []
        if mutation.kind == .create && (mutation.values["create_time"] == nil || mutation.values["create_time"] == .null) {
            mutation.values["create_time"] = .timestamp(Int64(now.timeIntervalSince1970 * 1_000))
            context.recordFixEvidence(FixEvidence(entityType: "School", modelPath: "create_time", source: .clock, sourceLabel: "graphClock"))
        }

        if mutation.kind == .create && (mutation.values["update_time"] == nil || mutation.values["update_time"] == .null) {
            mutation.values["update_time"] = .timestamp(Int64(now.timeIntervalSince1970 * 1_000))
            context.recordFixEvidence(FixEvidence(entityType: "School", modelPath: "update_time", source: .clock, sourceLabel: "graphClock"))
        }
        if mutation.kind == .update {
            mutation.values["update_time"] = .timestamp(Int64(now.timeIntervalSince1970 * 1_000))
            context.recordFixEvidence(FixEvidence(entityType: "School", modelPath: "update_time", source: .clock, sourceLabel: "graphClock"))
        }


        if (mutation.kind == .create && mutation.values["platform"] == nil) || mutation.values["platform"] == .null { results.append(CheckResult(ruleID: "required", location: .property("platform"))) }

        if (mutation.kind == .create && mutation.values["school_type"] == nil) || mutation.values["school_type"] == .null { results.append(CheckResult(ruleID: "required", location: .property("school_type"))) }

        if (mutation.kind == .create && mutation.values["name"] == nil) || mutation.values["name"] == .null { results.append(CheckResult(ruleID: "required", location: .property("name"))) }
        if let value = mutation.values["name"]?.stringValue, value.count > 100 { results.append(CheckResult(ruleID: "max_length", location: .property("name"), inputValue: value, systemValue: "100")) }

        if (mutation.kind == .create && mutation.values["address"] == nil) || mutation.values["address"] == .null { results.append(CheckResult(ruleID: "required", location: .property("address"))) }
        if let value = mutation.values["address"]?.stringValue, value.count > 100 { results.append(CheckResult(ruleID: "max_length", location: .property("address"), inputValue: value, systemValue: "100")) }

        if (mutation.kind == .create && mutation.values["established_date"] == nil) || mutation.values["established_date"] == .null { results.append(CheckResult(ruleID: "required", location: .property("established_date"))) }

        if (mutation.kind == .create && mutation.values["student_capacity"] == nil) || mutation.values["student_capacity"] == .null { results.append(CheckResult(ruleID: "required", location: .property("student_capacity"))) }

        if (mutation.kind == .create && mutation.values["active"] == nil) || mutation.values["active"] == .null { results.append(CheckResult(ruleID: "required", location: .property("active"))) }

        if (mutation.kind == .create && mutation.values["create_time"] == nil) || mutation.values["create_time"] == .null { results.append(CheckResult(ruleID: "required", location: .property("create_time"))) }

        if (mutation.kind == .create && mutation.values["update_time"] == nil) || mutation.values["update_time"] == .null { results.append(CheckResult(ruleID: "required", location: .property("update_time"))) }


        return results
    }
}

/// Passive generated metadata. Installing it never creates or changes schema.
public enum GeneratedRuntimeModule {
    public static let module = RuntimeModule(
        name: "school-management-service",
        entities: [
           Platform.descriptor,
           SchoolType.descriptor,
           School.descriptor
        ],
        checkers: [
           "Platform": PlatformChecker(),
           "SchoolType": SchoolTypeChecker(),
           "School": SchoolChecker()
        ],
        generatedBootstrap: ensureGeneratedBootstrap,

        wireMetadata: [
            "Platform": try! WireEntityMetadata(entityType: "Platform", canonicalFields: ["id", "name", "base_url", "create_time", "update_time", "version"], aliases: ["id": ["id"], "name": ["name"], "base_url": ["base_url"], "create_time": ["create_time"], "update_time": ["update_time"], "version": ["version"]]),
            "SchoolType": try! WireEntityMetadata(entityType: "SchoolType", canonicalFields: ["platform", "id", "name", "code", "display_order", "version"], aliases: ["platform": ["platform"], "id": ["id"], "name": ["name"], "code": ["code"], "display_order": ["display_order"], "version": ["version"]]),
            "School": try! WireEntityMetadata(entityType: "School", canonicalFields: ["id", "platform", "school_type", "name", "address", "established_date", "student_capacity", "active", "create_time", "update_time", "version"], aliases: ["id": ["id"], "platform": ["platform"], "school_type": ["school_type"], "name": ["name"], "address": ["address"], "established_date": ["established_date"], "student_capacity": ["student_capacity"], "active": ["active"], "create_time": ["create_time"], "update_time": ["update_time"], "version": ["version"]])
        ]
    )

    private static func ensureGeneratedBootstrap(_ callerContext: UserContext) async throws {
        var lastError: Error?
        for attempt in 0..<5 {
            do { try await ensureGeneratedBootstrapOnce(callerContext); return }
            catch { lastError = error; if attempt < 4 { try await Task.sleep(nanoseconds: UInt64(attempt + 1) * 10_000_000) } }
        }
        throw lastError!
    }

    private static func ensureGeneratedBootstrapOnce(_ callerContext: UserContext) async throws {
        let bootstrapContext = callerContext._generatedBootstrapContext()
        var domainRoot = try await Q.platforms().withIdIs(1).comment("what: locate generated Domain Root").purpose("why: idempotent runtime bootstrap").executeForList(bootstrapContext).first
        if domainRoot == nil {
            var created = try Q.platforms().comment("what: create generated Domain Root").purpose("why: initialize runtime bootstrap").newEntity(bootstrapContext)
            created.teaqlInitializeGeneratedBootstrapId(1)
            created.updateName("Campus Learning Platform")
            created.updateBaseUrl("https://campus.example.com")
            do { domainRoot = try await created.auditAs("create generated Domain Root Platform").save(bootstrapContext) }
            catch { domainRoot = try await Q.platforms().withIdIs(1).comment("what: recover concurrent Domain Root bootstrap").purpose("why: make bootstrap idempotent").executeForList(bootstrapContext).first; if domainRoot == nil { throw error } }
        }
        guard let domainRoot else { throw TeaQLError.execution("Generated Domain Root bootstrap failed") }
        let rootedContext = callerContext._generatedBootstrapContext(activeRoot: ContextEntityRef(entity: "Platform", id: .int(domainRoot.id)))
        var constantSchoolType1001 = try await Q.schoolTypes().withIdIs(1001).comment("what: locate generated constant").purpose("why: idempotent runtime bootstrap").executeForList(rootedContext).first
        if constantSchoolType1001 == nil {
            var created = try Q.schoolTypes().comment("what: create generated constant").purpose("why: initialize runtime bootstrap").newEntity(rootedContext)
            created.teaqlInitializeGeneratedBootstrapId(1001)
            created.updatePlatform(domainRoot.id)
            created.updateName("Primary")
            created.updateCode("PRIMARY")
            created.updateDisplayOrder(Decimal(string: "1")!)
            do { constantSchoolType1001 = try await created.auditAs("create model constant SchoolType(1001)").save(rootedContext) }
            catch { constantSchoolType1001 = try await Q.schoolTypes().withIdIs(1001).comment("what: recover concurrent constant bootstrap").purpose("why: make bootstrap idempotent").executeForList(rootedContext).first; if constantSchoolType1001 == nil { throw error } }
        } else {
            var current = constantSchoolType1001!
            var changed = false
            if current.platform != domainRoot.id {
                current.updatePlatform(domainRoot.id)
                changed = true
            }
            if current.name != "Primary" {
                current.updateName("Primary")
                changed = true
            }
            if current.code != "PRIMARY" {
                current.updateCode("PRIMARY")
                changed = true
            }
            if current.displayOrder != Decimal(string: "1")! {
                current.updateDisplayOrder(Decimal(string: "1")!)
                changed = true
            }
            if changed { constantSchoolType1001 = try await current.auditAs("reconcile model constant SchoolType(1001)").save(rootedContext) }
        }
        var constantSchoolType1002 = try await Q.schoolTypes().withIdIs(1002).comment("what: locate generated constant").purpose("why: idempotent runtime bootstrap").executeForList(rootedContext).first
        if constantSchoolType1002 == nil {
            var created = try Q.schoolTypes().comment("what: create generated constant").purpose("why: initialize runtime bootstrap").newEntity(rootedContext)
            created.teaqlInitializeGeneratedBootstrapId(1002)
            created.updatePlatform(domainRoot.id)
            created.updateName("Secondary")
            created.updateCode("SECONDARY")
            created.updateDisplayOrder(Decimal(string: "2")!)
            do { constantSchoolType1002 = try await created.auditAs("create model constant SchoolType(1002)").save(rootedContext) }
            catch { constantSchoolType1002 = try await Q.schoolTypes().withIdIs(1002).comment("what: recover concurrent constant bootstrap").purpose("why: make bootstrap idempotent").executeForList(rootedContext).first; if constantSchoolType1002 == nil { throw error } }
        } else {
            var current = constantSchoolType1002!
            var changed = false
            if current.platform != domainRoot.id {
                current.updatePlatform(domainRoot.id)
                changed = true
            }
            if current.name != "Secondary" {
                current.updateName("Secondary")
                changed = true
            }
            if current.code != "SECONDARY" {
                current.updateCode("SECONDARY")
                changed = true
            }
            if current.displayOrder != Decimal(string: "2")! {
                current.updateDisplayOrder(Decimal(string: "2")!)
                changed = true
            }
            if changed { constantSchoolType1002 = try await current.auditAs("reconcile model constant SchoolType(1002)").save(rootedContext) }
        }
    }

    private static func generatedBootstrapDate(_ value: String) throws -> Date {
        if let date = ISO8601DateFormatter().date(from: value) { return date }
        let formatter = DateFormatter(); formatter.locale = Locale(identifier: "en_US_POSIX"); formatter.timeZone = TimeZone(secondsFromGMT: 0); formatter.dateFormat = "yyyy-MM-dd"
        guard let date = formatter.date(from: value) else { throw TeaQLError.execution("Invalid generated bootstrap date: \(value)") }; return date
    }

}