// Generated by TeaQL. Do not edit directly.
import Foundation
import TeaQLCore

public struct PlatformRequest<State: Sendable>: Sendable {
    private var query: SelectQuery

    init(query: SelectQuery) { self.query = query }

    @discardableResult
    public func comment(_ value: String) -> Self {
        var copy = self; copy.query.comment = value; return copy
    }

    public func purpose(_ value: String) -> PlatformRequest<RequestExecutable> {
        var copy = query; copy.purpose = value
        return PlatformRequest<RequestExecutable>(query: copy)
    }

    @discardableResult
    public func limit(_ value: Int) -> Self {
        var copy = self; copy.query.limit = value; return copy
    }

    @discardableResult
    public func topNProbeParentThreshold(_ value: Int) -> Self {
        var copy = self; copy.query.topNProbeParentThreshold(value); return copy
    }

    @discardableResult
    public func hardLimit(_ value: Int) -> Self {
        var copy = self; copy.query.hardLimit = value; return copy
    }

    @discardableResult
    public func offset(_ value: Int) -> Self {
        var copy = self; copy.query.offset = value; return copy
    }

    @discardableResult
    public func optimizeForContinuousPageFetch() -> Self {
        optimizeForContinuousPageFetch(namespace: "default", ttlSeconds: 600)
    }

    @discardableResult
    public func optimizeForContinuousPageFetch(namespace: String, ttlSeconds: Int) -> Self {
        var copy = self
        copy.query.continuousPage = ContinuousPageFetchOptions(
            namespace: namespace, ttlSeconds: ttlSeconds)
        return copy
    }

    @discardableResult
    public func optimizePaginationWithIdSet() -> Self {
        optimizePaginationWithIdSet(namespace: "default", ttlSeconds: 600, maxIds: 3_000_000)
    }

    @discardableResult
    public func optimizePaginationWithIdSet(
        namespace: String, ttlSeconds: Int, maxIds: Int
    ) -> Self {
        var copy = self
        copy.query.idSetPagination = IdSetPaginationOptions(
            namespace: namespace, ttlSeconds: ttlSeconds, maxIds: maxIds)
        return copy
    }

    public func toQuery() -> SelectQuery { query }

    /// Includes both active and soft-deleted rows. Callers must still provide
    /// Comment and Purpose before execution.
    @discardableResult
    public func withDeletedRows() -> Self {
        var copy = self
        copy.query.filter = removingActiveVersionFilter(copy.query.filter)
        return copy
    }

    /// Returns only soft-deleted rows, represented by a negative version.
    @discardableResult
    public func deletedRowsOnly() -> Self {
        withDeletedRows().adding(.lessThanOrEqual("version", .int(-1)))
    }

    @discardableResult
    public func selectSelfFields() -> Self {
        var copy = self
        copy.query.projection = ["id", "name", "baseUrl", "createTime", "updateTime", "version"]
        return copy
    }

    @discardableResult
    public func selectId() -> Self {
        var copy = self
        if !copy.query.projection.contains("id") {
            copy.query.projection.append("id")
        }
        return copy
    }


    @discardableResult
    public func selectName() -> Self {
        var copy = self
        if !copy.query.projection.contains("name") {
            copy.query.projection.append("name")
        }
        return copy
    }


    @discardableResult
    public func selectBaseUrl() -> Self {
        var copy = self
        if !copy.query.projection.contains("baseUrl") {
            copy.query.projection.append("baseUrl")
        }
        return copy
    }


    @discardableResult
    public func selectCreateTime() -> Self {
        var copy = self
        if !copy.query.projection.contains("createTime") {
            copy.query.projection.append("createTime")
        }
        return copy
    }


    @discardableResult
    public func selectUpdateTime() -> Self {
        var copy = self
        if !copy.query.projection.contains("updateTime") {
            copy.query.projection.append("updateTime")
        }
        return copy
    }


    @discardableResult
    public func selectVersion() -> Self {
        var copy = self
        if !copy.query.projection.contains("version") {
            copy.query.projection.append("version")
        }
        return copy
    }



    @discardableResult
    public func orderByIdAscending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("id", .ascending)); return copy
    }

    @discardableResult
    public func orderByIdDescending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("id", .descending)); return copy
    }

    @discardableResult
    public func orderByNameAscending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("name", .ascending)); return copy
    }

    @discardableResult
    public func orderByNameDescending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("name", .descending)); return copy
    }

    @discardableResult
    public func orderByBaseUrlAscending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("baseUrl", .ascending)); return copy
    }

    @discardableResult
    public func orderByBaseUrlDescending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("baseUrl", .descending)); return copy
    }

    @discardableResult
    public func orderByCreateTimeAscending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("createTime", .ascending)); return copy
    }

    @discardableResult
    public func orderByCreateTimeDescending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("createTime", .descending)); return copy
    }

    @discardableResult
    public func orderByUpdateTimeAscending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("updateTime", .ascending)); return copy
    }

    @discardableResult
    public func orderByUpdateTimeDescending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("updateTime", .descending)); return copy
    }

    @discardableResult
    public func orderByVersionAscending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("version", .ascending)); return copy
    }

    @discardableResult
    public func orderByVersionDescending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("version", .descending)); return copy
    }

    @discardableResult
    public func selectSchoolTypeList() -> Self {
        selectSchoolTypeListWith(SchoolTypeRequest<RequestDraft>(
            query: SelectQuery(entity: SchoolType.descriptor)))
    }

    @discardableResult
    public func selectSchoolTypeListWith<ChildState: Sendable>(
        _ child: SchoolTypeRequest<ChildState>
    ) -> Self {
        var copy = self
        copy.query.relationQuery(
            "schoolTypeList",
            localKey: "id",
            foreignKey: "platform",
            many: true,
            query: child.toQuery())
        return copy
    }

    @discardableResult
    public func selectSchoolList() -> Self {
        selectSchoolListWith(SchoolRequest<RequestDraft>(
            query: SelectQuery(entity: School.descriptor)))
    }

    @discardableResult
    public func selectSchoolListWith<ChildState: Sendable>(
        _ child: SchoolRequest<ChildState>
    ) -> Self {
        var copy = self
        copy.query.relationQuery(
            "schoolList",
            localKey: "id",
            foreignKey: "platform",
            many: true,
            query: child.toQuery())
        return copy
    }

    @discardableResult
    public func countSchoolTypes() -> Self {
        countSchoolTypesAs("countSchoolTypes")
    }

    @discardableResult
    public func countSchoolTypesAs(_ alias: String) -> Self {
        countSchoolTypesWith(alias, Q.schoolTypes())
    }

    @discardableResult
    public func countSchoolTypesWith<ChildState: Sendable>(
        _ alias: String, _ child: SchoolTypeRequest<ChildState>
    ) -> Self {
        var copy = self
        var childQuery = child.toQuery()
        childQuery.aggregates.append(QueryAggregate(.count, field: "id", alias: alias))
        copy.query.relationAggregate(
            "schoolTypeList", foreignKey: "platform", alias: alias,
            query: childQuery, singleResult: true)
        return copy
    }

    @discardableResult
    public func minDisplayOrderOfSchoolTypes() -> Self {
        minDisplayOrderOfSchoolTypesAs(
            "minOfDisplayOrderOfSchoolTypes",
            Q.schoolTypes())
    }

    @discardableResult
    public func minDisplayOrderOfSchoolTypesAs<ChildState: Sendable>(
        _ alias: String, _ child: SchoolTypeRequest<ChildState>
    ) -> Self {
        var copy = self
        var childQuery = child.toQuery()
        childQuery.aggregates.append(
            QueryAggregate(.min, field: "displayOrder", alias: "min_displayOrder"))
        copy.query.relationAggregate(
            "schoolTypeList", foreignKey: "platform", alias: alias,
            query: childQuery, singleResult: true)
        return copy
    }


    @discardableResult
    public func maxDisplayOrderOfSchoolTypes() -> Self {
        maxDisplayOrderOfSchoolTypesAs(
            "maxOfDisplayOrderOfSchoolTypes",
            Q.schoolTypes())
    }

    @discardableResult
    public func maxDisplayOrderOfSchoolTypesAs<ChildState: Sendable>(
        _ alias: String, _ child: SchoolTypeRequest<ChildState>
    ) -> Self {
        var copy = self
        var childQuery = child.toQuery()
        childQuery.aggregates.append(
            QueryAggregate(.max, field: "displayOrder", alias: "max_displayOrder"))
        copy.query.relationAggregate(
            "schoolTypeList", foreignKey: "platform", alias: alias,
            query: childQuery, singleResult: true)
        return copy
    }


    @discardableResult
    public func sumDisplayOrderOfSchoolTypes() -> Self {
        sumDisplayOrderOfSchoolTypesAs(
            "sumOfDisplayOrderOfSchoolTypes",
            Q.schoolTypes())
    }

    @discardableResult
    public func sumDisplayOrderOfSchoolTypesAs<ChildState: Sendable>(
        _ alias: String, _ child: SchoolTypeRequest<ChildState>
    ) -> Self {
        var copy = self
        var childQuery = child.toQuery()
        childQuery.aggregates.append(
            QueryAggregate(.sum, field: "displayOrder", alias: "sum_displayOrder"))
        copy.query.relationAggregate(
            "schoolTypeList", foreignKey: "platform", alias: alias,
            query: childQuery, singleResult: true)
        return copy
    }


    @discardableResult
    public func avgDisplayOrderOfSchoolTypes() -> Self {
        avgDisplayOrderOfSchoolTypesAs(
            "avgOfDisplayOrderOfSchoolTypes",
            Q.schoolTypes())
    }

    @discardableResult
    public func avgDisplayOrderOfSchoolTypesAs<ChildState: Sendable>(
        _ alias: String, _ child: SchoolTypeRequest<ChildState>
    ) -> Self {
        var copy = self
        var childQuery = child.toQuery()
        childQuery.aggregates.append(
            QueryAggregate(.avg, field: "displayOrder", alias: "avg_displayOrder"))
        copy.query.relationAggregate(
            "schoolTypeList", foreignKey: "platform", alias: alias,
            query: childQuery, singleResult: true)
        return copy
    }






    @discardableResult
    public func countSchools() -> Self {
        countSchoolsAs("countSchools")
    }

    @discardableResult
    public func countSchoolsAs(_ alias: String) -> Self {
        countSchoolsWith(alias, Q.schools())
    }

    @discardableResult
    public func countSchoolsWith<ChildState: Sendable>(
        _ alias: String, _ child: SchoolRequest<ChildState>
    ) -> Self {
        var copy = self
        var childQuery = child.toQuery()
        childQuery.aggregates.append(QueryAggregate(.count, field: "id", alias: alias))
        copy.query.relationAggregate(
            "schoolList", foreignKey: "platform", alias: alias,
            query: childQuery, singleResult: true)
        return copy
    }

    @discardableResult
    public func minStudentCapacityOfSchools() -> Self {
        minStudentCapacityOfSchoolsAs(
            "minOfStudentCapacityOfSchools",
            Q.schools())
    }

    @discardableResult
    public func minStudentCapacityOfSchoolsAs<ChildState: Sendable>(
        _ alias: String, _ child: SchoolRequest<ChildState>
    ) -> Self {
        var copy = self
        var childQuery = child.toQuery()
        childQuery.aggregates.append(
            QueryAggregate(.min, field: "studentCapacity", alias: "min_studentCapacity"))
        copy.query.relationAggregate(
            "schoolList", foreignKey: "platform", alias: alias,
            query: childQuery, singleResult: true)
        return copy
    }


    @discardableResult
    public func maxStudentCapacityOfSchools() -> Self {
        maxStudentCapacityOfSchoolsAs(
            "maxOfStudentCapacityOfSchools",
            Q.schools())
    }

    @discardableResult
    public func maxStudentCapacityOfSchoolsAs<ChildState: Sendable>(
        _ alias: String, _ child: SchoolRequest<ChildState>
    ) -> Self {
        var copy = self
        var childQuery = child.toQuery()
        childQuery.aggregates.append(
            QueryAggregate(.max, field: "studentCapacity", alias: "max_studentCapacity"))
        copy.query.relationAggregate(
            "schoolList", foreignKey: "platform", alias: alias,
            query: childQuery, singleResult: true)
        return copy
    }


    @discardableResult
    public func sumStudentCapacityOfSchools() -> Self {
        sumStudentCapacityOfSchoolsAs(
            "sumOfStudentCapacityOfSchools",
            Q.schools())
    }

    @discardableResult
    public func sumStudentCapacityOfSchoolsAs<ChildState: Sendable>(
        _ alias: String, _ child: SchoolRequest<ChildState>
    ) -> Self {
        var copy = self
        var childQuery = child.toQuery()
        childQuery.aggregates.append(
            QueryAggregate(.sum, field: "studentCapacity", alias: "sum_studentCapacity"))
        copy.query.relationAggregate(
            "schoolList", foreignKey: "platform", alias: alias,
            query: childQuery, singleResult: true)
        return copy
    }


    @discardableResult
    public func avgStudentCapacityOfSchools() -> Self {
        avgStudentCapacityOfSchoolsAs(
            "avgOfStudentCapacityOfSchools",
            Q.schools())
    }

    @discardableResult
    public func avgStudentCapacityOfSchoolsAs<ChildState: Sendable>(
        _ alias: String, _ child: SchoolRequest<ChildState>
    ) -> Self {
        var copy = self
        var childQuery = child.toQuery()
        childQuery.aggregates.append(
            QueryAggregate(.avg, field: "studentCapacity", alias: "avg_studentCapacity"))
        copy.query.relationAggregate(
            "schoolList", foreignKey: "platform", alias: alias,
            query: childQuery, singleResult: true)
        return copy
    }






    @discardableResult
    public func withIdIs(_ value: Int64) -> Self {
        adding(.equal("id", .int(value)))
    }

    @discardableResult
    public func withIdIn(_ values: [Int64]) -> Self {
        adding(.inList("id", values.map { .int($0) }))
    }

    @discardableResult
    public func withIdIsNot(_ value: Int64) -> Self {
        adding(.notEqual("id", .int(value)))
    }

    @discardableResult
    public func withIdNotIn(_ values: [Int64]) -> Self {
        adding(.notInList("id", values.map { .int($0) }))
    }

    @discardableResult
    public func withIdGreaterThan(_ value: Int64) -> Self {
        adding(.greaterThan("id", .int(value)))
    }

    @discardableResult
    public func withIdGreaterThanOrEqualTo(_ value: Int64) -> Self {
        adding(.greaterThanOrEqual("id", .int(value)))
    }

    @discardableResult
    public func withIdLessThan(_ value: Int64) -> Self {
        adding(.lessThan("id", .int(value)))
    }

    @discardableResult
    public func withIdLessThanOrEqualTo(_ value: Int64) -> Self {
        adding(.lessThanOrEqual("id", .int(value)))
    }

    @discardableResult
    public func withIdBetween(_ lower: Int64, _ upper: Int64) -> Self {
        adding(.between("id", .int(lower), .int(upper)))
    }

    @discardableResult
    public func withIdIsKnown() -> Self {
        adding(.isNotNull("id"))
    }

    @discardableResult
    public func withIdIsUnknown() -> Self {
        adding(.isNull("id"))
    }


    @discardableResult
    public func withNameIs(_ value: String) -> Self {
        adding(.equal("name", .string(value)))
    }

    @discardableResult
    public func withNameIn(_ values: [String]) -> Self {
        adding(.inList("name", values.map { .string($0) }))
    }

    @discardableResult
    public func withNameIsNot(_ value: String) -> Self {
        adding(.notEqual("name", .string(value)))
    }

    @discardableResult
    public func withNameNotIn(_ values: [String]) -> Self {
        adding(.notInList("name", values.map { .string($0) }))
    }

    @discardableResult
    public func withNameGreaterThan(_ value: String) -> Self {
        adding(.greaterThan("name", .string(value)))
    }

    @discardableResult
    public func withNameGreaterThanOrEqualTo(_ value: String) -> Self {
        adding(.greaterThanOrEqual("name", .string(value)))
    }

    @discardableResult
    public func withNameLessThan(_ value: String) -> Self {
        adding(.lessThan("name", .string(value)))
    }

    @discardableResult
    public func withNameLessThanOrEqualTo(_ value: String) -> Self {
        adding(.lessThanOrEqual("name", .string(value)))
    }

    @discardableResult
    public func withNameBetween(_ lower: String, _ upper: String) -> Self {
        adding(.between("name", .string(lower), .string(upper)))
    }

    @discardableResult
    public func withNameIsKnown() -> Self {
        adding(.isNotNull("name"))
    }

    @discardableResult
    public func withNameIsUnknown() -> Self {
        adding(.isNull("name"))
    }
    @discardableResult
    public func withNameContaining(_ value: String) -> Self {
        adding(.contains("name", value))
    }

    @discardableResult
    public func withNameNotContaining(_ value: String) -> Self {
        adding(.notContains("name", value))
    }

    @discardableResult
    public func withNameStartingWith(_ value: String) -> Self {
        adding(.startsWith("name", value))
    }

    @discardableResult
    public func withNameNotStartingWith(_ value: String) -> Self {
        adding(.notStartsWith("name", value))
    }

    @discardableResult
    public func withNameEndingWith(_ value: String) -> Self {
        adding(.endsWith("name", value))
    }

    @discardableResult
    public func withNameNotEndingWith(_ value: String) -> Self {
        adding(.notEndsWith("name", value))
    }

    @discardableResult
    public func withNameSoundingLike(_ value: String) -> Self {
        adding(.soundingLike("name", value))
    }


    @discardableResult
    public func withBaseUrlIs(_ value: String) -> Self {
        adding(.equal("baseUrl", .string(value)))
    }

    @discardableResult
    public func withBaseUrlIn(_ values: [String]) -> Self {
        adding(.inList("baseUrl", values.map { .string($0) }))
    }

    @discardableResult
    public func withBaseUrlIsNot(_ value: String) -> Self {
        adding(.notEqual("baseUrl", .string(value)))
    }

    @discardableResult
    public func withBaseUrlNotIn(_ values: [String]) -> Self {
        adding(.notInList("baseUrl", values.map { .string($0) }))
    }

    @discardableResult
    public func withBaseUrlGreaterThan(_ value: String) -> Self {
        adding(.greaterThan("baseUrl", .string(value)))
    }

    @discardableResult
    public func withBaseUrlGreaterThanOrEqualTo(_ value: String) -> Self {
        adding(.greaterThanOrEqual("baseUrl", .string(value)))
    }

    @discardableResult
    public func withBaseUrlLessThan(_ value: String) -> Self {
        adding(.lessThan("baseUrl", .string(value)))
    }

    @discardableResult
    public func withBaseUrlLessThanOrEqualTo(_ value: String) -> Self {
        adding(.lessThanOrEqual("baseUrl", .string(value)))
    }

    @discardableResult
    public func withBaseUrlBetween(_ lower: String, _ upper: String) -> Self {
        adding(.between("baseUrl", .string(lower), .string(upper)))
    }

    @discardableResult
    public func withBaseUrlIsKnown() -> Self {
        adding(.isNotNull("baseUrl"))
    }

    @discardableResult
    public func withBaseUrlIsUnknown() -> Self {
        adding(.isNull("baseUrl"))
    }
    @discardableResult
    public func withBaseUrlContaining(_ value: String) -> Self {
        adding(.contains("baseUrl", value))
    }

    @discardableResult
    public func withBaseUrlNotContaining(_ value: String) -> Self {
        adding(.notContains("baseUrl", value))
    }

    @discardableResult
    public func withBaseUrlStartingWith(_ value: String) -> Self {
        adding(.startsWith("baseUrl", value))
    }

    @discardableResult
    public func withBaseUrlNotStartingWith(_ value: String) -> Self {
        adding(.notStartsWith("baseUrl", value))
    }

    @discardableResult
    public func withBaseUrlEndingWith(_ value: String) -> Self {
        adding(.endsWith("baseUrl", value))
    }

    @discardableResult
    public func withBaseUrlNotEndingWith(_ value: String) -> Self {
        adding(.notEndsWith("baseUrl", value))
    }

    @discardableResult
    public func withBaseUrlSoundingLike(_ value: String) -> Self {
        adding(.soundingLike("baseUrl", value))
    }


    @discardableResult
    public func withCreateTimeIs(_ value: Date) -> Self {
        adding(.equal("createTime", .date(value)))
    }

    @discardableResult
    public func withCreateTimeIn(_ values: [Date]) -> Self {
        adding(.inList("createTime", values.map { .date($0) }))
    }

    @discardableResult
    public func withCreateTimeIsNot(_ value: Date) -> Self {
        adding(.notEqual("createTime", .date(value)))
    }

    @discardableResult
    public func withCreateTimeNotIn(_ values: [Date]) -> Self {
        adding(.notInList("createTime", values.map { .date($0) }))
    }

    @discardableResult
    public func withCreateTimeGreaterThan(_ value: Date) -> Self {
        adding(.greaterThan("createTime", .date(value)))
    }

    @discardableResult
    public func withCreateTimeGreaterThanOrEqualTo(_ value: Date) -> Self {
        adding(.greaterThanOrEqual("createTime", .date(value)))
    }

    @discardableResult
    public func withCreateTimeLessThan(_ value: Date) -> Self {
        adding(.lessThan("createTime", .date(value)))
    }

    @discardableResult
    public func withCreateTimeLessThanOrEqualTo(_ value: Date) -> Self {
        adding(.lessThanOrEqual("createTime", .date(value)))
    }

    @discardableResult
    public func withCreateTimeBetween(_ lower: Date, _ upper: Date) -> Self {
        adding(.between("createTime", .date(lower), .date(upper)))
    }

    @discardableResult
    public func withCreateTimeIsKnown() -> Self {
        adding(.isNotNull("createTime"))
    }

    @discardableResult
    public func withCreateTimeIsUnknown() -> Self {
        adding(.isNull("createTime"))
    }


    @discardableResult
    public func withUpdateTimeIs(_ value: Date) -> Self {
        adding(.equal("updateTime", .date(value)))
    }

    @discardableResult
    public func withUpdateTimeIn(_ values: [Date]) -> Self {
        adding(.inList("updateTime", values.map { .date($0) }))
    }

    @discardableResult
    public func withUpdateTimeIsNot(_ value: Date) -> Self {
        adding(.notEqual("updateTime", .date(value)))
    }

    @discardableResult
    public func withUpdateTimeNotIn(_ values: [Date]) -> Self {
        adding(.notInList("updateTime", values.map { .date($0) }))
    }

    @discardableResult
    public func withUpdateTimeGreaterThan(_ value: Date) -> Self {
        adding(.greaterThan("updateTime", .date(value)))
    }

    @discardableResult
    public func withUpdateTimeGreaterThanOrEqualTo(_ value: Date) -> Self {
        adding(.greaterThanOrEqual("updateTime", .date(value)))
    }

    @discardableResult
    public func withUpdateTimeLessThan(_ value: Date) -> Self {
        adding(.lessThan("updateTime", .date(value)))
    }

    @discardableResult
    public func withUpdateTimeLessThanOrEqualTo(_ value: Date) -> Self {
        adding(.lessThanOrEqual("updateTime", .date(value)))
    }

    @discardableResult
    public func withUpdateTimeBetween(_ lower: Date, _ upper: Date) -> Self {
        adding(.between("updateTime", .date(lower), .date(upper)))
    }

    @discardableResult
    public func withUpdateTimeIsKnown() -> Self {
        adding(.isNotNull("updateTime"))
    }

    @discardableResult
    public func withUpdateTimeIsUnknown() -> Self {
        adding(.isNull("updateTime"))
    }


    @discardableResult
    public func withVersionIs(_ value: Int64) -> Self {
        adding(.equal("version", .int(value)))
    }

    @discardableResult
    public func withVersionIn(_ values: [Int64]) -> Self {
        adding(.inList("version", values.map { .int($0) }))
    }

    @discardableResult
    public func withVersionIsNot(_ value: Int64) -> Self {
        adding(.notEqual("version", .int(value)))
    }

    @discardableResult
    public func withVersionNotIn(_ values: [Int64]) -> Self {
        adding(.notInList("version", values.map { .int($0) }))
    }

    @discardableResult
    public func withVersionGreaterThan(_ value: Int64) -> Self {
        adding(.greaterThan("version", .int(value)))
    }

    @discardableResult
    public func withVersionGreaterThanOrEqualTo(_ value: Int64) -> Self {
        adding(.greaterThanOrEqual("version", .int(value)))
    }

    @discardableResult
    public func withVersionLessThan(_ value: Int64) -> Self {
        adding(.lessThan("version", .int(value)))
    }

    @discardableResult
    public func withVersionLessThanOrEqualTo(_ value: Int64) -> Self {
        adding(.lessThanOrEqual("version", .int(value)))
    }

    @discardableResult
    public func withVersionBetween(_ lower: Int64, _ upper: Int64) -> Self {
        adding(.between("version", .int(lower), .int(upper)))
    }

    @discardableResult
    public func withVersionIsKnown() -> Self {
        adding(.isNotNull("version"))
    }

    @discardableResult
    public func withVersionIsUnknown() -> Self {
        adding(.isNull("version"))
    }



    @discardableResult
    public func haveSchoolTypes() -> Self {
        withSchoolTypeListMatching(SchoolTypeRequest<RequestDraft>(
            query: SelectQuery(entity: SchoolType.descriptor)))
    }

    @discardableResult
    public func haveNoSchoolTypes() -> Self {
        withoutSchoolTypeListMatching(SchoolTypeRequest<RequestDraft>(
            query: SelectQuery(entity: SchoolType.descriptor)))
    }

    @discardableResult
    public func withSchoolTypeListMatching<ChildState: Sendable>(
        _ child: SchoolTypeRequest<ChildState>
    ) -> Self {
        adding(.inSubquery("id", RelationQueryPlan(child.toQuery()), "platform"))
    }

    @discardableResult
    public func withoutSchoolTypeListMatching<ChildState: Sendable>(
        _ child: SchoolTypeRequest<ChildState>
    ) -> Self {
        adding(.notInSubquery("id", RelationQueryPlan(child.toQuery()), "platform"))
    }

    @discardableResult
    public func haveSchools() -> Self {
        withSchoolListMatching(SchoolRequest<RequestDraft>(
            query: SelectQuery(entity: School.descriptor)))
    }

    @discardableResult
    public func haveNoSchools() -> Self {
        withoutSchoolListMatching(SchoolRequest<RequestDraft>(
            query: SelectQuery(entity: School.descriptor)))
    }

    @discardableResult
    public func withSchoolListMatching<ChildState: Sendable>(
        _ child: SchoolRequest<ChildState>
    ) -> Self {
        adding(.inSubquery("id", RelationQueryPlan(child.toQuery()), "platform"))
    }

    @discardableResult
    public func withoutSchoolListMatching<ChildState: Sendable>(
        _ child: SchoolRequest<ChildState>
    ) -> Self {
        adding(.notInSubquery("id", RelationQueryPlan(child.toQuery()), "platform"))
    }


    @discardableResult
    public func count() -> Self { countAs("count") }

    @discardableResult
    public func countAs(_ alias: String) -> Self {
        var copy = self
        copy.query.aggregates.append(QueryAggregate(.count, field: "*", alias: alias))
        return copy
    }


    @discardableResult
    public func groupById() -> Self {
        var copy = self
        copy.query.groupBy.append("id")
        return copy
    }

    @discardableResult
    public func groupByName() -> Self {
        var copy = self
        copy.query.groupBy.append("name")
        return copy
    }

    @discardableResult
    public func groupByBaseUrl() -> Self {
        var copy = self
        copy.query.groupBy.append("baseUrl")
        return copy
    }

    @discardableResult
    public func groupByCreateTime() -> Self {
        var copy = self
        copy.query.groupBy.append("createTime")
        return copy
    }

    @discardableResult
    public func groupByUpdateTime() -> Self {
        var copy = self
        copy.query.groupBy.append("updateTime")
        return copy
    }

    @discardableResult
    public func groupByVersion() -> Self {
        var copy = self
        copy.query.groupBy.append("version")
        return copy
    }

    private func adding(_ expression: TeaQLExpression) -> Self {
        var copy = self
        copy.query.filter = copy.query.filter.map { .and([$0, expression]) } ?? expression
        return copy
    }

    private func removingActiveVersionFilter(
        _ expression: TeaQLExpression?
    ) -> TeaQLExpression? {
        guard let expression else { return nil }
        let active = TeaQLExpression.greaterThanOrEqual("version", .int(1))
        if expression == active { return nil }
        guard case .and(let items) = expression else { return expression }
        let retained = items.compactMap { removingActiveVersionFilter($0) }
        if retained.isEmpty { return nil }
        if retained.count == 1 { return retained[0] }
        return .and(retained)
    }
}

public extension PlatformRequest where State == RequestExecutable {
    private func ensureIntent() throws {
        guard let comment = query.comment,
              !comment.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            throw TeaQLError.execution("Comment is required before execution")
        }
        guard let purpose = query.purpose,
              !purpose.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            throw TeaQLError.execution("Purpose is required before execution")
        }
    }

    func newEntity(_ context: UserContext) throws -> Platform {
        try ensureIntent()
        return context.initializeEntity("Platform", Platform())
    }

    func executeForList(_ context: UserContext) async throws -> SmartList<Platform> {
        try ensureIntent()
        let result = try await context.execute(query)
        let queryRoot = EntityRoot()
        return SmartList(
            try result.records.map { try Platform.from(record: $0, root: queryRoot) },
            facets: result.facets)
    }

    func executeForRows(_ context: UserContext) async throws -> SmartList<TeaQLRecord> {
        try ensureIntent()
        let result = try await context.execute(query)
        return SmartList(result.records, facets: result.facets)
    }

    func executeForPage(
        _ context: UserContext, offset: Int, limit: Int
    ) async throws -> TeaQLPage<Platform> {
        try ensureIntent()
        var pageQuery = query
        pageQuery.offset = offset
        pageQuery.limit = limit
        let result = try await context.execute(pageQuery)
        let observation = await context.idSetPaginationObservation()
        let total: Int
        if pageQuery.idSetPagination != nil && observation.countAccuracy == "EXACT" {
            total = observation.count
        } else {
            total = try await context.count(pageQuery)
        }
        let queryRoot = EntityRoot()
        let items = SmartList(
            try result.records.map { try Platform.from(record: $0, root: queryRoot) },
            totalCount: total)
        return TeaQLPage(items: items, total: total, offset: offset, limit: limit)
    }
}