// Generated by TeaQL. Do not edit directly.
import Foundation
import TeaQLCore

public struct SchoolTypeRequest<State: Sendable>: Sendable {
    private var query: SelectQuery

    init(query: SelectQuery) { self.query = query }

    @discardableResult
    public func comment(_ value: String) -> Self {
        var copy = self; copy.query.comment = value; return copy
    }

    public func purpose(_ value: String) -> SchoolTypeRequest<RequestExecutable> {
        var copy = query; copy.purpose = value
        return SchoolTypeRequest<RequestExecutable>(query: copy)
    }

    @discardableResult
    public func limit(_ value: Int) -> Self {
        var copy = self; copy.query.limit = value; return copy
    }

    @discardableResult
    public func hardLimit(_ value: Int) -> Self {
        var copy = self; copy.query.hardLimit = value; return copy
    }

    @discardableResult
    public func offset(_ value: Int) -> Self {
        var copy = self; copy.query.offset = value; return copy
    }

    public func toQuery() -> SelectQuery { query }

    /// Includes both active and soft-deleted rows. Callers must still provide
    /// Comment and Purpose before execution.
    @discardableResult
    public func withDeletedRows() -> Self {
        var copy = self
        copy.query.filter = removingActiveVersionFilter(copy.query.filter)
        return copy
    }

    /// Returns only soft-deleted rows, represented by a negative version.
    @discardableResult
    public func deletedRowsOnly() -> Self {
        withDeletedRows().adding(.lessThanOrEqual("version", .int(-1)))
    }

    @discardableResult
    public func selectSelfFields() -> Self {
        var copy = self
        copy.query.projection = ["platform", "id", "name", "code", "displayOrder", "version"]
        return copy
    }

    @discardableResult
    public func selectId() -> Self {
        var copy = self
        if !copy.query.projection.contains("id") {
            copy.query.projection.append("id")
        }
        return copy
    }


    @discardableResult
    public func selectName() -> Self {
        var copy = self
        if !copy.query.projection.contains("name") {
            copy.query.projection.append("name")
        }
        return copy
    }


    @discardableResult
    public func selectCode() -> Self {
        var copy = self
        if !copy.query.projection.contains("code") {
            copy.query.projection.append("code")
        }
        return copy
    }


    @discardableResult
    public func selectDisplayOrder() -> Self {
        var copy = self
        if !copy.query.projection.contains("displayOrder") {
            copy.query.projection.append("displayOrder")
        }
        return copy
    }


    @discardableResult
    public func selectVersion() -> Self {
        var copy = self
        if !copy.query.projection.contains("version") {
            copy.query.projection.append("version")
        }
        return copy
    }


    @discardableResult
    public func selectPlatform() -> Self {
        selectPlatformWith(Q.platformsWithMinimalFields())
    }

    @discardableResult
    public func selectPlatformWith<ChildState: Sendable>(
        _ child: PlatformRequest<ChildState>
    ) -> Self {
        var copy = self
        if !copy.query.projection.contains("platform") {
            copy.query.projection.append("platform")
        }
        copy.query.relationQuery(
            "platformEntity",
            localKey: "platform",
            foreignKey: "id",
            many: false,
            query: child.toQuery())
        return copy
    }

    @discardableResult
    public func orderByPlatformAscending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("platform", .ascending)); return copy
    }

    @discardableResult
    public func orderByPlatformDescending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("platform", .descending)); return copy
    }

    @discardableResult
    public func orderByIdAscending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("id", .ascending)); return copy
    }

    @discardableResult
    public func orderByIdDescending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("id", .descending)); return copy
    }

    @discardableResult
    public func orderByNameAscending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("name", .ascending)); return copy
    }

    @discardableResult
    public func orderByNameDescending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("name", .descending)); return copy
    }

    @discardableResult
    public func orderByCodeAscending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("code", .ascending)); return copy
    }

    @discardableResult
    public func orderByCodeDescending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("code", .descending)); return copy
    }

    @discardableResult
    public func orderByDisplayOrderAscending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("displayOrder", .ascending)); return copy
    }

    @discardableResult
    public func orderByDisplayOrderDescending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("displayOrder", .descending)); return copy
    }

    @discardableResult
    public func orderByVersionAscending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("version", .ascending)); return copy
    }

    @discardableResult
    public func orderByVersionDescending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("version", .descending)); return copy
    }

    @discardableResult
    public func selectSchoolList() -> Self {
        selectSchoolListWith(SchoolRequest<RequestDraft>(
            query: SelectQuery(entity: School.descriptor)))
    }

    @discardableResult
    public func selectSchoolListWith<ChildState: Sendable>(
        _ child: SchoolRequest<ChildState>
    ) -> Self {
        var copy = self
        copy.query.relationQuery(
            "schoolList",
            localKey: "id",
            foreignKey: "schoolType",
            many: true,
            query: child.toQuery())
        return copy
    }

    @discardableResult
    public func filterByPlatform(_ value: Int64) -> Self {
        adding(.equal("platform", .int(value)))
    }

    @discardableResult
    public func filterByPlatformIn(_ values: [Int64]) -> Self {
        adding(.inList("platform", values.map(TeaQLValue.int)))
    }


    @discardableResult
    public func withIdIs(_ value: Int64) -> Self {
        adding(.equal("id", .int(value)))
    }

    @discardableResult
    public func withIdIn(_ values: [Int64]) -> Self {
        adding(.inList("id", values.map { .int($0) }))
    }


    @discardableResult
    public func withNameIs(_ value: String) -> Self {
        adding(.equal("name", .string(value)))
    }

    @discardableResult
    public func withNameIn(_ values: [String]) -> Self {
        adding(.inList("name", values.map { .string($0) }))
    }
    @discardableResult
    public func withNameContaining(_ value: String) -> Self {
        adding(.contains("name", value))
    }


    @discardableResult
    public func withCodeIs(_ value: String) -> Self {
        adding(.equal("code", .string(value)))
    }

    @discardableResult
    public func withCodeIn(_ values: [String]) -> Self {
        adding(.inList("code", values.map { .string($0) }))
    }
    @discardableResult
    public func withCodeContaining(_ value: String) -> Self {
        adding(.contains("code", value))
    }


    @discardableResult
    public func withDisplayOrderIs(_ value: Decimal) -> Self {
        adding(.equal("displayOrder", .decimal(value)))
    }

    @discardableResult
    public func withDisplayOrderIn(_ values: [Decimal]) -> Self {
        adding(.inList("displayOrder", values.map { .decimal($0) }))
    }
    @discardableResult
    public func withDisplayOrderGreaterThanOrEqualTo(_ value: Decimal) -> Self {
        adding(.greaterThanOrEqual("displayOrder", .decimal(value)))
    }

    @discardableResult
    public func withDisplayOrderLessThanOrEqualTo(_ value: Decimal) -> Self {
        adding(.lessThanOrEqual("displayOrder", .decimal(value)))
    }


    @discardableResult
    public func withVersionIs(_ value: Int64) -> Self {
        adding(.equal("version", .int(value)))
    }

    @discardableResult
    public func withVersionIn(_ values: [Int64]) -> Self {
        adding(.inList("version", values.map { .int($0) }))
    }


    private func adding(_ expression: TeaQLExpression) -> Self {
        var copy = self
        copy.query.filter = copy.query.filter.map { .and([$0, expression]) } ?? expression
        return copy
    }

    private func removingActiveVersionFilter(
        _ expression: TeaQLExpression?
    ) -> TeaQLExpression? {
        guard let expression else { return nil }
        let active = TeaQLExpression.greaterThanOrEqual("version", .int(1))
        if expression == active { return nil }
        guard case .and(let items) = expression else { return expression }
        let retained = items.compactMap { removingActiveVersionFilter($0) }
        if retained.isEmpty { return nil }
        if retained.count == 1 { return retained[0] }
        return .and(retained)
    }
}

public extension SchoolTypeRequest where State == RequestExecutable {
    private func ensureIntent() throws {
        guard let comment = query.comment,
              !comment.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            throw TeaQLError.execution("Comment is required before execution")
        }
        guard let purpose = query.purpose,
              !purpose.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            throw TeaQLError.execution("Purpose is required before execution")
        }
    }

    func newEntity(_ context: UserContext) throws -> SchoolType {
        try ensureIntent()
        var entity = context.initializeEntity("SchoolType", SchoolType())
        entity.teaqlAttachRoot(context.entityRoot)
        return entity
    }

    func executeForList(_ context: UserContext) async throws -> SmartList<SchoolType> {
        try ensureIntent()
        return SmartList(try await context.execute(query).records.map { try SchoolType.from(record: $0, root: context.entityRoot) })
    }

    func executeForPage(
        _ context: UserContext, offset: Int, limit: Int
    ) async throws -> TeaQLPage<SchoolType> {
        try ensureIntent()
        var pageQuery = query
        pageQuery.offset = offset
        pageQuery.limit = limit
        let total = try await context.count(pageQuery)
        let items = SmartList(
            try await context.execute(pageQuery).records.map { try SchoolType.from(record: $0, root: context.entityRoot) },
            totalCount: total)
        return TeaQLPage(items: items, total: total, offset: offset, limit: limit)
    }
}