// Generated by TeaQL. Do not edit directly.
import Foundation
import TeaQLCore

public struct SchoolRequest<State: Sendable>: Sendable {
    private var query: SelectQuery

    init(query: SelectQuery) { self.query = query }

    @discardableResult
    public func comment(_ value: String) -> Self {
        var copy = self; copy.query.comment = value; return copy
    }

    public func purpose(_ value: String) -> SchoolRequest<RequestExecutable> {
        var copy = query; copy.purpose = value
        return SchoolRequest<RequestExecutable>(query: copy)
    }

    @discardableResult
    public func limit(_ value: Int) -> Self {
        var copy = self; copy.query.limit = value; return copy
    }

    @discardableResult
    public func topNProbeParentThreshold(_ value: Int) -> Self {
        var copy = self; copy.query.topNProbeParentThreshold(value); return copy
    }

    @discardableResult
    public func hardLimit(_ value: Int) -> Self {
        var copy = self; copy.query.hardLimit = value; return copy
    }

    @discardableResult
    public func offset(_ value: Int) -> Self {
        var copy = self; copy.query.offset = value; return copy
    }

    @discardableResult
    public func optimizeForContinuousPageFetch() -> Self {
        optimizeForContinuousPageFetch(namespace: "default", ttlSeconds: 600)
    }

    @discardableResult
    public func optimizeForContinuousPageFetch(namespace: String, ttlSeconds: Int) -> Self {
        var copy = self
        copy.query.continuousPage = ContinuousPageFetchOptions(
            namespace: namespace, ttlSeconds: ttlSeconds)
        return copy
    }

    @discardableResult
    public func optimizePaginationWithIdSet() -> Self {
        optimizePaginationWithIdSet(namespace: "default", ttlSeconds: 600, maxIds: 3_000_000)
    }

    @discardableResult
    public func optimizePaginationWithIdSet(
        namespace: String, ttlSeconds: Int, maxIds: Int
    ) -> Self {
        var copy = self
        copy.query.idSetPagination = IdSetPaginationOptions(
            namespace: namespace, ttlSeconds: ttlSeconds, maxIds: maxIds)
        return copy
    }

    public func toQuery() -> SelectQuery { query }

    /// Includes both active and soft-deleted rows. Callers must still provide
    /// Comment and Purpose before execution.
    @discardableResult
    public func withDeletedRows() -> Self {
        var copy = self
        copy.query.filter = removingActiveVersionFilter(copy.query.filter)
        return copy
    }

    /// Returns only soft-deleted rows, represented by a negative version.
    @discardableResult
    public func deletedRowsOnly() -> Self {
        withDeletedRows().adding(.lessThanOrEqual("version", .int(-1)))
    }

    @discardableResult
    public func selectSelfFields() -> Self {
        var copy = self
        copy.query.projection = ["id", "platform", "schoolType", "name", "address", "establishedDate", "studentCapacity", "active", "createTime", "updateTime", "version"]
        return copy
    }

    @discardableResult
    public func selectId() -> Self {
        var copy = self
        if !copy.query.projection.contains("id") {
            copy.query.projection.append("id")
        }
        return copy
    }






    @discardableResult
    public func selectName() -> Self {
        var copy = self
        if !copy.query.projection.contains("name") {
            copy.query.projection.append("name")
        }
        return copy
    }


    @discardableResult
    public func selectAddress() -> Self {
        var copy = self
        if !copy.query.projection.contains("address") {
            copy.query.projection.append("address")
        }
        return copy
    }


    @discardableResult
    public func selectEstablishedDate() -> Self {
        var copy = self
        if !copy.query.projection.contains("establishedDate") {
            copy.query.projection.append("establishedDate")
        }
        return copy
    }


    @discardableResult
    public func selectStudentCapacity() -> Self {
        var copy = self
        if !copy.query.projection.contains("studentCapacity") {
            copy.query.projection.append("studentCapacity")
        }
        return copy
    }


    @discardableResult
    public func selectActive() -> Self {
        var copy = self
        if !copy.query.projection.contains("active") {
            copy.query.projection.append("active")
        }
        return copy
    }


    @discardableResult
    public func selectCreateTime() -> Self {
        var copy = self
        if !copy.query.projection.contains("createTime") {
            copy.query.projection.append("createTime")
        }
        return copy
    }


    @discardableResult
    public func selectUpdateTime() -> Self {
        var copy = self
        if !copy.query.projection.contains("updateTime") {
            copy.query.projection.append("updateTime")
        }
        return copy
    }


    @discardableResult
    public func selectVersion() -> Self {
        var copy = self
        if !copy.query.projection.contains("version") {
            copy.query.projection.append("version")
        }
        return copy
    }


    @discardableResult
    public func selectPlatform() -> Self {
        selectPlatformWith(Q.platformsWithMinimalFields())
    }

    @discardableResult
    public func selectPlatformWith<ChildState: Sendable>(
        _ child: PlatformRequest<ChildState>
    ) -> Self {
        var copy = self
        if !copy.query.projection.contains("platform") {
            copy.query.projection.append("platform")
        }
        copy.query.relationQuery(
            "platformEntity",
            localKey: "platform",
            foreignKey: "id",
            many: false,
            query: child.toQuery())
        return copy
    }

    @discardableResult
    public func selectSchoolType() -> Self {
        selectSchoolTypeWith(Q.schoolTypesWithMinimalFields())
    }

    @discardableResult
    public func selectSchoolTypeWith<ChildState: Sendable>(
        _ child: SchoolTypeRequest<ChildState>
    ) -> Self {
        var copy = self
        if !copy.query.projection.contains("schoolType") {
            copy.query.projection.append("schoolType")
        }
        copy.query.relationQuery(
            "schoolTypeEntity",
            localKey: "schoolType",
            foreignKey: "id",
            many: false,
            query: child.toQuery())
        return copy
    }

    @discardableResult
    public func orderByIdAscending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("id", .ascending)); return copy
    }

    @discardableResult
    public func orderByIdDescending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("id", .descending)); return copy
    }

    @discardableResult
    public func orderByPlatformAscending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("platform", .ascending)); return copy
    }

    @discardableResult
    public func orderByPlatformDescending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("platform", .descending)); return copy
    }

    @discardableResult
    public func orderBySchoolTypeAscending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("schoolType", .ascending)); return copy
    }

    @discardableResult
    public func orderBySchoolTypeDescending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("schoolType", .descending)); return copy
    }

    @discardableResult
    public func orderByNameAscending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("name", .ascending)); return copy
    }

    @discardableResult
    public func orderByNameDescending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("name", .descending)); return copy
    }

    @discardableResult
    public func orderByAddressAscending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("address", .ascending)); return copy
    }

    @discardableResult
    public func orderByAddressDescending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("address", .descending)); return copy
    }

    @discardableResult
    public func orderByEstablishedDateAscending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("establishedDate", .ascending)); return copy
    }

    @discardableResult
    public func orderByEstablishedDateDescending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("establishedDate", .descending)); return copy
    }

    @discardableResult
    public func orderByStudentCapacityAscending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("studentCapacity", .ascending)); return copy
    }

    @discardableResult
    public func orderByStudentCapacityDescending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("studentCapacity", .descending)); return copy
    }

    @discardableResult
    public func orderByActiveAscending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("active", .ascending)); return copy
    }

    @discardableResult
    public func orderByActiveDescending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("active", .descending)); return copy
    }

    @discardableResult
    public func orderByCreateTimeAscending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("createTime", .ascending)); return copy
    }

    @discardableResult
    public func orderByCreateTimeDescending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("createTime", .descending)); return copy
    }

    @discardableResult
    public func orderByUpdateTimeAscending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("updateTime", .ascending)); return copy
    }

    @discardableResult
    public func orderByUpdateTimeDescending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("updateTime", .descending)); return copy
    }

    @discardableResult
    public func orderByVersionAscending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("version", .ascending)); return copy
    }

    @discardableResult
    public func orderByVersionDescending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("version", .descending)); return copy
    }



    @discardableResult
    public func withIdIs(_ value: Int64) -> Self {
        adding(.equal("id", .int(value)))
    }

    @discardableResult
    public func withIdIn(_ values: [Int64]) -> Self {
        adding(.inList("id", values.map { .int($0) }))
    }

    @discardableResult
    public func withIdIsNot(_ value: Int64) -> Self {
        adding(.notEqual("id", .int(value)))
    }

    @discardableResult
    public func withIdNotIn(_ values: [Int64]) -> Self {
        adding(.notInList("id", values.map { .int($0) }))
    }

    @discardableResult
    public func withIdGreaterThan(_ value: Int64) -> Self {
        adding(.greaterThan("id", .int(value)))
    }

    @discardableResult
    public func withIdGreaterThanOrEqualTo(_ value: Int64) -> Self {
        adding(.greaterThanOrEqual("id", .int(value)))
    }

    @discardableResult
    public func withIdLessThan(_ value: Int64) -> Self {
        adding(.lessThan("id", .int(value)))
    }

    @discardableResult
    public func withIdLessThanOrEqualTo(_ value: Int64) -> Self {
        adding(.lessThanOrEqual("id", .int(value)))
    }

    @discardableResult
    public func withIdBetween(_ lower: Int64, _ upper: Int64) -> Self {
        adding(.between("id", .int(lower), .int(upper)))
    }

    @discardableResult
    public func withIdIsKnown() -> Self {
        adding(.isNotNull("id"))
    }

    @discardableResult
    public func withIdIsUnknown() -> Self {
        adding(.isNull("id"))
    }


    @discardableResult
    public func filterByPlatform(_ value: Int64) -> Self {
        adding(.equal("platform", .int(value)))
    }

    @discardableResult
    public func filterByPlatformIn(_ values: [Int64]) -> Self {
        adding(.inList("platform", values.map(TeaQLValue.int)))
    }

    @discardableResult
    public func withPlatformIsKnown() -> Self {
        adding(.isNotNull("platform"))
    }

    @discardableResult
    public func withPlatformIsUnknown() -> Self {
        adding(.isNull("platform"))
    }


    @discardableResult
    public func filterBySchoolType(_ value: Int64) -> Self {
        adding(.equal("schoolType", .int(value)))
    }

    @discardableResult
    public func filterBySchoolTypeIn(_ values: [Int64]) -> Self {
        adding(.inList("schoolType", values.map(TeaQLValue.int)))
    }

    @discardableResult
    public func withSchoolTypeIsKnown() -> Self {
        adding(.isNotNull("schoolType"))
    }

    @discardableResult
    public func withSchoolTypeIsUnknown() -> Self {
        adding(.isNull("schoolType"))
    }
    @discardableResult
    public func withSchoolTypeIsPrimary() -> Self {
        adding(.equal("schoolType", .int(1001)))
    }


    @discardableResult
    public func withNameIs(_ value: String) -> Self {
        adding(.equal("name", .string(value)))
    }

    @discardableResult
    public func withNameIn(_ values: [String]) -> Self {
        adding(.inList("name", values.map { .string($0) }))
    }

    @discardableResult
    public func withNameIsNot(_ value: String) -> Self {
        adding(.notEqual("name", .string(value)))
    }

    @discardableResult
    public func withNameNotIn(_ values: [String]) -> Self {
        adding(.notInList("name", values.map { .string($0) }))
    }

    @discardableResult
    public func withNameGreaterThan(_ value: String) -> Self {
        adding(.greaterThan("name", .string(value)))
    }

    @discardableResult
    public func withNameGreaterThanOrEqualTo(_ value: String) -> Self {
        adding(.greaterThanOrEqual("name", .string(value)))
    }

    @discardableResult
    public func withNameLessThan(_ value: String) -> Self {
        adding(.lessThan("name", .string(value)))
    }

    @discardableResult
    public func withNameLessThanOrEqualTo(_ value: String) -> Self {
        adding(.lessThanOrEqual("name", .string(value)))
    }

    @discardableResult
    public func withNameBetween(_ lower: String, _ upper: String) -> Self {
        adding(.between("name", .string(lower), .string(upper)))
    }

    @discardableResult
    public func withNameIsKnown() -> Self {
        adding(.isNotNull("name"))
    }

    @discardableResult
    public func withNameIsUnknown() -> Self {
        adding(.isNull("name"))
    }
    @discardableResult
    public func withNameContaining(_ value: String) -> Self {
        adding(.contains("name", value))
    }

    @discardableResult
    public func withNameNotContaining(_ value: String) -> Self {
        adding(.notContains("name", value))
    }

    @discardableResult
    public func withNameStartingWith(_ value: String) -> Self {
        adding(.startsWith("name", value))
    }

    @discardableResult
    public func withNameNotStartingWith(_ value: String) -> Self {
        adding(.notStartsWith("name", value))
    }

    @discardableResult
    public func withNameEndingWith(_ value: String) -> Self {
        adding(.endsWith("name", value))
    }

    @discardableResult
    public func withNameNotEndingWith(_ value: String) -> Self {
        adding(.notEndsWith("name", value))
    }

    @discardableResult
    public func withNameSoundingLike(_ value: String) -> Self {
        adding(.soundingLike("name", value))
    }


    @discardableResult
    public func withAddressIs(_ value: String) -> Self {
        adding(.equal("address", .string(value)))
    }

    @discardableResult
    public func withAddressIn(_ values: [String]) -> Self {
        adding(.inList("address", values.map { .string($0) }))
    }

    @discardableResult
    public func withAddressIsNot(_ value: String) -> Self {
        adding(.notEqual("address", .string(value)))
    }

    @discardableResult
    public func withAddressNotIn(_ values: [String]) -> Self {
        adding(.notInList("address", values.map { .string($0) }))
    }

    @discardableResult
    public func withAddressGreaterThan(_ value: String) -> Self {
        adding(.greaterThan("address", .string(value)))
    }

    @discardableResult
    public func withAddressGreaterThanOrEqualTo(_ value: String) -> Self {
        adding(.greaterThanOrEqual("address", .string(value)))
    }

    @discardableResult
    public func withAddressLessThan(_ value: String) -> Self {
        adding(.lessThan("address", .string(value)))
    }

    @discardableResult
    public func withAddressLessThanOrEqualTo(_ value: String) -> Self {
        adding(.lessThanOrEqual("address", .string(value)))
    }

    @discardableResult
    public func withAddressBetween(_ lower: String, _ upper: String) -> Self {
        adding(.between("address", .string(lower), .string(upper)))
    }

    @discardableResult
    public func withAddressIsKnown() -> Self {
        adding(.isNotNull("address"))
    }

    @discardableResult
    public func withAddressIsUnknown() -> Self {
        adding(.isNull("address"))
    }
    @discardableResult
    public func withAddressContaining(_ value: String) -> Self {
        adding(.contains("address", value))
    }

    @discardableResult
    public func withAddressNotContaining(_ value: String) -> Self {
        adding(.notContains("address", value))
    }

    @discardableResult
    public func withAddressStartingWith(_ value: String) -> Self {
        adding(.startsWith("address", value))
    }

    @discardableResult
    public func withAddressNotStartingWith(_ value: String) -> Self {
        adding(.notStartsWith("address", value))
    }

    @discardableResult
    public func withAddressEndingWith(_ value: String) -> Self {
        adding(.endsWith("address", value))
    }

    @discardableResult
    public func withAddressNotEndingWith(_ value: String) -> Self {
        adding(.notEndsWith("address", value))
    }

    @discardableResult
    public func withAddressSoundingLike(_ value: String) -> Self {
        adding(.soundingLike("address", value))
    }


    @discardableResult
    public func withEstablishedDateIs(_ value: Date) -> Self {
        adding(.equal("establishedDate", .date(value)))
    }

    @discardableResult
    public func withEstablishedDateIn(_ values: [Date]) -> Self {
        adding(.inList("establishedDate", values.map { .date($0) }))
    }

    @discardableResult
    public func withEstablishedDateIsNot(_ value: Date) -> Self {
        adding(.notEqual("establishedDate", .date(value)))
    }

    @discardableResult
    public func withEstablishedDateNotIn(_ values: [Date]) -> Self {
        adding(.notInList("establishedDate", values.map { .date($0) }))
    }

    @discardableResult
    public func withEstablishedDateGreaterThan(_ value: Date) -> Self {
        adding(.greaterThan("establishedDate", .date(value)))
    }

    @discardableResult
    public func withEstablishedDateGreaterThanOrEqualTo(_ value: Date) -> Self {
        adding(.greaterThanOrEqual("establishedDate", .date(value)))
    }

    @discardableResult
    public func withEstablishedDateLessThan(_ value: Date) -> Self {
        adding(.lessThan("establishedDate", .date(value)))
    }

    @discardableResult
    public func withEstablishedDateLessThanOrEqualTo(_ value: Date) -> Self {
        adding(.lessThanOrEqual("establishedDate", .date(value)))
    }

    @discardableResult
    public func withEstablishedDateBetween(_ lower: Date, _ upper: Date) -> Self {
        adding(.between("establishedDate", .date(lower), .date(upper)))
    }

    @discardableResult
    public func withEstablishedDateIsKnown() -> Self {
        adding(.isNotNull("establishedDate"))
    }

    @discardableResult
    public func withEstablishedDateIsUnknown() -> Self {
        adding(.isNull("establishedDate"))
    }


    @discardableResult
    public func withStudentCapacityIs(_ value: Int64) -> Self {
        adding(.equal("studentCapacity", .int(value)))
    }

    @discardableResult
    public func withStudentCapacityIn(_ values: [Int64]) -> Self {
        adding(.inList("studentCapacity", values.map { .int($0) }))
    }

    @discardableResult
    public func withStudentCapacityIsNot(_ value: Int64) -> Self {
        adding(.notEqual("studentCapacity", .int(value)))
    }

    @discardableResult
    public func withStudentCapacityNotIn(_ values: [Int64]) -> Self {
        adding(.notInList("studentCapacity", values.map { .int($0) }))
    }

    @discardableResult
    public func withStudentCapacityGreaterThan(_ value: Int64) -> Self {
        adding(.greaterThan("studentCapacity", .int(value)))
    }

    @discardableResult
    public func withStudentCapacityGreaterThanOrEqualTo(_ value: Int64) -> Self {
        adding(.greaterThanOrEqual("studentCapacity", .int(value)))
    }

    @discardableResult
    public func withStudentCapacityLessThan(_ value: Int64) -> Self {
        adding(.lessThan("studentCapacity", .int(value)))
    }

    @discardableResult
    public func withStudentCapacityLessThanOrEqualTo(_ value: Int64) -> Self {
        adding(.lessThanOrEqual("studentCapacity", .int(value)))
    }

    @discardableResult
    public func withStudentCapacityBetween(_ lower: Int64, _ upper: Int64) -> Self {
        adding(.between("studentCapacity", .int(lower), .int(upper)))
    }

    @discardableResult
    public func withStudentCapacityIsKnown() -> Self {
        adding(.isNotNull("studentCapacity"))
    }

    @discardableResult
    public func withStudentCapacityIsUnknown() -> Self {
        adding(.isNull("studentCapacity"))
    }


    @discardableResult
    public func whichAreActive() -> Self {
        adding(.equal("active", .bool(true)))
    }

    @discardableResult
    public func whichAreNotActive() -> Self {
        adding(.equal("active", .bool(false)))
    }


    @discardableResult
    public func withCreateTimeIs(_ value: Date) -> Self {
        adding(.equal("createTime", .date(value)))
    }

    @discardableResult
    public func withCreateTimeIn(_ values: [Date]) -> Self {
        adding(.inList("createTime", values.map { .date($0) }))
    }

    @discardableResult
    public func withCreateTimeIsNot(_ value: Date) -> Self {
        adding(.notEqual("createTime", .date(value)))
    }

    @discardableResult
    public func withCreateTimeNotIn(_ values: [Date]) -> Self {
        adding(.notInList("createTime", values.map { .date($0) }))
    }

    @discardableResult
    public func withCreateTimeGreaterThan(_ value: Date) -> Self {
        adding(.greaterThan("createTime", .date(value)))
    }

    @discardableResult
    public func withCreateTimeGreaterThanOrEqualTo(_ value: Date) -> Self {
        adding(.greaterThanOrEqual("createTime", .date(value)))
    }

    @discardableResult
    public func withCreateTimeLessThan(_ value: Date) -> Self {
        adding(.lessThan("createTime", .date(value)))
    }

    @discardableResult
    public func withCreateTimeLessThanOrEqualTo(_ value: Date) -> Self {
        adding(.lessThanOrEqual("createTime", .date(value)))
    }

    @discardableResult
    public func withCreateTimeBetween(_ lower: Date, _ upper: Date) -> Self {
        adding(.between("createTime", .date(lower), .date(upper)))
    }

    @discardableResult
    public func withCreateTimeIsKnown() -> Self {
        adding(.isNotNull("createTime"))
    }

    @discardableResult
    public func withCreateTimeIsUnknown() -> Self {
        adding(.isNull("createTime"))
    }


    @discardableResult
    public func withUpdateTimeIs(_ value: Date) -> Self {
        adding(.equal("updateTime", .date(value)))
    }

    @discardableResult
    public func withUpdateTimeIn(_ values: [Date]) -> Self {
        adding(.inList("updateTime", values.map { .date($0) }))
    }

    @discardableResult
    public func withUpdateTimeIsNot(_ value: Date) -> Self {
        adding(.notEqual("updateTime", .date(value)))
    }

    @discardableResult
    public func withUpdateTimeNotIn(_ values: [Date]) -> Self {
        adding(.notInList("updateTime", values.map { .date($0) }))
    }

    @discardableResult
    public func withUpdateTimeGreaterThan(_ value: Date) -> Self {
        adding(.greaterThan("updateTime", .date(value)))
    }

    @discardableResult
    public func withUpdateTimeGreaterThanOrEqualTo(_ value: Date) -> Self {
        adding(.greaterThanOrEqual("updateTime", .date(value)))
    }

    @discardableResult
    public func withUpdateTimeLessThan(_ value: Date) -> Self {
        adding(.lessThan("updateTime", .date(value)))
    }

    @discardableResult
    public func withUpdateTimeLessThanOrEqualTo(_ value: Date) -> Self {
        adding(.lessThanOrEqual("updateTime", .date(value)))
    }

    @discardableResult
    public func withUpdateTimeBetween(_ lower: Date, _ upper: Date) -> Self {
        adding(.between("updateTime", .date(lower), .date(upper)))
    }

    @discardableResult
    public func withUpdateTimeIsKnown() -> Self {
        adding(.isNotNull("updateTime"))
    }

    @discardableResult
    public func withUpdateTimeIsUnknown() -> Self {
        adding(.isNull("updateTime"))
    }


    @discardableResult
    public func withVersionIs(_ value: Int64) -> Self {
        adding(.equal("version", .int(value)))
    }

    @discardableResult
    public func withVersionIn(_ values: [Int64]) -> Self {
        adding(.inList("version", values.map { .int($0) }))
    }

    @discardableResult
    public func withVersionIsNot(_ value: Int64) -> Self {
        adding(.notEqual("version", .int(value)))
    }

    @discardableResult
    public func withVersionNotIn(_ values: [Int64]) -> Self {
        adding(.notInList("version", values.map { .int($0) }))
    }

    @discardableResult
    public func withVersionGreaterThan(_ value: Int64) -> Self {
        adding(.greaterThan("version", .int(value)))
    }

    @discardableResult
    public func withVersionGreaterThanOrEqualTo(_ value: Int64) -> Self {
        adding(.greaterThanOrEqual("version", .int(value)))
    }

    @discardableResult
    public func withVersionLessThan(_ value: Int64) -> Self {
        adding(.lessThan("version", .int(value)))
    }

    @discardableResult
    public func withVersionLessThanOrEqualTo(_ value: Int64) -> Self {
        adding(.lessThanOrEqual("version", .int(value)))
    }

    @discardableResult
    public func withVersionBetween(_ lower: Int64, _ upper: Int64) -> Self {
        adding(.between("version", .int(lower), .int(upper)))
    }

    @discardableResult
    public func withVersionIsKnown() -> Self {
        adding(.isNotNull("version"))
    }

    @discardableResult
    public func withVersionIsUnknown() -> Self {
        adding(.isNull("version"))
    }


    @discardableResult
    public func withPlatformMatching<ChildState: Sendable>(
        _ child: PlatformRequest<ChildState>
    ) -> Self {
        adding(.inSubquery("platform", RelationQueryPlan(child.toQuery()), "id"))
    }

    @discardableResult
    public func withoutPlatformMatching<ChildState: Sendable>(
        _ child: PlatformRequest<ChildState>
    ) -> Self {
        adding(.notInSubquery("platform", RelationQueryPlan(child.toQuery()), "id"))
    }

    @discardableResult
    public func withSchoolTypeMatching<ChildState: Sendable>(
        _ child: SchoolTypeRequest<ChildState>
    ) -> Self {
        adding(.inSubquery("schoolType", RelationQueryPlan(child.toQuery()), "id"))
    }

    @discardableResult
    public func withoutSchoolTypeMatching<ChildState: Sendable>(
        _ child: SchoolTypeRequest<ChildState>
    ) -> Self {
        adding(.notInSubquery("schoolType", RelationQueryPlan(child.toQuery()), "id"))
    }


    @discardableResult
    public func facetByPlatformAs<NestedState: Sendable>(
        _ name: String,
        _ request: PlatformRequest<NestedState>,
        includeAllFacets: Bool = true
    ) -> Self {
        var copy = self
        copy.query.facets.append(FacetRequest(
            name: name,
            relationName: "platform",
            query: request.toQuery(),
            includeAllFacets: includeAllFacets))
        return copy
    }


    @discardableResult
    public func facetBySchoolTypeAs<NestedState: Sendable>(
        _ name: String,
        _ request: SchoolTypeRequest<NestedState>,
        includeAllFacets: Bool = true
    ) -> Self {
        var copy = self
        copy.query.facets.append(FacetRequest(
            name: name,
            relationName: "schoolType",
            query: request.toQuery(),
            includeAllFacets: includeAllFacets))
        return copy
    }


    @discardableResult
    public func count() -> Self { countAs("count") }

    @discardableResult
    public func countAs(_ alias: String) -> Self {
        var copy = self
        copy.query.aggregates.append(QueryAggregate(.count, field: "*", alias: alias))
        return copy
    }

    @discardableResult
    public func minStudentCapacity() -> Self {
        minStudentCapacityAs("minOfStudentCapacity")
    }

    @discardableResult
    public func minStudentCapacityAs(_ alias: String) -> Self {
        var copy = self
        copy.query.aggregates.append(QueryAggregate(.min, field: "studentCapacity", alias: alias))
        return copy
    }


    @discardableResult
    public func maxStudentCapacity() -> Self {
        maxStudentCapacityAs("maxOfStudentCapacity")
    }

    @discardableResult
    public func maxStudentCapacityAs(_ alias: String) -> Self {
        var copy = self
        copy.query.aggregates.append(QueryAggregate(.max, field: "studentCapacity", alias: alias))
        return copy
    }


    @discardableResult
    public func sumStudentCapacity() -> Self {
        sumStudentCapacityAs("sumOfStudentCapacity")
    }

    @discardableResult
    public func sumStudentCapacityAs(_ alias: String) -> Self {
        var copy = self
        copy.query.aggregates.append(QueryAggregate(.sum, field: "studentCapacity", alias: alias))
        return copy
    }


    @discardableResult
    public func avgStudentCapacity() -> Self {
        avgStudentCapacityAs("avgOfStudentCapacity")
    }

    @discardableResult
    public func avgStudentCapacityAs(_ alias: String) -> Self {
        var copy = self
        copy.query.aggregates.append(QueryAggregate(.avg, field: "studentCapacity", alias: alias))
        return copy
    }










    @discardableResult
    public func groupById() -> Self {
        var copy = self
        copy.query.groupBy.append("id")
        return copy
    }

    @discardableResult
    public func groupByPlatform() -> Self {
        var copy = self
        copy.query.groupBy.append("platform")
        return copy
    }

    @discardableResult
    public func groupBySchoolType() -> Self {
        var copy = self
        copy.query.groupBy.append("schoolType")
        return copy
    }

    @discardableResult
    public func groupByName() -> Self {
        var copy = self
        copy.query.groupBy.append("name")
        return copy
    }

    @discardableResult
    public func groupByAddress() -> Self {
        var copy = self
        copy.query.groupBy.append("address")
        return copy
    }

    @discardableResult
    public func groupByEstablishedDate() -> Self {
        var copy = self
        copy.query.groupBy.append("establishedDate")
        return copy
    }

    @discardableResult
    public func groupByStudentCapacity() -> Self {
        var copy = self
        copy.query.groupBy.append("studentCapacity")
        return copy
    }

    @discardableResult
    public func groupByActive() -> Self {
        var copy = self
        copy.query.groupBy.append("active")
        return copy
    }

    @discardableResult
    public func groupByCreateTime() -> Self {
        var copy = self
        copy.query.groupBy.append("createTime")
        return copy
    }

    @discardableResult
    public func groupByUpdateTime() -> Self {
        var copy = self
        copy.query.groupBy.append("updateTime")
        return copy
    }

    @discardableResult
    public func groupByVersion() -> Self {
        var copy = self
        copy.query.groupBy.append("version")
        return copy
    }

    private func adding(_ expression: TeaQLExpression) -> Self {
        var copy = self
        copy.query.filter = copy.query.filter.map { .and([$0, expression]) } ?? expression
        return copy
    }

    private func removingActiveVersionFilter(
        _ expression: TeaQLExpression?
    ) -> TeaQLExpression? {
        guard let expression else { return nil }
        let active = TeaQLExpression.greaterThanOrEqual("version", .int(1))
        if expression == active { return nil }
        guard case .and(let items) = expression else { return expression }
        let retained = items.compactMap { removingActiveVersionFilter($0) }
        if retained.isEmpty { return nil }
        if retained.count == 1 { return retained[0] }
        return .and(retained)
    }
}

public extension SchoolRequest where State == RequestExecutable {
    private func ensureIntent() throws {
        guard let comment = query.comment,
              !comment.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            throw TeaQLError.execution("Comment is required before execution")
        }
        guard let purpose = query.purpose,
              !purpose.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            throw TeaQLError.execution("Purpose is required before execution")
        }
    }

    func newEntity(_ context: UserContext) throws -> School {
        try ensureIntent()
        return context.initializeEntity("School", School())
    }

    func executeForList(_ context: UserContext) async throws -> SmartList<School> {
        try ensureIntent()
        let result = try await context.execute(query)
        let queryRoot = EntityRoot()
        return SmartList(
            try result.records.map { try School.from(record: $0, root: queryRoot) },
            facets: result.facets)
    }

    func executeForRows(_ context: UserContext) async throws -> SmartList<TeaQLRecord> {
        try ensureIntent()
        let result = try await context.execute(query)
        return SmartList(result.records, facets: result.facets)
    }

    func executeForPage(
        _ context: UserContext, offset: Int, limit: Int
    ) async throws -> TeaQLPage<School> {
        try ensureIntent()
        var pageQuery = query
        pageQuery.offset = offset
        pageQuery.limit = limit
        let result = try await context.execute(pageQuery)
        let observation = await context.idSetPaginationObservation()
        let total: Int
        if pageQuery.idSetPagination != nil && observation.countAccuracy == "EXACT" {
            total = observation.count
        } else {
            total = try await context.count(pageQuery)
        }
        let queryRoot = EntityRoot()
        let items = SmartList(
            try result.records.map { try School.from(record: $0, root: queryRoot) },
            totalCount: total)
        return TeaQLPage(items: items, total: total, offset: offset, limit: limit)
    }
}