// Generated by TeaQL. Do not edit directly.
import Foundation
import TeaQLCore

public struct SchoolTypeRequest<State: Sendable>: Sendable {
    private var query: SelectQuery

    init(query: SelectQuery) { self.query = query }

    @discardableResult
    public func comment(_ value: String) -> Self {
        var copy = self; copy.query.comment = value; return copy
    }

    public func purpose(_ value: String) -> SchoolTypeRequest<RequestExecutable> {
        var copy = query; copy.purpose = value
        return SchoolTypeRequest<RequestExecutable>(query: copy)
    }

    @discardableResult
    public func limit(_ value: Int) -> Self {
        var copy = self; copy.query.limit = value; return copy
    }

    @discardableResult
    public func topNProbeParentThreshold(_ value: Int) -> Self {
        var copy = self; copy.query.topNProbeParentThreshold(value); return copy
    }

    @discardableResult
    public func hardLimit(_ value: Int) -> Self {
        var copy = self; copy.query.hardLimit = value; return copy
    }

    @discardableResult
    public func offset(_ value: Int) -> Self {
        var copy = self; copy.query.offset = value; return copy
    }

    @discardableResult
    public func optimizeForContinuousPageFetch() -> Self {
        optimizeForContinuousPageFetch(namespace: "default", ttlSeconds: 600)
    }

    @discardableResult
    public func optimizeForContinuousPageFetch(namespace: String, ttlSeconds: Int) -> Self {
        var copy = self
        copy.query.continuousPage = ContinuousPageFetchOptions(
            namespace: namespace, ttlSeconds: ttlSeconds)
        return copy
    }

    @discardableResult
    public func optimizePaginationWithIdSet() -> Self {
        optimizePaginationWithIdSet(namespace: "default", ttlSeconds: 600, maxIds: 3_000_000)
    }

    @discardableResult
    public func optimizePaginationWithIdSet(
        namespace: String, ttlSeconds: Int, maxIds: Int
    ) -> Self {
        var copy = self
        copy.query.idSetPagination = IdSetPaginationOptions(
            namespace: namespace, ttlSeconds: ttlSeconds, maxIds: maxIds)
        return copy
    }

    public func toQuery() -> SelectQuery { query }

    /// Includes both active and soft-deleted rows. Callers must still provide
    /// Comment and Purpose before execution.
    @discardableResult
    public func withDeletedRows() -> Self {
        var copy = self
        copy.query.filter = removingActiveVersionFilter(copy.query.filter)
        return copy
    }

    /// Returns only soft-deleted rows, represented by a negative version.
    @discardableResult
    public func deletedRowsOnly() -> Self {
        withDeletedRows().adding(.lessThanOrEqual("version", .int(-1)))
    }

    @discardableResult
    public func selectSelfFields() -> Self {
        var copy = self
        copy.query.projection = ["platform", "id", "name", "code", "displayOrder", "version"]
        return copy
    }

    @discardableResult
    public func selectId() -> Self {
        var copy = self
        if !copy.query.projection.contains("id") {
            copy.query.projection.append("id")
        }
        return copy
    }


    @discardableResult
    public func selectName() -> Self {
        var copy = self
        if !copy.query.projection.contains("name") {
            copy.query.projection.append("name")
        }
        return copy
    }


    @discardableResult
    public func selectCode() -> Self {
        var copy = self
        if !copy.query.projection.contains("code") {
            copy.query.projection.append("code")
        }
        return copy
    }


    @discardableResult
    public func selectDisplayOrder() -> Self {
        var copy = self
        if !copy.query.projection.contains("displayOrder") {
            copy.query.projection.append("displayOrder")
        }
        return copy
    }


    @discardableResult
    public func selectVersion() -> Self {
        var copy = self
        if !copy.query.projection.contains("version") {
            copy.query.projection.append("version")
        }
        return copy
    }


    @discardableResult
    public func selectPlatform() -> Self {
        selectPlatformWith(Q.platformsWithMinimalFields())
    }

    @discardableResult
    public func selectPlatformWith<ChildState: Sendable>(
        _ child: PlatformRequest<ChildState>
    ) -> Self {
        var copy = self
        if !copy.query.projection.contains("platform") {
            copy.query.projection.append("platform")
        }
        copy.query.relationQuery(
            "platformEntity",
            localKey: "platform",
            foreignKey: "id",
            many: false,
            query: child.toQuery())
        return copy
    }

    @discardableResult
    public func orderByPlatformAscending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("platform", .ascending)); return copy
    }

    @discardableResult
    public func orderByPlatformDescending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("platform", .descending)); return copy
    }

    @discardableResult
    public func orderByIdAscending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("id", .ascending)); return copy
    }

    @discardableResult
    public func orderByIdDescending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("id", .descending)); return copy
    }

    @discardableResult
    public func orderByNameAscending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("name", .ascending)); return copy
    }

    @discardableResult
    public func orderByNameDescending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("name", .descending)); return copy
    }

    @discardableResult
    public func orderByCodeAscending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("code", .ascending)); return copy
    }

    @discardableResult
    public func orderByCodeDescending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("code", .descending)); return copy
    }

    @discardableResult
    public func orderByDisplayOrderAscending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("displayOrder", .ascending)); return copy
    }

    @discardableResult
    public func orderByDisplayOrderDescending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("displayOrder", .descending)); return copy
    }

    @discardableResult
    public func orderByVersionAscending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("version", .ascending)); return copy
    }

    @discardableResult
    public func orderByVersionDescending() -> Self {
        var copy = self; copy.query.orderBy.append(OrderBy("version", .descending)); return copy
    }

    @discardableResult
    public func selectSchoolList() -> Self {
        selectSchoolListWith(SchoolRequest<RequestDraft>(
            query: SelectQuery(entity: School.descriptor)))
    }

    @discardableResult
    public func selectSchoolListWith<ChildState: Sendable>(
        _ child: SchoolRequest<ChildState>
    ) -> Self {
        var copy = self
        copy.query.relationQuery(
            "schoolList",
            localKey: "id",
            foreignKey: "schoolType",
            many: true,
            query: child.toQuery())
        return copy
    }

    @discardableResult
    public func countSchools() -> Self {
        countSchoolsAs("countSchools")
    }

    @discardableResult
    public func countSchoolsAs(_ alias: String) -> Self {
        countSchoolsWith(alias, Q.schools())
    }

    @discardableResult
    public func countSchoolsWith<ChildState: Sendable>(
        _ alias: String, _ child: SchoolRequest<ChildState>
    ) -> Self {
        var copy = self
        var childQuery = child.toQuery()
        childQuery.aggregates.append(QueryAggregate(.count, field: "id", alias: alias))
        copy.query.relationAggregate(
            "schoolList", foreignKey: "schoolType", alias: alias,
            query: childQuery, singleResult: true)
        return copy
    }

    @discardableResult
    public func minStudentCapacityOfSchools() -> Self {
        minStudentCapacityOfSchoolsAs(
            "minOfStudentCapacityOfSchools",
            Q.schools())
    }

    @discardableResult
    public func minStudentCapacityOfSchoolsAs<ChildState: Sendable>(
        _ alias: String, _ child: SchoolRequest<ChildState>
    ) -> Self {
        var copy = self
        var childQuery = child.toQuery()
        childQuery.aggregates.append(
            QueryAggregate(.min, field: "studentCapacity", alias: "min_studentCapacity"))
        copy.query.relationAggregate(
            "schoolList", foreignKey: "schoolType", alias: alias,
            query: childQuery, singleResult: true)
        return copy
    }


    @discardableResult
    public func maxStudentCapacityOfSchools() -> Self {
        maxStudentCapacityOfSchoolsAs(
            "maxOfStudentCapacityOfSchools",
            Q.schools())
    }

    @discardableResult
    public func maxStudentCapacityOfSchoolsAs<ChildState: Sendable>(
        _ alias: String, _ child: SchoolRequest<ChildState>
    ) -> Self {
        var copy = self
        var childQuery = child.toQuery()
        childQuery.aggregates.append(
            QueryAggregate(.max, field: "studentCapacity", alias: "max_studentCapacity"))
        copy.query.relationAggregate(
            "schoolList", foreignKey: "schoolType", alias: alias,
            query: childQuery, singleResult: true)
        return copy
    }


    @discardableResult
    public func sumStudentCapacityOfSchools() -> Self {
        sumStudentCapacityOfSchoolsAs(
            "sumOfStudentCapacityOfSchools",
            Q.schools())
    }

    @discardableResult
    public func sumStudentCapacityOfSchoolsAs<ChildState: Sendable>(
        _ alias: String, _ child: SchoolRequest<ChildState>
    ) -> Self {
        var copy = self
        var childQuery = child.toQuery()
        childQuery.aggregates.append(
            QueryAggregate(.sum, field: "studentCapacity", alias: "sum_studentCapacity"))
        copy.query.relationAggregate(
            "schoolList", foreignKey: "schoolType", alias: alias,
            query: childQuery, singleResult: true)
        return copy
    }


    @discardableResult
    public func avgStudentCapacityOfSchools() -> Self {
        avgStudentCapacityOfSchoolsAs(
            "avgOfStudentCapacityOfSchools",
            Q.schools())
    }

    @discardableResult
    public func avgStudentCapacityOfSchoolsAs<ChildState: Sendable>(
        _ alias: String, _ child: SchoolRequest<ChildState>
    ) -> Self {
        var copy = self
        var childQuery = child.toQuery()
        childQuery.aggregates.append(
            QueryAggregate(.avg, field: "studentCapacity", alias: "avg_studentCapacity"))
        copy.query.relationAggregate(
            "schoolList", foreignKey: "schoolType", alias: alias,
            query: childQuery, singleResult: true)
        return copy
    }






    @discardableResult
    public func filterByPlatform(_ value: Int64) -> Self {
        adding(.equal("platform", .int(value)))
    }

    @discardableResult
    public func filterByPlatformIn(_ values: [Int64]) -> Self {
        adding(.inList("platform", values.map(TeaQLValue.int)))
    }

    @discardableResult
    public func withPlatformIsKnown() -> Self {
        adding(.isNotNull("platform"))
    }

    @discardableResult
    public func withPlatformIsUnknown() -> Self {
        adding(.isNull("platform"))
    }


    @discardableResult
    public func withIdIs(_ value: Int64) -> Self {
        adding(.equal("id", .int(value)))
    }

    @discardableResult
    public func withIdIn(_ values: [Int64]) -> Self {
        adding(.inList("id", values.map { .int($0) }))
    }

    @discardableResult
    public func withIdIsNot(_ value: Int64) -> Self {
        adding(.notEqual("id", .int(value)))
    }

    @discardableResult
    public func withIdNotIn(_ values: [Int64]) -> Self {
        adding(.notInList("id", values.map { .int($0) }))
    }

    @discardableResult
    public func withIdGreaterThan(_ value: Int64) -> Self {
        adding(.greaterThan("id", .int(value)))
    }

    @discardableResult
    public func withIdGreaterThanOrEqualTo(_ value: Int64) -> Self {
        adding(.greaterThanOrEqual("id", .int(value)))
    }

    @discardableResult
    public func withIdLessThan(_ value: Int64) -> Self {
        adding(.lessThan("id", .int(value)))
    }

    @discardableResult
    public func withIdLessThanOrEqualTo(_ value: Int64) -> Self {
        adding(.lessThanOrEqual("id", .int(value)))
    }

    @discardableResult
    public func withIdBetween(_ lower: Int64, _ upper: Int64) -> Self {
        adding(.between("id", .int(lower), .int(upper)))
    }

    @discardableResult
    public func withIdIsKnown() -> Self {
        adding(.isNotNull("id"))
    }

    @discardableResult
    public func withIdIsUnknown() -> Self {
        adding(.isNull("id"))
    }


    @discardableResult
    public func withNameIs(_ value: String) -> Self {
        adding(.equal("name", .string(value)))
    }

    @discardableResult
    public func withNameIn(_ values: [String]) -> Self {
        adding(.inList("name", values.map { .string($0) }))
    }

    @discardableResult
    public func withNameIsNot(_ value: String) -> Self {
        adding(.notEqual("name", .string(value)))
    }

    @discardableResult
    public func withNameNotIn(_ values: [String]) -> Self {
        adding(.notInList("name", values.map { .string($0) }))
    }

    @discardableResult
    public func withNameGreaterThan(_ value: String) -> Self {
        adding(.greaterThan("name", .string(value)))
    }

    @discardableResult
    public func withNameGreaterThanOrEqualTo(_ value: String) -> Self {
        adding(.greaterThanOrEqual("name", .string(value)))
    }

    @discardableResult
    public func withNameLessThan(_ value: String) -> Self {
        adding(.lessThan("name", .string(value)))
    }

    @discardableResult
    public func withNameLessThanOrEqualTo(_ value: String) -> Self {
        adding(.lessThanOrEqual("name", .string(value)))
    }

    @discardableResult
    public func withNameBetween(_ lower: String, _ upper: String) -> Self {
        adding(.between("name", .string(lower), .string(upper)))
    }

    @discardableResult
    public func withNameIsKnown() -> Self {
        adding(.isNotNull("name"))
    }

    @discardableResult
    public func withNameIsUnknown() -> Self {
        adding(.isNull("name"))
    }
    @discardableResult
    public func withNameContaining(_ value: String) -> Self {
        adding(.contains("name", value))
    }

    @discardableResult
    public func withNameNotContaining(_ value: String) -> Self {
        adding(.notContains("name", value))
    }

    @discardableResult
    public func withNameStartingWith(_ value: String) -> Self {
        adding(.startsWith("name", value))
    }

    @discardableResult
    public func withNameNotStartingWith(_ value: String) -> Self {
        adding(.notStartsWith("name", value))
    }

    @discardableResult
    public func withNameEndingWith(_ value: String) -> Self {
        adding(.endsWith("name", value))
    }

    @discardableResult
    public func withNameNotEndingWith(_ value: String) -> Self {
        adding(.notEndsWith("name", value))
    }

    @discardableResult
    public func withNameSoundingLike(_ value: String) -> Self {
        adding(.soundingLike("name", value))
    }


    @discardableResult
    public func withCodeIs(_ value: String) -> Self {
        adding(.equal("code", .string(value)))
    }

    @discardableResult
    public func withCodeIn(_ values: [String]) -> Self {
        adding(.inList("code", values.map { .string($0) }))
    }

    @discardableResult
    public func withCodeIsNot(_ value: String) -> Self {
        adding(.notEqual("code", .string(value)))
    }

    @discardableResult
    public func withCodeNotIn(_ values: [String]) -> Self {
        adding(.notInList("code", values.map { .string($0) }))
    }

    @discardableResult
    public func withCodeGreaterThan(_ value: String) -> Self {
        adding(.greaterThan("code", .string(value)))
    }

    @discardableResult
    public func withCodeGreaterThanOrEqualTo(_ value: String) -> Self {
        adding(.greaterThanOrEqual("code", .string(value)))
    }

    @discardableResult
    public func withCodeLessThan(_ value: String) -> Self {
        adding(.lessThan("code", .string(value)))
    }

    @discardableResult
    public func withCodeLessThanOrEqualTo(_ value: String) -> Self {
        adding(.lessThanOrEqual("code", .string(value)))
    }

    @discardableResult
    public func withCodeBetween(_ lower: String, _ upper: String) -> Self {
        adding(.between("code", .string(lower), .string(upper)))
    }

    @discardableResult
    public func withCodeIsKnown() -> Self {
        adding(.isNotNull("code"))
    }

    @discardableResult
    public func withCodeIsUnknown() -> Self {
        adding(.isNull("code"))
    }
    @discardableResult
    public func withCodeContaining(_ value: String) -> Self {
        adding(.contains("code", value))
    }

    @discardableResult
    public func withCodeNotContaining(_ value: String) -> Self {
        adding(.notContains("code", value))
    }

    @discardableResult
    public func withCodeStartingWith(_ value: String) -> Self {
        adding(.startsWith("code", value))
    }

    @discardableResult
    public func withCodeNotStartingWith(_ value: String) -> Self {
        adding(.notStartsWith("code", value))
    }

    @discardableResult
    public func withCodeEndingWith(_ value: String) -> Self {
        adding(.endsWith("code", value))
    }

    @discardableResult
    public func withCodeNotEndingWith(_ value: String) -> Self {
        adding(.notEndsWith("code", value))
    }

    @discardableResult
    public func withCodeSoundingLike(_ value: String) -> Self {
        adding(.soundingLike("code", value))
    }


    @discardableResult
    public func withDisplayOrderIs(_ value: Decimal) -> Self {
        adding(.equal("displayOrder", .decimal(value)))
    }

    @discardableResult
    public func withDisplayOrderIn(_ values: [Decimal]) -> Self {
        adding(.inList("displayOrder", values.map { .decimal($0) }))
    }

    @discardableResult
    public func withDisplayOrderIsNot(_ value: Decimal) -> Self {
        adding(.notEqual("displayOrder", .decimal(value)))
    }

    @discardableResult
    public func withDisplayOrderNotIn(_ values: [Decimal]) -> Self {
        adding(.notInList("displayOrder", values.map { .decimal($0) }))
    }

    @discardableResult
    public func withDisplayOrderGreaterThan(_ value: Decimal) -> Self {
        adding(.greaterThan("displayOrder", .decimal(value)))
    }

    @discardableResult
    public func withDisplayOrderGreaterThanOrEqualTo(_ value: Decimal) -> Self {
        adding(.greaterThanOrEqual("displayOrder", .decimal(value)))
    }

    @discardableResult
    public func withDisplayOrderLessThan(_ value: Decimal) -> Self {
        adding(.lessThan("displayOrder", .decimal(value)))
    }

    @discardableResult
    public func withDisplayOrderLessThanOrEqualTo(_ value: Decimal) -> Self {
        adding(.lessThanOrEqual("displayOrder", .decimal(value)))
    }

    @discardableResult
    public func withDisplayOrderBetween(_ lower: Decimal, _ upper: Decimal) -> Self {
        adding(.between("displayOrder", .decimal(lower), .decimal(upper)))
    }

    @discardableResult
    public func withDisplayOrderIsKnown() -> Self {
        adding(.isNotNull("displayOrder"))
    }

    @discardableResult
    public func withDisplayOrderIsUnknown() -> Self {
        adding(.isNull("displayOrder"))
    }


    @discardableResult
    public func withVersionIs(_ value: Int64) -> Self {
        adding(.equal("version", .int(value)))
    }

    @discardableResult
    public func withVersionIn(_ values: [Int64]) -> Self {
        adding(.inList("version", values.map { .int($0) }))
    }

    @discardableResult
    public func withVersionIsNot(_ value: Int64) -> Self {
        adding(.notEqual("version", .int(value)))
    }

    @discardableResult
    public func withVersionNotIn(_ values: [Int64]) -> Self {
        adding(.notInList("version", values.map { .int($0) }))
    }

    @discardableResult
    public func withVersionGreaterThan(_ value: Int64) -> Self {
        adding(.greaterThan("version", .int(value)))
    }

    @discardableResult
    public func withVersionGreaterThanOrEqualTo(_ value: Int64) -> Self {
        adding(.greaterThanOrEqual("version", .int(value)))
    }

    @discardableResult
    public func withVersionLessThan(_ value: Int64) -> Self {
        adding(.lessThan("version", .int(value)))
    }

    @discardableResult
    public func withVersionLessThanOrEqualTo(_ value: Int64) -> Self {
        adding(.lessThanOrEqual("version", .int(value)))
    }

    @discardableResult
    public func withVersionBetween(_ lower: Int64, _ upper: Int64) -> Self {
        adding(.between("version", .int(lower), .int(upper)))
    }

    @discardableResult
    public func withVersionIsKnown() -> Self {
        adding(.isNotNull("version"))
    }

    @discardableResult
    public func withVersionIsUnknown() -> Self {
        adding(.isNull("version"))
    }


    @discardableResult
    public func withPlatformMatching<ChildState: Sendable>(
        _ child: PlatformRequest<ChildState>
    ) -> Self {
        adding(.inSubquery("platform", RelationQueryPlan(child.toQuery()), "id"))
    }

    @discardableResult
    public func withoutPlatformMatching<ChildState: Sendable>(
        _ child: PlatformRequest<ChildState>
    ) -> Self {
        adding(.notInSubquery("platform", RelationQueryPlan(child.toQuery()), "id"))
    }

    @discardableResult
    public func haveSchools() -> Self {
        withSchoolListMatching(SchoolRequest<RequestDraft>(
            query: SelectQuery(entity: School.descriptor)))
    }

    @discardableResult
    public func haveNoSchools() -> Self {
        withoutSchoolListMatching(SchoolRequest<RequestDraft>(
            query: SelectQuery(entity: School.descriptor)))
    }

    @discardableResult
    public func withSchoolListMatching<ChildState: Sendable>(
        _ child: SchoolRequest<ChildState>
    ) -> Self {
        adding(.inSubquery("id", RelationQueryPlan(child.toQuery()), "schoolType"))
    }

    @discardableResult
    public func withoutSchoolListMatching<ChildState: Sendable>(
        _ child: SchoolRequest<ChildState>
    ) -> Self {
        adding(.notInSubquery("id", RelationQueryPlan(child.toQuery()), "schoolType"))
    }

    @discardableResult
    public func facetByPlatformAs<NestedState: Sendable>(
        _ name: String,
        _ request: PlatformRequest<NestedState>,
        includeAllFacets: Bool = true
    ) -> Self {
        var copy = self
        copy.query.facets.append(FacetRequest(
            name: name,
            relationName: "platform",
            query: request.toQuery(),
            includeAllFacets: includeAllFacets))
        return copy
    }


    @discardableResult
    public func count() -> Self { countAs("count") }

    @discardableResult
    public func countAs(_ alias: String) -> Self {
        var copy = self
        copy.query.aggregates.append(QueryAggregate(.count, field: "*", alias: alias))
        return copy
    }

    @discardableResult
    public func minDisplayOrder() -> Self {
        minDisplayOrderAs("minOfDisplayOrder")
    }

    @discardableResult
    public func minDisplayOrderAs(_ alias: String) -> Self {
        var copy = self
        copy.query.aggregates.append(QueryAggregate(.min, field: "displayOrder", alias: alias))
        return copy
    }


    @discardableResult
    public func maxDisplayOrder() -> Self {
        maxDisplayOrderAs("maxOfDisplayOrder")
    }

    @discardableResult
    public func maxDisplayOrderAs(_ alias: String) -> Self {
        var copy = self
        copy.query.aggregates.append(QueryAggregate(.max, field: "displayOrder", alias: alias))
        return copy
    }


    @discardableResult
    public func sumDisplayOrder() -> Self {
        sumDisplayOrderAs("sumOfDisplayOrder")
    }

    @discardableResult
    public func sumDisplayOrderAs(_ alias: String) -> Self {
        var copy = self
        copy.query.aggregates.append(QueryAggregate(.sum, field: "displayOrder", alias: alias))
        return copy
    }


    @discardableResult
    public func avgDisplayOrder() -> Self {
        avgDisplayOrderAs("avgOfDisplayOrder")
    }

    @discardableResult
    public func avgDisplayOrderAs(_ alias: String) -> Self {
        var copy = self
        copy.query.aggregates.append(QueryAggregate(.avg, field: "displayOrder", alias: alias))
        return copy
    }










    @discardableResult
    public func groupByPlatform() -> Self {
        var copy = self
        copy.query.groupBy.append("platform")
        return copy
    }

    @discardableResult
    public func groupById() -> Self {
        var copy = self
        copy.query.groupBy.append("id")
        return copy
    }

    @discardableResult
    public func groupByName() -> Self {
        var copy = self
        copy.query.groupBy.append("name")
        return copy
    }

    @discardableResult
    public func groupByCode() -> Self {
        var copy = self
        copy.query.groupBy.append("code")
        return copy
    }

    @discardableResult
    public func groupByDisplayOrder() -> Self {
        var copy = self
        copy.query.groupBy.append("displayOrder")
        return copy
    }

    @discardableResult
    public func groupByVersion() -> Self {
        var copy = self
        copy.query.groupBy.append("version")
        return copy
    }

    private func adding(_ expression: TeaQLExpression) -> Self {
        var copy = self
        copy.query.filter = copy.query.filter.map { .and([$0, expression]) } ?? expression
        return copy
    }

    private func removingActiveVersionFilter(
        _ expression: TeaQLExpression?
    ) -> TeaQLExpression? {
        guard let expression else { return nil }
        let active = TeaQLExpression.greaterThanOrEqual("version", .int(1))
        if expression == active { return nil }
        guard case .and(let items) = expression else { return expression }
        let retained = items.compactMap { removingActiveVersionFilter($0) }
        if retained.isEmpty { return nil }
        if retained.count == 1 { return retained[0] }
        return .and(retained)
    }
}

public extension SchoolTypeRequest where State == RequestExecutable {
    private func ensureIntent() throws {
        guard let comment = query.comment,
              !comment.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            throw TeaQLError.execution("Comment is required before execution")
        }
        guard let purpose = query.purpose,
              !purpose.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            throw TeaQLError.execution("Purpose is required before execution")
        }
    }

    func newEntity(_ context: UserContext) throws -> SchoolType {
        try ensureIntent()
        return context.initializeEntity("SchoolType", SchoolType())
    }

    func executeForList(_ context: UserContext) async throws -> SmartList<SchoolType> {
        try ensureIntent()
        let result = try await context.execute(query)
        let queryRoot = EntityRoot()
        return SmartList(
            try result.records.map { try SchoolType.from(record: $0, root: queryRoot) },
            facets: result.facets)
    }

    func executeForRows(_ context: UserContext) async throws -> SmartList<TeaQLRecord> {
        try ensureIntent()
        let result = try await context.execute(query)
        return SmartList(result.records, facets: result.facets)
    }

    func executeForPage(
        _ context: UserContext, offset: Int, limit: Int
    ) async throws -> TeaQLPage<SchoolType> {
        try ensureIntent()
        var pageQuery = query
        pageQuery.offset = offset
        pageQuery.limit = limit
        let result = try await context.execute(pageQuery)
        let observation = await context.idSetPaginationObservation()
        let total: Int
        if pageQuery.idSetPagination != nil && observation.countAccuracy == "EXACT" {
            total = observation.count
        } else {
            total = try await context.count(pageQuery)
        }
        let queryRoot = EntityRoot()
        let items = SmartList(
            try result.records.map { try SchoolType.from(record: $0, root: queryRoot) },
            totalCount: total)
        return TeaQLPage(items: items, total: total, offset: offset, limit: limit)
    }
}