// Generated by TeaQL. Do not edit directly.
import Foundation
import TeaQLCore

public struct WorkItem: TeaQLEntity, TeaQLMutationRootedEntity {
    public var id: Int64 = 0
    public var title: String? = nil
    public var description: String? = nil
    public var platform: Int64 = 0
    public var version: Int64 = 0
    public var platformEntity: Platform?
    private var _loadedFields: Set<String> = []
    public var teaqlEntityRoot = EntityRoot()
    private static let teaqlIDLock = NSLock()
    nonisolated(unsafe) private static var teaqlNextTemporaryID: Int64 = 0
    private var teaqlLedgerID: Int64 = 0
    public var teaqlEntityKey: EntityKey { EntityKey(entity: "WorkItem", id: .int(id == 0 ? teaqlLedgerID : id)) }

    private enum CodingKeys: String, CodingKey {
        case id
        case title
        case description
        case platform
        case version
    }

    public init() {
        Self.teaqlIDLock.lock(); Self.teaqlNextTemporaryID -= 1; teaqlLedgerID = Self.teaqlNextTemporaryID; Self.teaqlIDLock.unlock()
        _loadedFields = Set(["id", "title", "description", "platform", "version"])
        teaqlEntityRoot.markAsNew(teaqlEntityKey)
    }

    public static let descriptor = EntityDescriptor(
        name: "WorkItem",
        table: "work_item_data",
        properties: [
            PropertyDescriptor(name: "id", modelName: "id", column: "id", type: .int, nullable: true, isID: true, isVersion: false),
            PropertyDescriptor(name: "title", modelName: "title", column: "title", type: .string, nullable: true, isID: false, isVersion: false),
            PropertyDescriptor(name: "description", modelName: "description", column: "description", type: .string, nullable: true, isID: false, isVersion: false),
            PropertyDescriptor(name: "platform", modelName: "platform", column: "platform", type: .int, nullable: true, isID: false, isVersion: false),
            PropertyDescriptor(name: "version", modelName: "version", column: "version", type: .int, nullable: true, isID: false, isVersion: true)
        ]
    )

    public static func from(record: TeaQLRecord) throws -> Self {
        var entity = Self()
        entity._loadedFields.removeAll()
        entity.id = record["id"]?.int64Value ?? 0
        if record.keys.contains("id") { entity._loadedFields.insert("id") }
        entity.title = record["title"]?.stringValue ?? nil
        if record.keys.contains("title") { entity._loadedFields.insert("title") }
        entity.description = record["description"]?.stringValue ?? nil
        if record.keys.contains("description") { entity._loadedFields.insert("description") }
        entity.platform = record["platform"]?.int64Value ?? 0
        if record.keys.contains("platform") { entity._loadedFields.insert("platform") }
        entity.version = record["version"]?.int64Value ?? 0
        if record.keys.contains("version") { entity._loadedFields.insert("version") }
        if let relationValue = record["platformEntity"] {
            switch relationValue {
            case .object(let relatedRecord):
                entity.platformEntity = try Platform.from(record: relatedRecord)
            case .null:
                entity.platformEntity = nil
            default:
                throw TeaQLError.execution("Invalid relation payload: platform")
            }
            entity._loadedFields.insert("platformEntity")
        }
        let temporaryKey = entity.teaqlEntityKey
        entity.teaqlLedgerID = entity.id
        entity.teaqlEntityRoot.rekey(temporaryKey, to: entity.teaqlEntityKey)
        entity.teaqlEntityRoot.markAsPersisted(entity.teaqlEntityKey)
        entity.teaqlEntityRoot.setOriginalVersion(entity.teaqlEntityKey, version: entity.version)
        return entity
    }

    public static func from(record: TeaQLRecord, root: EntityRoot) throws -> Self {
        var entity = try from(record: record)
        entity.teaqlAttachRoot(root)
        return entity
    }

    public mutating func teaqlAttachRoot(_ root: EntityRoot) {
        if teaqlEntityRoot !== root { root.merge(from: teaqlEntityRoot); teaqlEntityRoot = root }
    }

    public func toRecord() -> TeaQLRecord {
        [
            "id": .int(id),
            "title": title.map(TeaQLValue.string) ?? .null,
            "description": description.map(TeaQLValue.string) ?? .null,
            "platform": .int(platform),
            "version": .int(version)
        ]
    }

    public func toMutationRecord() -> TeaQLRecord {
        var record: TeaQLRecord = [:]
        if _loadedFields.contains("id") {
            record["id"] = .int(id)
        }
        if _loadedFields.contains("title") {
            record["title"] = title.map(TeaQLValue.string) ?? .null
        }
        if _loadedFields.contains("description") {
            record["description"] = description.map(TeaQLValue.string) ?? .null
        }
        if _loadedFields.contains("platform") {
            record["platform"] = .int(platform)
        }
        if _loadedFields.contains("version") {
            record["version"] = .int(version)
        }
        return record
    }

    public func isLoaded(_ field: String) -> Bool { _loadedFields.contains(field) }

    @discardableResult
    public mutating func markLoadedOnly(_ fields: String...) -> Self {
        _loadedFields = Set(fields)
        return self
    }

    @discardableResult
    public mutating func updateId(_ value: Int64) -> Self {
        self.id = value
        self._loadedFields.insert("id")
        self.teaqlEntityRoot.set(teaqlEntityKey, field: "id", value: .int(value))
        return self
    }


    @discardableResult
    public mutating func updateTitle(_ value: String?) -> Self {
        self.title = value
        self._loadedFields.insert("title")
        self.teaqlEntityRoot.set(teaqlEntityKey, field: "title", value: value.map(TeaQLValue.string) ?? .null)
        return self
    }


    @discardableResult
    public mutating func updateDescription(_ value: String?) -> Self {
        self.description = value
        self._loadedFields.insert("description")
        self.teaqlEntityRoot.set(teaqlEntityKey, field: "description", value: value.map(TeaQLValue.string) ?? .null)
        return self
    }


    @discardableResult
    public mutating func updatePlatform(_ value: Int64) -> Self {
        self.platform = value
        self._loadedFields.insert("platform")
        self.teaqlEntityRoot.set(teaqlEntityKey, field: "platform", value: .int(value))
        return self
    }


    @discardableResult
    public mutating func updateVersion(_ value: Int64) -> Self {
        self.version = value
        self._loadedFields.insert("version")
        self.teaqlEntityRoot.set(teaqlEntityKey, field: "version", value: .int(value))
        return self
    }



    public mutating func markForDeletion() -> Self {
        teaqlEntityRoot.markAsDeleted(teaqlEntityKey)
        return self
    }


    public func auditAs(_ reason: String) -> WorkItemAudited {
        WorkItemAudited(entity: self, reason: reason)
    }
}

public struct WorkItemAudited: Sendable {
    public let entity: WorkItem
    public let reason: String

    public func save(_ context: UserContext) async throws -> WorkItem {
        let saved = try await AuditedEntity(entity: entity, reason: reason).save(context)
        return saved
    }
}
